### ISSUE TITLE
Plugin System

### ISSUE THREAD

**Issue by Holzhaus** [jasperproject/jasper-client#130]
Jasper should use some kind of plugin architecture (e.g. [Yapsy](http://yapsy.sourceforge.net/index.html)), so that it's easy to activate, deactive and add modules.

The Plugin interface class could also define some abstract methods (via the `@abstractmethod` decorator), to tell Plugin developers, which methods are needed for a working plugin.

This would also make it easier for the main code to access available/activated plugins (e.g. in `brain.py` or `vocabcompiler.py`), especially if we want to load plugins from dífferent locations (the jasper base plugins from the installation directory and user-installed plugins in `~/.jasper-client/plugins/`).

What do you think?

**Comment by androbwebb** [comment]
Would be nice to handle priorities on the modules through the plugin manager too.

**Comment by androbwebb** [comment]
Also, events should have configurable "Do Not Disturb" hours.

**Comment by Holzhaus** [comment]
Superseded by issue #280.

**Comment by GustavoMSevero** [comment]
Guys, do you know Chatterbot? DO you know if there is a way to implement chatterbot in Jasper? Or do you know how to teach Jasper new dialogs?
