### ISSUE TITLE
Listening permanently and doing transcription in a thread

### ISSUE THREAD

**Issue by Holzhaus** [jasperproject/jasper-client#136]
@crm416 @shbhrsaha Please check out my branch [listen-forever](https://github.com/Holzhaus/jasper-client/compare/Holzhaus:master...listen-forever).

I've changed the Listen-methods of Mic (see below).

# Rationale
Most of the time, Jasper will detect disturbances in the passiveListen-Method even though we're NOT talking to it (because we're talking to friends, watching tv, whatever).

But because of that, we're opening/closing audio stream *all the time* (literally!). But this also has another downside:
If we really want to talk to Jasper, chances are high, that it's not listening, because it's still transcribing and checking another disturbance and has not yet restarted listening.

## So what's the solution?
1. We turn `passiveListen` into a generator function that only yields a result if `PERSONA` was said and `activeListen` transcribed something. Also, activeListen reuses the audio stream from passiveListen. Thus, we avoid opening/closing the stream constantly.
2. If a disturbance was detected, we do **not** try to evaluate the frames in the loop. Instead, we're putting the frames into a queue. A thread will automatically grab the frames and evaluate them simultaneously, while the main loop continues to listen for disturbances.
3. The thread waits for frames to be placed into the queue. If there are some, I takes them, writes them to a file, transcribes them, then checks if there's `PERSONA` in there. If not, he just throws the frames and the transcription away and waits for some new frames. But if `PERSONA` was said, he sets a flag.
4. On the next iteration of the main loop, passiveListen will check if the flag has been set. If it was, it unsets it and starts the activeListen process. If something was transcribed, then it yields the result and the loop is continued.

## What we're doing now

- Open Audio Stream
- Listen
- Close Audio Stream
- If disturbance was detected:
  - Write audio to file
  - transcribe stuff
  - If PERSONA was said:
    - Beep
    - Open Audio Stream
    - Listen
    - Close Audio Stream
    - Beep
    - Write audio to file
    - Transcribe
    - Do stuff
- Repeat

## Proposal

- Open Audio Stream
- Loop:
  - If event flag is set
    - Beep
    - Listen
    - Beep
    - Write audio to file
    - Transcribe
    - Do stuff
  - Listen
  - If Disturbance Detected:
    - Pass frames to thread
- Close Audio Stream

And inside the Thread:
- Write audio to file
- transcribe stuff
- If PERSONA was said:
  - Set event flag

**Comment by elmezie** [comment]
How would I go about getting these changes into my Jasper Client?

**Comment by Holzhaus** [comment]
Try out PR #247.

**Comment by Holzhaus** [comment]
#247 was merged into the [v2.0 dev branch](https://github.com/jasperproject/jasper-client/tree/jasper-dev), closing this.
