### ISSUE TITLE
Trouble with manual install instructions using Raspbian and B+ Pi

### ISSUE THREAD

**Issue by EMCP** [jasperproject/jasper-client#140]
I'm trying both the Raspberry Pi provided image, AND the manual instructions.

When I follow the manual instructions http://jasperproject.github.io/documentation/software/#configure-jasper

I am getting an error message on 

`aplay temp.wav` or `aplay -D hw:1,0 temp.wav`

both give the following error and quit

```
ALSA lib pcm_dmix.c:1018:(snd_pcm_dmix_open) unable to open slave
aplay: main:682: audio open error: No such file or directory
```

If I revert the changes to the configuration and reboot, I can play the recorded audio file fine.. but unable to record.

```
arecord new.wav
```

```
arecord: main:682: audio open error No such file or directory
```

Should I try to poke around the Ubuntu/Debian forums ?  In the meantime I just want to update you guys on your instructions.. it doesn't seem to want to work on the B+ model.

**Comment by Holzhaus** [comment]
Thanks. Looks like this was solved after all.

**Comment by kevinzzz007** [comment]
@famanson omg, now my speaker and the mic are both working thanks to your asound.config file!
