### ISSUE TITLE
Running it on Ubuntu

### ISSUE THREAD

**Issue by patvdleer** [jasperproject/jasper-client#20]
Tried to run it on Ubuntu 12.10 64bit, which seems way handier for developing new modules. Due to pip issues I wasn't able to get all the latest packages.

Did the following:

``` bash
sudo apt-get install python-setuptools
sudo easy_install pip
sudo apt-get install python-pocketsphinx python-yaml python-tz python-requests build-essential python-pyaudio
git clone https://github.com/jasperproject/jasper-client.git
#sudo pip install -r jasper-client/client/requirements.txt
sudo pip install APScheduler CherryPy PyYAML Pykka RPi.GPIO argparse beautifulsoup4 facebook-sdk feedparser numpy pifacedigitalio --allow-external pygame python-dateutil python-mpd pytz quantities semantic six ws4py wsgiref requests sphinx
cd jasper-client/client
python populate.py
python main.py
```

results in:

``` bash
===========================================================
 JASPER The Talking Computer                               
 Copyright 2013 Shubhro Saha & Charlie Marsh               
===========================================================
INFO: cmd_ln.c(506): Parsing command line:
\
    -hmm /usr/local/share/pocketsphinx/model/hmm/en_US/hub4wsj_sc_8k \
    -lm languagemodel_persona.lm \
    -dict dictionary_persona.dic 

Current configuration:
[NAME]      [DEFLT]     [VALUE]
-agc        none        none
-agcthresh  2.0     2.000000e+00
-alpha      0.97        9.700000e-01
-ascale     20.0        2.000000e+01
-backtrace  no      no
-beam       1e-48       1.000000e-48
-bestpath   yes     yes
-bestpathlw 9.5     9.500000e+00
-cep2spec   no      no
-ceplen     13      13
-cmn        current     current
-cmninit    8.0     8.0
-compallsen no      no
-dict               dictionary_persona.dic
-dictcase   no      no
-dither     no      no
-doublebw   no      no
-ds     1       1
-fdict              
-feat       1s_c_d_dd   1s_c_d_dd
-featparams         
-fillprob   1e-8        1.000000e-08
-frate      100     100
-fsg                
-fsgusealtpron  yes     yes
-fsgusefiller   yes     yes
-fwdflat    yes     yes
-fwdflatbeam    1e-64       1.000000e-64
-fwdflatefwid   4       4
-fwdflatlw  8.5     8.500000e+00
-fwdflatsfwin   25      25
-fwdflatwbeam   7e-29       7.000000e-29
-fwdtree    yes     yes
-hmm                /usr/local/share/pocketsphinx/model/hmm/en_US/hub4wsj_sc_8k
-input_endian   little      little
-jsgf               
-kdmaxbbi   -1      -1
-kdmaxdepth 0       0
-kdtree             
-latsize    5000        5000
-lda                
-ldadim     0       0
-lifter     0       0
-lm             languagemodel_persona.lm
-lmctl              
-lmname     default     default
-logbase    1.0001      1.000100e+00
-logfn              
-logspec    no      no
-lowerf     133.33334   1.333333e+02
-lpbeam     1e-40       1.000000e-40
-lponlybeam 7e-29       7.000000e-29
-lw     6.5     6.500000e+00
-maxhistpf  100     100
-maxhmmpf   -1      -1
-maxnewoov  20      20
-maxwpf     -1      -1
-mdef               
-mean               
-mfclogdir          
-mixw               
-mixwfloor  0.0000001   1.000000e-07
-mmap       yes     yes
-ncep       13      13
-nfft       512     512
-nfilt      40      40
-nwpen      1.0     1.000000e+00
-pbeam      1e-48       1.000000e-48
-pip        1.0     1.000000e+00
-rawlogdir          
-remove_dc  no      no
-round_filters  yes     yes
-samprate   16000       1.600000e+04
-sdmap              
-seed       -1      -1
-sendump            
-silprob    0.005       5.000000e-03
-smoothspec no      no
-spec2cep   no      no
-svspec             
-tmat               
-tmatfloor  0.0001      1.000000e-04
-topn       4       4
-toprule            
-transform  legacy      legacy
-unit_area  yes     yes
-upperf     6855.4976   6.855498e+03
-usewdphones    no      no
-uw     1.0     1.000000e+00
-var                
-varfloor   0.0001      1.000000e-04
-varnorm    no      no
-verbose    no      no
-warp_params            
-warp_type  inverse_linear  inverse_linear
-wbeam      7e-29       7.000000e-29
-wip        0.65        6.500000e-01
-wlen       0.025625    2.562500e-02

ERROR: "acmod.c", line 88: Must specify -mdef or -hmm
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    "languagemodel_persona.lm", "dictionary_persona.dic")
  File "/home/patrick/git/jasper-client/client/mic.py", line 41, in __init__
    hmm=hmdir, lm=lmd_persona, dict=dictd_persona)
  File "pocketsphinx.pyx", line 258, in pocketsphinx.Decoder.__cinit__
RuntimeError: Failed to initialize PocketSphinx
```

**Comment by twinspica14** [comment]
can u help me running on rpi b,plz respond,

guys just give a hint, i tried on B B+ UBUNTU 14.04
all get to same step

INFO:client.stt:Transcribed: ['NOW IN']
INFO:client.stt:Transcribed: ['']
INFO:client.stt:Transcribed: ['IN']
INFO:client.stt:Transcribed: ['JASPER']
INFO:client.stt:Transcribed: ['TODAY NEWS TODAY']
INFO:client.stt:Transcribed: ['']
INFO:client.stt:Transcribed: ['']
INFO:client.stt:Transcribed: ['IS BEING']
INFO:client.stt:Transcribed: ['']

still no outut yet

**Comment by FreakErn** [comment]
I don't have any idea what you need to do on ubuntu, but maybe on the raspberry, do you have an external usb sound card?

please post the output of `aplay -l`

Where are your speakers connected? usb sound card or audio out on the raspberry itself?
Did you try the other one?

Try `alsamixer` to raise up the volume. For the speakers and the microphone.
What kind of microphone are you using?

Try a speaker test with
`speaker-test -c2 -D hw:1,0` for the raspberry pi onboard sound (which is default for jasper afaik)

If your speaker are working try with `arecord -f dat test.wav` to record something (Ctrl+C to stop recording) and after that try play that file with `aplay -f dat -D hw:1,0 test.wav`

**Comment by JoelVinayKumar** [comment]
joelvinaykumar@Deadpool:~$ cd ~/jasper/client
joelvinaykumar@Deadpool:~/jasper/client$ python main.py
No handlers could be found for logger "cmuclmtk"
*******************************************************
*             JASPER - THE TALKING COMPUTER           *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
WARNING:root:tts_engine not specified in profile, defaulting to 'espeak-tts'
ERROR:root:Error occured!
Traceback (most recent call last):
  File "../jasper.py", line 143, in <module>
    app = Jasper()
  File "../jasper.py", line 102, in __init__
    tts_engine_class = tts.get_engine_by_slug(tts_engine_slug)
  File "../client/tts.py", line 665, in get_engine_by_slug
    "missing dependencies, etc.)") % slug)
ValueError: TTS engine 'espeak-tts' is not available (due to missing dependencies, etc.)
joelvinaykumar@Deadpool:~/jasper/client$

**Comment by JoelVinayKumar** [comment]
Can somebody help me with this ! I'm not able to proceed after Pocket Sphinx & that too its not installing.
I tried youart command....but it says command not found.

**Comment by Renezera** [comment]
Hello there
I was able to install all the components for Jasper on my Ubuntu Mate, but I get no sound return when I say "Jasper".
During alsa config and temp.wav test sound, I was able to record and hear the file.
Can someone help me figure out what's going on with the sound on jasper?
Thanks

**Comment by andweber** [comment]
are you using Jasper "master"-branch or "jasper-dev" Branch

In case of the master branch, have a look at client/tts.py. In line  76 is the aplay command used to play audio:
`cmd = ['aplay', '-D', 'plughw:1,0', str(filename)]`
You may need to adapt the plughw option depending on your system, e.g. specifying which audio output device should be used.

**Comment by Renezera** [comment]
adndweber - I problably love you! Thanks
