### ISSUE TITLE
Compatible bit rates

### ISSUE THREAD

**Issue by vondeckerstein** [jasperproject/jasper-client#226]
So far with three different USB input devices(one USB microphone, two USB soundcards) I am unable to get jasper to work. I have confirmed in the python interpreter (with a pyaudio instance) that each device supports a bitrate of 44100 or 48000, but not the jasper default 16000.

Running it without editing mic.py causes an error:
  File "/usr/lib/pymodules/python2.7/pyaudio.py", line 714, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/lib/pymodules/python2.7/pyaudio.py", line 396, in __init__
    self._stream = pa.open(**arguments)
IOError: [Errno Invalid sample rate] -9997

Increasing the rate in mic.py to 48000(and the chunk to 4096)  causes an error:
  File "/home/pi/jasper/client/mic.py", line 117, in passiveListen
    data = stream.read(CHUNK)
  File "/usr/lib/pymodules/python2.7/pyaudio.py", line 564, in read
    return pa.read_stream(self._stream, num_frames)
IOError: [Errno Input overflowed] -9981

out of the three devices, one defaults to 48000 so i suspect it should work. what am i doing wrong?

**Comment by Holzhaus** [comment]
Thanks to #247 (which was merged into the [v2.0 dev branch](https://github.com/jasperproject/jasper-client/tree/jasper-dev)), audio devices will soon be configurable. Closing.
