### ISSUE TITLE
Profile.yml

### ISSUE THREAD

**Issue by chandlerpl** [jasperproject/jasper-client#230]
this probably seems stupid but I ran the populate.py and it ran through and then at the end this came up
"Writing to profile...
Done."

However I have looked everywhere for the profile.yml so I can add my Facebook key in and Spotify intergration and can't seem to find it. 
I'm using SSH I don't know if that has anything to do with it or not.

I also got this when I tried to run it,
# 

 JASPER The Talking Computer
#  Copyright 2013 Shubhro Saha & Charlie Marsh

WARNING:root:tts_engine not specified in profile, defaulting to 'espeak-tts'
ERROR:client.vocabcompiler:Fatal compilation Error occured, cleaning up...
Traceback (most recent call last):
  File "/home/pi/jasper/client/vocabcompiler.py", line 157, in compile
    self._compile_vocabulary(phrases)
  File "/home/pi/jasper/client/vocabcompiler.py", line 263, in _compile_vocabulary
    vocabulary = self._compile_languagemodel(text, self.languagemodel_file)
  File "/home/pi/jasper/client/vocabcompiler.py", line 284, in _compile_languagemodel
    cmuclmtk.text2vocab(text, vocab_file)
  File "/usr/local/lib/python2.7/dist-packages/cmuclmtk/__init__.py", line 485, in text2vocab
    text2wfreq(text, wfreq_file, **text2wfreq_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/cmuclmtk/**init**.py", line 114, in text2wfreq
    raise ConversionError("'%s' returned with non-zero exit status '%s'" % (cmd[0], exitcode))
ConversionError: 'text2wfreq' returned with non-zero exit status '127'
ERROR:root:Error occured!
Traceback (most recent call last):
  File "/home/pi/jasper/jasper.py", line 140, in <module>
    app = Jasper()
  File "/home/pi/jasper/jasper.py", line 104, in **init**
    stt.PocketSphinxSTT(**stt.PocketSphinxSTT.get_config()),
  File "/home/pi/jasper/client/stt.py", line 144, in get_config
    config['vocabulary'].compile(vocabcompiler.get_all_phrases())
  File "/home/pi/jasper/client/vocabcompiler.py", line 165, in compile
    raise e
ConversionError: 'text2wfreq' returned with non-zero exit status '127'

I have tried redoing the setup and tried the populate.py again and nothing seems to have fixed it.

EDIT: I should also mention that the install was the download version of Jasper and then imaged onto my RPi not the manual version.

Thanks in advance, 
Chandler

**Comment by ShunJianLee** [comment]
@chandlerpl may i know how to locate your FST model (g014b2b.fst) and your Hidden Markov Model directory (hub4wsj_sc_8k). Thanks

**Comment by chandlerpl** [comment]
I believe you can search for them in Rasbian using
Sudo find / -name "g014b2b.fst"

**Comment by GeoBeBee** [comment]
Regarding g014b2b.fst, see: https://jasperproject.github.io/documentation/installation/
You'll then have: phonetisaurus/g014b2b/g014b2b.fst

Regarding your HMM (hub4wsj_sc_8), I previously directed you here:
https://github.com/GeoBeBee/mySystem/blob/master/Jasper-dev_onPocketPhinx_5preAlpha.txt

**Comment by raghuramtce** [comment]
there is an error coming in the alsamixer cnonfiguration... in sound card settings usb codec option itself is not present for me.. can anyone help

**Comment by raghuramtce** [comment]
my profile is also not being created... output is coming s it does not exist..
