### ISSUE TITLE
Jasper Wont start

### ISSUE THREAD

**Issue by BluGeni** [jasperproject/jasper-client#262]
When I run jasper i get this:(im not sure how to debug this or what went wrong)
#  `/home/pi/jasper/jasper.py

 JASPER The Talking Computer
#  Copyright 2013 Shubhro Saha & Charlie Marsh

WARNING:root:tts_engine not specified in profile, defaulting to 'espeak-tts'
ALSA lib pcm_direct.c:980:(snd1_pcm_direct_initialize_slave) unable to install hw params
ALSA lib pcm_dsnoop.c:623:(snd_pcm_dsnoop_open) unable to initialize slave
ALSA lib pcm_direct.c:980:(snd1_pcm_direct_initialize_slave) unable to install hw params
ALSA lib pcm_dmix.c:1030:(snd_pcm_dmix_open) unable to initialize slave
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

ALSA lib pcm_direct.c:980:(snd1_pcm_direct_initialize_slave) unable to install hw params
ALSA lib pcm_dsnoop.c:623:(snd_pcm_dsnoop_open) unable to initialize slave
ALSA lib pcm_direct.c:980:(snd1_pcm_direct_initialize_slave) unable to install hw params
ALSA lib pcm_dmix.c:1030:(snd_pcm_dmix_open) unable to initialize slave
ALSA lib pcm_dmix.c:957:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
ALSA lib pcm_direct.c:980:(snd1_pcm_direct_initialize_slave) unable to install hw params
ALSA lib pcm_dmix.c:1030:(snd_pcm_dmix_open) unable to initialize slave
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
Traceback (most recent call last):
  File "/home/pi/jasper/jasper.py", line 142, in <module>
    app.run()
  File "/home/pi/jasper/jasper.py", line 111, in run
    conversation = Conversation("JASPER", self.mic, self.config)
  File "/home/pi/jasper/client/conversation.py", line 15, in **init**
    self.notifier = Notifier(profile)
  File "/home/pi/jasper/client/notifier.py", line 35, in **init**
    sched.add_job(self.gather, 'interval', seconds=30)
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/schedulers/base.py", line 330, in add_job
    'trigger': self._create_trigger(trigger, trigger_args),
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/schedulers/base.py", line 782, in _create_trigger
    return self._create_plugin_instance('trigger', trigger, trigger_args)
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/schedulers/base.py", line 766, in _create_plugin_instance
    raise LookupError('No {0} by the name "{1}" was found'.format(type_, alias))
LookupError: No trigger by the name "interval" was found
Exception in thread APScheduler (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 505, in run
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/schedulers/blocking.py", line 27, in _main_loop
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/schedulers/base.py", line 796, in _process_jobs
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'now'`

**Comment by dilipsingh556** [comment]
ALSA lib pcm_dmix.c:1018:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm_dmix.c:1018:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:957:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
ALSA lib pcm_dmix.c:1018:(snd_pcm_dmix_open) unable to open slave
Traceback (most recent call last):
  File "/home/pi/jasper/jasper.py", line 151, in <module>
    app.run()
  File "/home/pi/jasper/jasper.py", line 120, in run
    conversation = Conversation("JASPER", self.mic, self.config)
  File "/home/pi/jasper/client/conversation.py", line 15, in __init__
    self.notifier = Notifier(profile)
  File "/home/pi/jasper/client/notifier.py", line 35, in __init__
    sched.add_job(self.gather, 'interval', seconds=30)
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/schedulers/base.py", line 330, in add_job
    'trigger': self._create_trigger(trigger, trigger_args),
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/schedulers/base.py", line 782, in _create_trigger
    return self._create_plugin_instance('trigger', trigger, trigger_args)
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/schedulers/base.py", line 766, in _create_plugin_instance
    raise LookupError('No {0} by the name "{1}" was found'.format(type_, alias))
LookupError: No trigger by the name "interval" was found
Exception in thread APScheduler (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 505, in run
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/schedulers/blocking.py", line 27, in _main_loop
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/schedulers/base.py", line 796, in _process_jobs
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'now'

**Comment by dilipsingh556** [comment]
After I ran   sudo pip install -r jasper/client/requirements.txt --upgrade
I got the following information. How can i solve this?

/usr/local/lib/python2.7/dist-packages/pip-10.0.1-py2.7.egg/pip/_vendor/urllib3/util/ssl_.py:339: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip-10.0.1-py2.7.egg/pip/_vendor/urllib3/util/ssl_.py:137: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
Requirement already up-to-date: APScheduler==3.0.1 in /usr/local/lib/python2.7/dist-packages (from -r jasper/client/requirements.txt (line 2)) (3.0.1)
Requirement already up-to-date: argparse==1.2.2 in /usr/local/lib/python2.7/dist-packages (from -r jasper/client/requirements.txt (line 3)) (1.2.2)
Requirement already up-to-date: mock==1.0.1 in /usr/local/lib/python2.7/dist-packages (from -r jasper/client/requirements.txt (line 4)) (1.0.1)
Requirement already up-to-date: pytz==2014.10 in /usr/local/lib/python2.7/dist-packages (from -r jasper/client/requirements.txt (line 5)) (2014.10)
Requirement already up-to-date: PyYAML==3.11 in /usr/local/lib/python2.7/dist-packages (from -r jasper/client/requirements.txt (line 6)) (3.11)
Requirement already up-to-date: requests==2.5.0 in /usr/local/lib/python2.7/dist-packages (from -r jasper/client/requirements.txt (line 7)) (2.5.0)
Requirement already up-to-date: cmuclmtk==0.1.5 in /usr/local/lib/python2.7/dist-packages (from -r jasper/client/requirements.txt (line 10)) (0.1.5)
Requirement already up-to-date: beautifulsoup4==4.3.2 in /usr/local/lib/python2.7/dist-packages (from -r jasper/client/requirements.txt (line 13)) (4.3.2)
Requirement already up-to-date: semantic==1.0.3 in /usr/local/lib/python2.7/dist-packages (from -r jasper/client/requirements.txt (line 14)) (1.0.3)
Requirement already up-to-date: facebook-sdk==0.4.0 in /usr/local/lib/python2.7/dist-packages (from -r jasper/client/requirements.txt (line 17)) (0.4.0)
Requirement already up-to-date: feedparser==5.1.3 in /usr/local/lib/python2.7/dist-packages (from -r jasper/client/requirements.txt (line 20)) (5.1.3)
Requirement already up-to-date: python-dateutil==2.3 in /usr/local/lib/python2.7/dist-packages (from -r jasper/client/requirements.txt (line 23)) (2.3)
Requirement already up-to-date: python-mpd==0.3.0 in /usr/local/lib/python2.7/dist-packages (from -r jasper/client/requirements.txt (line 26)) (0.3.0)
Requirement not upgraded as not directly required: six in /usr/local/lib/python2.7/dist-packages (from APScheduler==3.0.1->-r jasper/client/requirements.txt (line 2)) (1.6.1)
Requirement not upgraded as not directly required: futures; python_version < "3.2" in /usr/local/lib/python2.7/dist-packages (from APScheduler==3.0.1->-r jasper/client/requirements.txt (line 2)) (3.2.0)
Requirement not upgraded as not directly required: tzlocal in /usr/local/lib/python2.7/dist-packages (from APScheduler==3.0.1->-r jasper/client/requirements.txt (line 2)) (1.5.1)
Requirement not upgraded as not directly required: quantities in /usr/local/lib/python2.7/dist-packages (from semantic==1.0.3->-r jasper/client/requirements.txt (line 14)) (0.10.1)
Requirement not upgraded as not directly required: numpy in /usr/local/lib/python2.7/dist-packages (from semantic==1.0.3->-r jasper/client/requirements.txt (line 14)) (1.8.0)
