### ISSUE TITLE
Building phonetisaurus failed

### ISSUE THREAD

**Issue by Binzzzz** [jasperproject/jasper-client#267]
Makefile:51: recipe for target 'Phonetisaurus.o' failed
make: *** [Phonetisaurus.o] Error 1
.
There was a fix that was given at https://aur.archlinux.org/packages/phonetisaurus/ under m01 and that unable to apply that solution

**Comment by Binzzzz** [comment]
I'm a beginner for the contribution of the project . I have found the solution for this for those who are using the Manjaro Linux(Arch Based) where the PKGBUILD will not be asked to edit and it executes on it's own. We cannot edit the make file before executing and to do that please follow these steps:
1: The make file will be available in the temp folder------- In my case /tmp/yaourt-tmp-binoy/aur-phonetisaurus/
2: Goto to temp folder and enter into the phonetisaurus direcutory and then use your editor to edit the PKGBUILD 
3:Inside that package build before the 'make' just paste the above solution CPPFLAGS="-std=c++11"
4.Take the terminal and then restart building the package
5.Done :)

**Comment by Holzhaus** [comment]
Or you could just do:
```
$ CPPFLAGS="-std=c++11" yaourt -S phonetisaurus
```
:)

**Comment by iver3on** [comment]
Python/random.c: In function 'py_getrandom':
Python/random.c:112:28: error: 'GRND_NONBLOCK' undeclared (first use in this function)
     flags = blocking ? 0 : GRND_NONBLOCK;
                            ^
Python/random.c:112:28: note: each undeclared identifier is reported only once for each function it appears in
Python/random.c:140:25: error: 'SYS_getrandom' undeclared (first use in this function)
             n = syscall(SYS_getrandom, dest, n, flags);
                         ^
Makefile:1587: recipe for target 'Python/random.o' failed
