### ISSUE TITLE
Problem encounter when trying to start Jasper in Raspberry B+

### ISSUE THREAD

**Issue by tonylu880042** [jasperproject/jasper-client#274]
I start from the B+ image, and finish the configuration.
However, I can start Jasper with the following message, 
pi@raspberrypi ~ $ /home/pi/jasper/jasper.py
No handlers could be found for logger "client.vocabcompiler"
Traceback (most recent call last):
  File "/home/pi/jasper/jasper.py", line 16, in <module>
    from client.conversation import Conversation
  File "/home/pi/jasper/client/conversation.py", line 3, in <module>
    from notifier import Notifier
  File "/home/pi/jasper/client/notifier.py", line 5, in <module>
    from apscheduler.schedulers.background import BackgroundScheduler
ImportError: No module named schedulers.background
I am new to Raspberry Pi, and have no idea how to deal with this problem.
Any suggestion will be appreciated.
Best regards,
tony

**Comment by Holzhaus** [comment]
You need to install the latest version of APScheduler. Try `pip --upgrade -r client/requirements.txt`.
