### ISSUE TITLE
[Question] Jasper return ' ' with another language 

### ISSUE THREAD

**Issue by Inglebard** [jasperproject/jasper-client#275]
Hi, 

I would like to use jasper with another language. 
I know there are closed issues which talking about it but i don't understand what I suppose to do.

- I got language model file in lm (after convert it from dmp to lm : http://cmusphinx.sourceforge.net/wiki/tutoriallm#converting_model_into_dmp_format )
- I got dictionnary 
- I got accoustic model

In /usr/local/share/pocketsphinx/model/hmm/`language`/ , I put my accoustic model.
In /usr/local/share/pocketsphinx/model/lm/`language`/ , I put my dictionnary and my language file.

In my "profile.yml", I add : 
pocketsphinx:
    hmm_dir: /usr/local/share/pocketsphinx/model/hmm/`language`/ `accoustic_directory`

I don't find a good way to modify path for language model file and dictionnary, so I modify files under : .jasper/vocabularies/pocketsphinx-vocabulary/default/
and replace dictionary an languagemodel files.

Here are all my problems :-) :

- When I launch Jasper, it cannot load all the language model file (+1GB ) so jasper stop, there is a way to generate short and custom language model file from existing one ? (like the default one.)
- What is the correct way to use other folder than "default" ? (for example use custom dictionary and language model files like hmm_dir)
- If I use valid hmm_dir, dictionary and language model files (but different of original installation) Jasper always return ' ' (or "No disturbance detected" of course) 

What I don't understand and what did I do wrong ?

**Comment by Holzhaus** [comment]
This wont work. Dictionary and languagemodel are auto generated by Jasper. Even if you manage to make Sphinx recognize another language, Jasper won't work, because the plugins expect english input. Thus, using a language other than english is not possible at the moment, although we consider this feature for future versions.
