### ISSUE TITLE
virtualBox image of jasper

### ISSUE THREAD

**Issue by ychoucha** [jasperproject/jasper-client#277]
Hello, 

can we make a virtual box of jasper using with virtualBox, to make Jasper using by evryone and not only the raspberry user ?

**Comment by Holzhaus** [comment]
It's already possible to run Jasper on non-raspberrypi computers. I'm also running jasper on my desktop-pc. Just follow the installation instructions.

**Comment by ychoucha** [comment]
Hello,

in fact i make it.
it's works sure, but u can only talk with jasper in command line, no way to make mic work on the virtual box.

so the question why not using a python to make some webservice to communique with jasper for evryone.

just imagine, can make a weBserver and make it talk all the people on the world :)


the way of jasper become more interresting for all people on the world is not using it only on raspberry !!!!
