### ISSUE TITLE
requests.exceptions.ConnectionError: ('Connection Aborted', Error(32, 'Broken Pipe')

### ISSUE THREAD

**Issue by isaacwalkercox** [jasperproject/jasper-client#292]
Hi Guys,

I have downloaded the quickstart version of jasper and have run populate.py but when i run jasper.py it comes up with the above error. Please help?

**Comment by Holzhaus** [comment]
Thanks for taking the time to report a bug. Unfortunately, we can't help you, because you didn't post enough output (you even skipped the Traceback). [Please read this](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html) and then report the bug again. Closing this one.
