### ISSUE TITLE
Jasper STT wrong answers

### ISSUE THREAD

**Issue by mete89** [jasperproject/jasper-client#296]
Hi,

I removed all predefined modules and added 4 modules on Jasper. Each has one words which are LEFT, RIGHT, FORWARD, BACKWARD. (This, the, of etc. are all deleted.)

It compiled new vocabs. It worked fine for exact words. But the problem is, when I say meaningless things it always understand them as LEFT. How can we solve that problem? Can we increase accuracy? Is there a way or suggestion that Jasper not to understand the words which are not in any the list?

I'm using default STT (pocketsphinx).

Thanks

**Comment by Holzhaus** [comment]
You need to compile additional words into the vocabulary, like "WHAT", "WHEN", "IS", "BLA". Otherwise, pocketsphinx will try to map the speech to the closest match in your vocabulary.
