### ISSUE TITLE
No such file or directory: '/root/.jasper/profile.yml'

### ISSUE THREAD

**Issue by teuma86** [jasperproject/jasper-client#302]
hi
First, YES: I have run the populate.py

I have installed Jasper on my pi and it failed to work
So I run python ~/jasper/client/main.py
Then I get 
Traceback (most recent call last):
  File "client/../jasper.py", line 138, in <module>
    app = Jasper()
  File "client/../jasper.py", line 77, in __init__
    with open(new_configfile, "r") as f:
IOError: [Errno 2] No such file or directory: '/root/.jasper/profile.yml'

YES, /root/.jasper does not exist
/home/pi/.jasper does

Any suggestions.

**Comment by teuma86** [comment]
Ignore
This was because I ran python ~/jasper/client/main.py with sudo

**Comment by mbeirouti** [comment]
Why does this error only come up when running as sudo? Do you know?

**Comment by mattcurrycom** [comment]
yeah because you are loading that users environment. Which is different.  Its quite obvious look at the paths in the error.  You should never run it with sudo

**Comment by mbeirouti** [comment]
@mattcurrycom True but how else am I supposed to control the raspberry pi's GPIO pins? You can't do so unless the you have run a program as super user. Any ideas? I tried to echo commands to terminal using the os library but that didnt work either.

**Comment by DarthToker** [comment]
Try sudo apt-get install rpi-update 
I had that prob and that fixed it

**Comment by jamieduk** [comment]
Im on kali linux and im root by default so this error needs to be fixed!

IOError: [Errno 2] No such file or directory: '/root/.jasper/profile.yml'

I touched the above file to create an empty file and now the error is:

*******************************************************
*             JASPER - THE TALKING COMPUTER           *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
ERROR:root:Error occured!
Traceback (most recent call last):
  File "jasper.py", line 146, in <module>
    app = Jasper()
  File "jasper.py", line 86, in __init__
    stt_engine_slug = self.config['stt_engine']
TypeError: 'NoneType' object has no attribute '__getitem__'
