### ISSUE TITLE
Jasper on raspberry pi board ,We are not getting any response when saying "ONE", TWO, "THREE"....etc

### ISSUE THREAD

**Issue by Ajith1231** [jasperproject/jasper-client#312]
Hi All, 
I am able to use Jasper with no problem and ask a couple inbuilt questions like "TIME" etc.

pi@raspberrypi ~/jasper $ ./jasper.py

We are getting the below prints 
*******************************************************
*             JASPER - THE TALKING COMPUTER           *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
WARNING:root:tts_engine not specified in profile, defaulting to 'espeak-tts'
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm_dmix.c:957:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
WARNING:client.notifier:gmail_address or gmail_password not set in profile, Gmail notifier will not be used
INFO:client.stt:Transcribed: ['']
INFO:client.stt:Transcribed: ['IN']
INFO:client.stt:Transcribed: ['ON']
INFO:client.stt:Transcribed: ['IT']
INFO:client.stt:Transcribed: ['DID ON']
FO:client.stt:Transcribed: ['OF IS BUT']
INFO:client.stt:Transcribed: ['IN IN']
INFO:client.stt:Transcribed: ['IS IT BUT']
INFO:client.stt:Transcribed: ['IN IN']
INFO:client.stt:Transcribed: ['SAY IN']
INFO:client.stt:Transcribed: ['IN DID']
FO:client.stt:Transcribed: ['OF IS BUT']
INFO:client.stt:Transcribed: ['IN IN']
INFO:client.stt:Transcribed: ['IS IT BUT']
INFO:client.stt:Transcribed: ['IN IN']
INFO:client.stt:Transcribed: ['SAY IN']
INFO:client.stt:Transcribed: ['IN DID']
FO:client.stt:Transcribed: ['OF IS BUT']
INFO:client.stt:Transcribed: ['IN IN']
INFO:client.stt:Transcribed: ['IS IT BUT']
INFO:client.stt:Transcribed: ['IN IN']
INFO:client.stt:Transcribed: ['SAY IN']
INFO:client.stt:Transcribed: ['IN DID']
FO:client.stt:Transcribed: ['OF IS BUT']
INFO:client.stt:Transcribed: ['IN IN']
INFO:client.stt:Transcribed: ['IS IT BUT']
INFO:client.stt:Transcribed: ['IN IN']
INFO:client.stt:Transcribed: ['SAY IN']
INFO:client.stt:Transcribed: ['IN DID']
FO:client.stt:Transcribed: ['OF IS BUT']
INFO:client.stt:Transcribed: ['IN IN']
INFO:client.stt:Transcribed: ['IS IT BUT']
INFO:client.stt:Transcribed: ['IN IN']
INFO:client.stt:Transcribed: ['SAY IN']
INFO:client.stt:Transcribed: ['IN DID']

INFO:client.stt:Transcribed: ['OF IS BUT']
INFO:client.stt:Transcribed: ['IN IN']
INFO:client.stt:Transcribed: ['IS IT BUT']
INFO:client.stt:Transcribed: ['IN IN']
INFO:client.stt:Transcribed: ['SAY IN']
INFO:client.stt:Transcribed: ['IN DID']

What does the above prints indicate. We need to customize speech to text on jasper command window so we added "ONE", TWO, "THREE".... in the below file 
/home/pi/.jasper/vocabularies/pocketsphinx-vocabulary/keyword/dictionary

We are not getting any response when saying "ONE", TWO, "THREE"....etc and it did not show anything on window our mic and speaker are working fine as its responding to Jasper command.

Did we miss any steps above and where should we need to add commands for creating my own vocabulary(say for example detecting "ONE", TWO, "THREE"....) and so on.

Any help please.

**Comment by Holzhaus** [comment]
Please read [the documentation](http://jasperproject.github.io/documentation/api/standard/#keywords) or ask in the support forum before creating an issue.
