### ISSUE TITLE
no tts engine defined ... but ...

### ISSUE THREAD

**Issue by alban4github** [jasperproject/jasper-client#313]
hello

I just install on my raspberry the whole thing and adding googleTTS in my profile.yml (with KEY and so on)
but when I launch jasper.py it happens not to recognize my profile file as jasper states no TTS engine defined ?
did I miss something ? like chmod profile or so ?
according to install doc all dependencies ok ...

thx
Alban

**Comment by Holzhaus** [comment]
Please read [this](https://github.com/jasperproject/jasper-client/blob/master/CONTRIBUTING.md#reporting-bugs).

**Comment by alban4github** [comment]
ok no help then ... Jasper skipped ...

**Comment by Holzhaus** [comment]
> Please open a new thread in the [support forum](https://groups.google.com/forum/#!forum/jasper-support-forum) instead.
