### ISSUE TITLE
Python2-Pymad not avilable to install

### ISSUE THREAD

**Issue by Binzzzz** [jasperproject/jasper-client#317]
googletts needs python2-pymad as dependencies . please tell me how to configure

**Comment by Holzhaus** [comment]
Please read our [contributing guidelines](https://github.com/jasperproject/jasper-client/blob/master/CONTRIBUTING.md):
> The [bug tracker](https://github.com/jasperproject/jasper-client/issues) at Github is for reporting bugs in Jasper. If encounter problems during installation or compliation of one of Jasper's dependencies for example, do not create a new issue here. Please open a new thread in the [support forum](https://groups.google.com/forum/#!forum/jasper-support-forum) instead.
