### ISSUE TITLE
Problem with requirement.txt

### ISSUE THREAD

**Issue by pbhuvanesh** [jasperproject/jasper-client#321]
Hello all,
             Everytime I run sudo pip install jasper/client/requirements.txt I encounter the following error

pi@raspberrypi ~ $ sudo pip install -r jasper/client/requirements.txt
Downloading/unpacking APScheduler==3.0.1 (from -r jasper/client/requirements.txt (line 2))
  Downloading APScheduler-3.0.1.tar.gz (74Kb): 74Kb downloaded
  Running setup.py egg_info for package APScheduler

Downloading/unpacking argparse==1.2.2 (from -r jasper/client/requirements.txt (line 3))
  Downloading argparse-1.2.2.tar.gz (68Kb): 68Kb downloaded
  Running setup.py egg_info for package argparse

    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.pyo' found anywhere in distribution
    warning: no previously-included files matching '*.orig' found anywhere in distribution
    warning: no previously-included files matching '*.rej' found anywhere in distribution
    no previously-included directories found matching 'doc/_build'
    no previously-included directories found matching 'env24'
    no previously-included directories found matching 'env25'
    no previously-included directories found matching 'env26'
    no previously-included directories found matching 'env27'
Downloading/unpacking mock==1.0.1 (from -r jasper/client/requirements.txt (line 4))
  Downloading mock-1.0.1.tar.gz (818Kb): 818Kb downloaded
  Running setup.py egg_info for package mock

    warning: no files found matching '*.png' under directory 'docs'
    warning: no files found matching '*.css' under directory 'docs'
    warning: no files found matching '*.html' under directory 'docs'
    warning: no files found matching '*.js' under directory 'docs'
Downloading/unpacking pytz==2014.10 (from -r jasper/client/requirements.txt (line 5))
  Downloading pytz-2014.10.tar.bz2 (166Kb): 166Kb downloaded
  Running setup.py egg_info for package pytz

Downloading/unpacking PyYAML==3.11 (from -r jasper/client/requirements.txt (line 6))
  Downloading PyYAML-3.11.tar.gz (248Kb): 248Kb downloaded
  Running setup.py egg_info for package PyYAML

Downloading/unpacking requests==2.5.0 (from -r jasper/client/requirements.txt (line 7))
  Downloading requests-2.5.0.tar.gz (443Kb): 443Kb downloaded
  Running setup.py egg_info for package requests

Downloading/unpacking cmuclmtk==0.1.5 (from -r jasper/client/requirements.txt (line 10))
  Downloading cmuclmtk-0.1.5.tar.gz
  Running setup.py egg_info for package cmuclmtk

Downloading/unpacking beautifulsoup4==4.3.2 (from -r jasper/client/requirements.txt (line 13))
  Downloading beautifulsoup4-4.3.2.tar.gz (143Kb): 143Kb downloaded
  Running setup.py egg_info for package beautifulsoup4

Downloading/unpacking semantic==1.0.3 (from -r jasper/client/requirements.txt (line 14))
  Downloading semantic-1.0.3.tar.gz
  Running setup.py egg_info for package semantic

Requirement already satisfied (use --upgrade to upgrade): facebook-sdk==0.4.0 in /usr/local/lib/python2.7/dist-packages (from -r jasper/client/requirements.txt (line 17))
Requirement already satisfied (use --upgrade to upgrade): feedparser==5.1.3 in /usr/local/lib/python2.7/dist-packages (from -r jasper/client/requirements.txt (line 20))
Downloading/unpacking python-dateutil==2.3 (from -r jasper/client/requirements.txt (line 23))
  Downloading python-dateutil-2.3.tar.gz (191Kb): 191Kb downloaded
  Running setup.py egg_info for package python-dateutil

Requirement already satisfied (use --upgrade to upgrade): python-mpd==0.3.0 in /usr/local/lib/python2.7/dist-packages (from -r jasper/client/requirements.txt (line 26))
Requirement already satisfied (use --upgrade to upgrade): six>=1.4.0 in /usr/local/lib/python2.7/dist-packages (from APScheduler==3.0.1->-r jasper/client/requirements.txt (line 2))
Downloading/unpacking tzlocal (from APScheduler==3.0.1->-r jasper/client/requirements.txt (line 2))
  Downloading tzlocal-1.1.2.zip
  Running setup.py egg_info for package tzlocal

Downloading/unpacking futures (from APScheduler==3.0.1->-r jasper/client/requirements.txt (line 2))
  Downloading futures-2.2.0.tar.gz
  Running setup.py egg_info for package futures

Requirement already satisfied (use --upgrade to upgrade): quantities in /usr/local/lib/python2.7/dist-packages (from semantic==1.0.3->-r jasper/client/requirements.txt (line 14))
Requirement already satisfied (use --upgrade to upgrade): numpy in /usr/local/lib/python2.7/dist-packages (from semantic==1.0.3->-r jasper/client/requirements.txt (line 14))
Installing collected packages: APScheduler, argparse, mock, pytz, PyYAML, requests, cmuclmtk, beautifulsoup4, semantic, python-dateutil, tzlocal, futures
  Found existing installation: APScheduler 2.1.2
    Uninstalling APScheduler:
      Successfully uninstalled APScheduler
  Running setup.py install for APScheduler

  Found existing installation: argparse 1.2.1
    Uninstalling argparse:
      Successfully uninstalled argparse
  Running setup.py install for argparse

    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.pyo' found anywhere in distribution
    warning: no previously-included files matching '*.orig' found anywhere in distribution
    warning: no previously-included files matching '*.rej' found anywhere in distribution
    no previously-included directories found matching 'doc/_build'
    no previously-included directories found matching 'env24'
    no previously-included directories found matching 'env25'
    no previously-included directories found matching 'env26'
    no previously-included directories found matching 'env27'
  Running setup.py install for mock

    warning: no files found matching '*.png' under directory 'docs'
    warning: no files found matching '*.css' under directory 'docs'
    warning: no files found matching '*.html' under directory 'docs'
    warning: no files found matching '*.js' under directory 'docs'
  Found existing installation: pytz 2013b0
    Uninstalling pytz:
      Successfully uninstalled pytz
  Running setup.py install for pytz

  Found existing installation: PyYAML 3.10
    Uninstalling PyYAML:
      Successfully uninstalled PyYAML
  Running setup.py install for PyYAML
    checking if libyaml is compilable
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c build/temp.linux-armv6l-2.7/check_libyaml.c -o build/temp.linux-armv6l-2.7/check_libyaml.o
    build/temp.linux-armv6l-2.7/check_libyaml.c:2:18: fatal error: yaml.h: No such file or directory
    compilation terminated.

    libyaml is not found or a compiler error: forcing --without-libyaml
    (if libyaml is installed correctly, you may need to
     specify the option --include-dirs or uncomment and
     modify the parameter include_dirs in setup.cfg)

  Running setup.py install for requests

  Running setup.py install for cmuclmtk

  Found existing installation: beautifulsoup4 4.2.1
    Uninstalling beautifulsoup4:
      Successfully uninstalled beautifulsoup4
  Running setup.py install for beautifulsoup4

  Found existing installation: semantic 1.0.1
    Uninstalling semantic:
      Successfully uninstalled semantic
  Running setup.py install for semantic

  Found existing installation: python-dateutil 2.1
    Uninstalling python-dateutil:
      Successfully uninstalled python-dateutil
  Running setup.py install for python-dateutil

  Running setup.py install for tzlocal

  Running setup.py install for futures

Successfully installed APScheduler argparse mock pytz PyYAML requests cmuclmtk beautifulsoup4 semantic python-dateutil tzlocal futures
Cleaning up...

How do I fix the issue?

**Comment by Holzhaus** [comment]
Please read our [contributing guidelines](https://github.com/jasperproject/jasper-client/blob/master/CONTRIBUTING.md):
> The [bug tracker](https://github.com/jasperproject/jasper-client/issues) at Github is for reporting bugs in Jasper. If encounter problems during installation or compliation of one of Jasper's dependencies for example, do not create a new issue here. Please open a new thread in the [support forum](https://groups.google.com/forum/#!forum/jasper-support-forum) instead.
