### ISSUE TITLE
Jasper unable to playback spotify playlists

### ISSUE THREAD

**Issue by jsgilly20** [jasperproject/jasper-client#325]
Hey, spent the day playing with Jasper using the premade image, basic modules and commands all work fine. Only when I've tried to get it working with Spotify have I started to get problems. 

I have a spotify premium account.

I have my spotify account details entered correctly in /root/.config/mopidy/mopidy.conf

Jasper responds with "Please give me a moment, I'm loading your spotify playlists" ..... "I'm sorry, please try again later"

ERROR:client.brain:Failed to execute module
Traceback (most recent call last):
  File "/home/pi/jasper/client/brain.py", line 73, in query
    module.handle(text, self.mic, self.profile)
  File "/home/pi/jasper/client/modules/MPDControl.py", line 47, in handle
    music_mode.handleForever()
  File "/home/pi/jasper/client/modules/MPDControl.py", line 160, in handleForever
    self.mic.say("Playing %s" % self.music.current_song())
  File "/home/pi/jasper/client/modules/MPDControl.py", line 204, in wrap
    return func(self, *default_args, **default_kwargs)
  File "/home/pi/jasper/client/modules/MPDControl.py", line 283, in current_song
    item = self.client.playlistinfo(int(self.client.status()["song"]))[0]
KeyError: 'song'

Anyone any ideas? 

I must point out I'm rather new to this.

Thanks.

**Comment by mruba** [comment]
im having the same issue...

**Comment by mruba** [comment]
i reinstalled jasper again without success

**Comment by Holzhaus** [comment]
In the `jasper-dev` branch the MPDcode has been rewritten. If you notice an error, open a new issue.

**Comment by Nikozi93** [comment]
I am having the exact same issue here, this is my output. 
![basic_error](https://user-images.githubusercontent.com/46537542/51402914-7cb74100-1b57-11e9-875c-76db4a60d653.png)

**Comment by Nikozi93** [comment]
> In the `jasper-dev` branch the MPDcode has been rewritten. If you notice an error, open a new issue.

Hello sir, could you pelase explain what do you mean by that? I am having the same issue here and after a lot of frustrating hours trying to make mopidy work as it should, I'm still getting the same error so could you please help?
