### ISSUE TITLE
Jasper logging

### ISSUE THREAD

**Issue by makeacoffeeprj** [jasperproject/jasper-client#329]
Hi everyone,

I don't know why but sometimes Jasper stops working while I'm not using it and I'm not able to understand why because there's no logging to check. Is it possible to force Jasper to write some logs about its operativity? 

Thank you so much,

Diego

**Comment by Holzhaus** [comment]
Don't start it as a cronjob, start it via command line, possibly in `screen`. For additional logging, use the `--debug` argument.
