### ISSUE TITLE
[Errno Invalid sample rate] -9997

### ISSUE THREAD

**Issue by makeacoffeeprj** [jasperproject/jasper-client#330]
Hi guys! I just made a fresh installation of jasper and it fails to run due to this error:

Expression 'SetApproximateSampleRate( pcm, hwParams, sr )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 1968
Expression 'PaAlsaStreamComponent_InitialConfigure( &self->capture, inParams, self->primeBuffers, hwParamsCapture, &realSr )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2643
Expression 'PaAlsaStream_Configure( stream, inputParameters, outputParameters, sampleRate, framesPerBuffer, &inputLatency, &outputLatency, &hostBufferSizeMode )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2767
Traceback (most recent call last):
  File "/home/pi/jasper/jasper.py", line 148, in <module>
    app.run()
  File "/home/pi/jasper/jasper.py", line 118, in run
    conversation.handleForever()
  File "/home/pi/jasper/client/conversation.py", line 31, in handleForever
    threshold, transcribed = self.mic.passiveListen(self.persona)
  File "/home/pi/jasper/client/mic.py", line 110, in passiveListen
    frames_per_buffer=CHUNK)
  File "/usr/lib/pymodules/python2.7/pyaudio.py", line 714, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/lib/pymodules/python2.7/pyaudio.py", line 396, in __init__
    self._stream = pa.open(**arguments)
IOError: [Errno Invalid sample rate] -9997

Do you have any ideas on how to fix this?

Thank you in advance,

DIego

**Comment by makeacoffeeprj** [comment]
Has anyone a suggestion to fix this issue? Sorry for bothering with the same question

**Comment by Holzhaus** [comment]
Please try again with the `jasper-dev` branch.
