### ISSUE TITLE
Crashing on launch

### ISSUE THREAD

**Issue by chandlerpl** [jasperproject/jasper-client#331]
Hi, I just setup Jasper on a RPi B and I got this error message: http://pastebin.com/z083syVJ

I ran jasper/jasper.py --debug and got this http://pastebin.com/v1dmDw3N

I think its a misconfigured audio file but Im not sure, any help would be appreciated.

[Edit]
I have also tried commenting out my gmail details and still get the same error.
Thanks in advance,
chandlerpl

**Comment by Laitala88** [comment]
234hg.446l zk 


Skickat från min Samsung-enhet

-------- Originalmeddelande --------
Från: chandlerpl <notifications@github.com> 
Datum: 15-05-2015  00:38  (GMT+01:00) 
Till: jasperproject/jasper-client <jasper-client@noreply.github.com> 
Rubrik: [jasper-client] Crashing on launch (#331) 

Hi, I just setup Jasper on a RPi B and I got this error message: http://pastebin.com/z083syVJ

I ran jasper/jasper.py --debug and got this http://pastebin.com/v1dmDw3N

I think its a misconfigured audio file but Im not sure, any help would be appreciated.

Thanks in advance,

chandlerpl
