### ISSUE TITLE
Jasper doesn't install on Yosemite

### ISSUE THREAD

**Issue by thsowers** [jasperproject/jasper-client#333]
Hey all. Following the thread here and everyones suggestions: https://github.com/jasperproject/jasper-client/issues/35
 
This project seems awesome and I would really love to help out...but..I've been trying for hours to get this to work -- no dice. Could we maybe get an updated tutorial? It's really difficult to attempt to follow a ton of various advice on a comment thread, and i'm worried that it isn't working because the steps are outdated for Yosemite.

Right now i'm stuck on trying to compile the phonetisarus libary, and it's a complete nightmare.:

g++ -O2 -I3rdparty/sparsehash -I3rdparty/utfcpp    -c Phonetisaurus.cpp -o Phonetisaurus.o
In file included from Phonetisaurus.cpp:39:
In file included from ./Phonetisaurus.hpp:36:
In file included from ./MBRDecoder.hpp:33:
3rdparty/sparsehash/google/dense_hash_map:106:10: fatal error: 'tr1/functional' file not found
#include HASH_FUN_H                  // defined in config.h
         ^
3rdparty/sparsehash/google/sparsehash/sparseconfig.h:10:20: note: expanded from macro 'HASH_FUN_H'
#define HASH_FUN_H <tr1/functional>
                   ^
1 error generated.
make: *** [Phonetisaurus.o] Error 1

**Comment by Holzhaus** [comment]
Please report the issue [over here](https://github.com/AdolfVonKleist/Phonetisaurus) and have a look at the [support forum](https://groups.google.com/forum/#!forum/jasper-support-forum).
