### ISSUE TITLE
No response from the system

### ISSUE THREAD

**Issue by NKPmedia** [jasperproject/jasper-client#334]
Hello I installed Jasper on my Pi B but I have a problem with the response!

I use the At&t STT because all other systems worked not so good. Or only work with 50 request per day. I change the name of Jasper to JESSICA because AT&T is not able to detect Jasper.

The system is able to hear me saying JESSICA and I hear the beep. But then the system always answers "Pardon?" whatever I say between the two beeps.

This is the log:
DEBUG:client.conversation:Stopped listening for keyword 'JESSICA'
INFO:client.conversation:Nothing has been said or transcribed.
DEBUG:client.conversation:Started listening for keyword 'JESSICA'
DEBUG:apscheduler.scheduler:Looking for jobs to run
WARNING:apscheduler.executors.default:Run time of job "Notifier.gather (trigger: interval[0:00:30], next run at: 2015-05-19 18:35:47 UTC)" was missed by 0:00:04.552925
DEBUG:apscheduler.scheduler:Next wakeup is due at 2015-05-19 18:36:17.750541+00:00 (in 25.451074 seconds)
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.att.com
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
DEBUG:requests.packages.urllib3.connectionpool:"POST /speech/v3/speechToText HTTP/1.1" 200 317
INFO:client.stt:Transcribed: [u'JESSICA']
DEBUG:client.conversation:Stopped listening for keyword 'JESSICA'
INFO:client.conversation:Keyword 'JESSICA' has been said!
DEBUG:client.conversation:Started to listen actively with threshold: 19.8
DEBUG:client.tts:Executing aplay -D hw:1,0 /home/pi/jasper/static/audio/beep_hi.wav
DEBUG:client.tts:Output was: 'Playing WAVE '/home/pi/jasper/static/audio/beep_hi.wav' : Signed 16 bit Little Endian, Rate 44100 Hz, Stereo
'
DEBUG:client.tts:Executing aplay -D hw:1,0 /home/pi/jasper/static/audio/beep_lo.wav
DEBUG:client.tts:Output was: 'Playing WAVE '/home/pi/jasper/static/audio/beep_lo.wav' : Signed 16 bit Little Endian, Rate 44100 Hz, Stereo
'
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.att.com
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
DEBUG:requests.packages.urllib3.connectionpool:"POST /speech/v3/speechToText HTTP/1.1" 200 161
DEBUG:client.stt:Recognition failed with status: Speech Not Recognized
DEBUG:client.conversation:Stopped to listen actively with threshold: 19.8
DEBUG:client.tts:Saying 'Pardon?' with 'espeak-tts'
DEBUG:client.tts:Executing espeak -v default+m3 -p 40 -s 160 -w /tmp/tmpfmB38t.wav 'Pardon?'
DEBUG:client.tts:Executing aplay -D hw:1,0 /tmp/tmpfmB38t.wav
DEBUG:client.tts:Output was: 'Playing WAVE '/tmp/tmpfmB38t.wav' : Signed 16 bit Little Endian, Rate 22050 Hz, Mono
'

Do you have any idea what is wrong...

Thank you for your help :D

**Comment by professorDODO** [comment]
How did you manage to get the beep response? I changed the name to Oracle and he recognize it INFO:client.stt:Transcribed: ['ORACLE'] but doesn't react to it. Where are the hard coded names you changed? I only found one in jasper.py line 117.

**Comment by NKPmedia** [comment]
Try to write the name in big letters. At the moment  I cant see my code because I am on my way to school but I think you have to do this...

I will take a look at my code later.

By the way on my Linux desktop I also get a response from the system. Its only a little bit slow. Streaming would be a solution or?

**Comment by professorDODO** [comment]
I wrote the name in capitals. I just wonder, that I found only one place
where it is hardcoded, instead of two like in the old version which is
described in the Jasper FAQs. When I got on your level of progress, I hope
I can help with yout response problem.

NKPmedia <notifications@github.com> schrieb am Mo., 8. Juni 2015 08:18:
