### ISSUE TITLE
New Volume / Audio Interface on Raspbian

### ISSUE THREAD

**Issue by makeacoffeeprj** [jasperproject/jasper-client#335]
Hi guys,

as the last release of Raspbian includes a new interface to handle audio devices, it is now not working the "arecord" recording test instruction of the "installation" section.

As anyone already tried a fresh installation of Jasper on clean installation of the latest Raspbian?

Thank you so much in advance,

Diego

**Comment by ledor473** [comment]
Which version of Raspian are you using? Could you paste the output of `cat /proc/version`

I had to add my user to the `audio` group  (and reboot) to make it work, something like:
```
usermod -a -G audio <username>
```

**Comment by makeacoffeeprj** [comment]
cat /proc/version
Linux version 3.18.11+ (dc4@dc4-XPS13-9333) (gcc version 4.8.3 20140303 (prerelease) (crosstool-NG linaro-1.13.1+bzr2650 - Linaro GCC 2014.03) ) #781 PREEMPT Tue Apr 21 18:02:18 BST 2015

I found out that Jasper is not working when the .asoundrc file is in the /home/ directory

**Comment by ledor473** [comment]
I'm currently running the same version as you. I had some issues to setup arecord, but it was a matter of permission.
Have you validate that your in the audio group as I said above?

**Comment by EMCP** [comment]
@ledor473 I tried your instructions , and rebooted.  Still not hearing anything.  This is on a brand new installation of raspbian on a Raspberry Pi 2

```
pi@raspberrypi2 ~ $ cat /proc/version
Linux version 3.18.11-v7+ (dc4@dc4-XPS13-9333) (gcc version 4.8.3 20140303 (prerelease) (crosstool-NG linaro-1.13.1+bzr2650 - Linaro GCC 2014.03) ) #781 SMP PREEMPT Tue Apr 21 18:07:59 BST 2015
```

**Comment by ledor473** [comment]
Could you show the output of the command `arecord temp.wav` (CTRL-C to stop the recording)
When it's done, are you able to play it with:
1. `aplay -D hw:1,0 temp.wav`
2. `aplay temp.wav`
3. With any music player that is working like VLC

To debug, would you also send the output of `arecord -l` and `aplay -l`
