### ISSUE TITLE
Jasper not listening

### ISSUE THREAD

**Issue by chandlerpl** [jasperproject/jasper-client#337]
I managed to get Jasper to work however when it is running is won't listen to me saying 'jasper' and won't say what it is supposed to at startup, I have tried 3 different headphones and 2 different mics and none of them are working.
I ran /jasper/jasper.py --debug http://pastebin.com/3C9HCBHc

Just found running jasper.py without debug has started giving this error message

pi@raspberrypi ~ $ /home/pi/jasper/jasper.py
*******************************************************
*             JASPER - THE TALKING COMPUTER           *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
ALSA lib pcm_direct.c:980:(snd1_pcm_direct_initialize_slave) unable to install hw params
ALSA lib pcm_dmix.c:1030:(snd_pcm_dmix_open) unable to initialize slave
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm_direct.c:980:(snd1_pcm_direct_initialize_slave) unable to install hw params
ALSA lib pcm_dmix.c:1030:(snd_pcm_dmix_open) unable to initialize slave
ALSA lib pcm_dmix.c:957:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
ALSA lib pcm_direct.c:980:(snd1_pcm_direct_initialize_slave) unable to install hw params
ALSA lib pcm_dmix.c:1030:(snd_pcm_dmix_open) unable to initialize slave
ERROR:apscheduler.executors.default:Job "Notifier.gather (trigger: interval[0:00:30], next run at: 2015-06-06 23:32:08 UTC)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/executors/base.py", line 108, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/pi/jasper/client/notifier.py", line 39, in gather
    [client.run() for client in self.notifiers]
  File "/home/pi/jasper/client/notifier.py", line 18, in run
    self.timestamp = self.gather(self.timestamp)
  File "/home/pi/jasper/client/notifier.py", line 43, in handleEmailNotifications
    emails = Gmail.fetchUnreadEmails(self.profile, since=lastDate)
  File "/home/pi/jasper/client/modules/Gmail.py", line 61, in fetchUnreadEmails
    conn = imaplib.IMAP4_SSL('imap.gmail.com')
  File "/usr/lib/python2.7/imaplib.py", line 1148, in __init__
    IMAP4.__init__(self, host, port)
  File "/usr/lib/python2.7/imaplib.py", line 163, in __init__
    self.open(host, port)
  File "/usr/lib/python2.7/imaplib.py", line 1159, in open
    self.sock = socket.create_connection((host, port))
  File "/usr/lib/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno -2] Name or service not known
WARNING:apscheduler.scheduler:Execution of job "Notifier.gather (trigger: interval[0:00:30], next run at: 2015-06-06 23:32:38 UTC)" skipped: maximum number of running instances reached (1)
WARNING:apscheduler.scheduler:Execution of job "Notifier.gather (trigger: interval[0:00:30], next run at: 2015-06-06 23:33:38 UTC)" skipped: maximum number of running instances reached (1)

**Comment by brad999** [comment]
There is a problem with the gmail notifications. Try removing your email address from profile.yml and see if that helps.

**Comment by chandlerpl** [comment]
Oh ok thanks, I haven't tested this yet because I have been busy Ill try later or tomorrow
