### ISSUE TITLE
Multi language support

### ISSUE THREAD

**Issue by sapier** [jasperproject/jasper-client#341]
It'd be good to have multi language support in jasper. It's not a big deal to change the tts engine to use a separate language. Right now I'm only failing to get jasper to use a different way to translate words to phonems. It's quite useless to try to talk e.g. in german to jasper expecting english pronounciation ;-)

**Comment by EMCP** [comment]
can you please direct me to non-english TTS engine options?

**Comment by Holzhaus** [comment]
Please have a look at PR #383. Feedback is always welcome.

**Comment by Holzhaus** [comment]
Multilanguage support has been merged into the `jasper-dev` branch.
