### ISSUE TITLE
How to implement PocketSphinx 5prealpha in Jasper

### ISSUE THREAD

**Issue by professorDODO** [jasperproject/jasper-client#343]
I installed PocketSphinx 5prealpha on Rpi 2 B hoping for a better speach recognition. But after starting Jasper I get this error:

```shell```
*******************************************************
*             JASPER - THE TALKING COMPUTER           *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
ERROR:root:Error occured!
Traceback (most recent call last):
  File "/home/pi/jasper/jasper.py", line 143, in <module>
    app = Jasper()
  File "/home/pi/jasper/jasper.py", line 106, in __init__
    stt_passive_engine_class.get_passive_instance(),
  File "/home/pi/jasper/client/stt.py", line 48, in get_passive_instance
    return cls.get_instance('keyword', phrases)
  File "/home/pi/jasper/client/stt.py", line 42, in get_instance
    instance = cls(**config)
  File "/home/pi/jasper/client/stt.py", line 126, in __init__
    **vocabulary.decoder_kwargs)
TypeError: __init__() got an unexpected keyword argument 'hmm'

**Comment by AndyMiao** [comment]
Hi I got the same error with you, and my jasper works good with google stt, but get this error with sphinx. did you figure that out?

**Comment by mbilker** [comment]
Jasper only supports PocketSphinx 0.8, but I think there is a fork working on implementing 5prealpha support.

**Comment by brad999** [comment]
@aish9r is your branch working with 5prealpha?

**Comment by mbilker** [comment]
@brad999 It works with 5prealpha. I am running @aish9r 's fork on Arch Linux with pocketsphinx 5prealpha-1 and phonetisaurus g014b2b.

**Comment by brad999** [comment]
Awesome, I will have to give it a try.

**Comment by G10DRAS** [comment]
Yes, Jasper works with PocketSphinx-5prealpha. I am using it for a while. 
check the below link for an installation
https://wolfpaulus.com/journal/embedded/raspberrypi2-sr/

**Comment by Holzhaus** [comment]
Pocketsphinx 5 prealpha support was added in commit f02a61e6c6b5853bcf232cc0c19879c9edd3fa3c. It currently resided in the experimental `jasper-dev` branch.

**Comment by Holzhaus** [comment]
Seems to be resolved.

**Comment by GeoBeBee** [comment]
Thanks, this finally got me on a solid track. 
I have documented my journey of required fixes here: 
[https://github.com/GeoBeBee/mySystem/blob/master/Jasper-dev_onPocketPhinx_5preAlpha.txt](https://github.com/GeoBeBee/mySystem/blob/master/Jasper-dev_onPocketPhinx_5preAlpha.txt)
