### ISSUE TITLE
Jasper Yosemite

### ISSUE THREAD

**Issue by HUGEwindow** [jasperproject/jasper-client#346]
Can Jasper work on Yosemite? Any clear instruction?

**Comment by Hadjimina** [comment]
What you could do is run Linux with Virtual Box. I'm currently running jasper on a standard arch install and it works beautifully.
You might have problem with the audio input and output but you should be able to manage it with some tweaking.

**Comment by Holzhaus** [comment]
Check out the [jasper-dev](https://github.com/jasperproject/jasper-client/tree/jasper-dev) branch. In theory, it should be possible to run this on any platform. If not, please post the full error message here (usign the `--debug` switch).
