### ISSUE TITLE
First Run Error

### ISSUE THREAD

**Issue by HUGEwindow** [jasperproject/jasper-client#347]
Using Quick Start installation with Pi I received this error:

File "/home/pi/jasper/jasper.py", line 11, in <module>
    from client import tts, stt, jaspepath, diagnose
File "/home/pi/jasper/client/tts.py", line 20, in <module>
    import requests
ImportError: No module named requests

Does anyone know what the issue may be? 

Thanks.

**Comment by Holzhaus** [comment]
You need to install `python-requests`.
