### ISSUE TITLE
IVONA TTS voices

### ISSUE THREAD

**Issue by hairychris** [jasperproject/jasper-client#348]
Hey,

It would require an internet connection but the IVONA voices available at http://www.ivona.com/ are also available via an API at https://www.ivona.com/us/for-business/speech-cloud/ 

Someone has even written a wrapper library (although it could do with a cleanup and getting rid of pygame) at http://zacharybears.com/pyvona/

I've been playing around with Google STT + Google Translate + IVONA multi-lingual voices and it's great. The Russian 'Maxim' voice is particularly good (so I'm told), much better than the Google voices. 

It might be worth looking at.

**Comment by Holzhaus** [comment]
Just had a look, but I need to wait until zbears/pyvona#9 has been merged to use this properly.
