### ISSUE TITLE
Could Japser work on OS X?

### ISSUE THREAD

**Issue by vicramon** [jasperproject/jasper-client#35]
I think it would be great if I could run Jasper on my Macbook. Would that be possible? I'm looking at [the documentation](http://jasperproject.github.io/documentation/software/) and it seems like it could work with some extra configuration, but I don't know enough about the internals to know how if it's possible.

**Comment by alzbookstore** [comment]
Just an FYI for new installers, the Homebrew link stated toward the top is old.
Here's the updated:

ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

**Comment by nyreed** [comment]
I actually got phonetisaurus to compile with liberal editing of compile flags in the makefile.
https://github.com/AdolfVonKleist/Phonetisaurus/issues/1#issuecomment-151455477

BUT I don't think this is what you want for jasper!
Compiling this project yielded two binaries 'phonetisaurus-align' and 'phonetisaurus-arpa2wfst-omega'
I think these are different components of the phonetisaurus project.

For Jasper, we need phonetisaurus-g2p, which is available from the [repo dump](https://www.dropbox.com/s/1bgavg07qx8fe5w/phonetisaurus-googlecode-archive.tgz?dl=0) at the closed [google code page](https://code.google.com/p/phonetisaurus/).

Within this archive is a folder 'g2p2rnn'
Again I edited the makefile to change std library and point to my openfst installation
```
-- CC=g++ -O2
++ CC=g++ -O2 -std=c++11
-- EXTRA= # Add extra here
++ EXTRA=-L/usr/local/Cellar/openfst/1.5.0/lib/ -I/usr/local/Cellar/openfst/1.5.0/include
```

then ran `sudo make` and it compiled to make 'phonetisaurus-g2p'

Please correct me if I'm wrong, I've not got Jasper running yet!

**Comment by Holzhaus** [comment]
@nitsujri First thing you could try is to choose another `stt_engine` in your `profile.yml` (e.g. `google`). You won't need `cmuclmtk`, `phonetisaurus`, `openfst`, `sphinxbase` or `pocketsphinx` in that case. If that works, you can look into trying to get pocketsphinx working - if not, please file bug reports, since the overall goal is to make jasper platform-independent.

**Comment by moochtm** [comment]
@nyreed 

Thanks for your Phonetisaurus pointer. I have Jasper running on Mac (El Capitan) now, and this was one of the last things I needed to sort out. I found that the Phonetisaurus version you pointed to was a different (I assume newer) version with different args. I changed g2p.py to check for which version was present and alter the args accordingly, and it's all up and running now.

**Comment by Shreyash23** [comment]
I need some help installing MITLM, could someone please help me? 

These are the steps I've done till now...
Add the Homebrew tap:

$ brew tap watsonbox/cmu-sphinx
You'll see some warnings as these formulae conflict with those in the main reponitory, but that's fine.

Install the libraries:

$ brew install --HEAD watsonbox/cmu-sphinx/cmu-sphinxbase
$ brew install --HEAD watsonbox/cmu-sphinx/cmu-sphinxtrain # optional
$ brew install --HEAD watsonbox/cmu-sphinx/cmu-pocketsphinx

openfst homebrew
cmuclmtk homebrew


GFortran -> https://gcc.gnu.org/wiki/GFortranBinaries#MacOS

**Comment by zoecarver** [comment]
I installed MITLM by changing line 325 in `src/NgramModel.cpp` like stated above and by running `sudo make install -stdlib=libstdc++` instead of `sudo make install`.

**Comment by zoecarver** [comment]
Got it working on my machine pretty well, if you have questions feel free to ask. 

### Edit
Tutorial here: https://github.com/pudility/jasper-osx
