### ISSUE TITLE
Can Jasper be used on the Raspberry Pi A+?

### ISSUE THREAD

**Issue by BruceJohnJennerLawso** [jasperproject/jasper-client#353]
I understand that installation images for the B+ are available, is it possible to install Jasper on the Raspberry Pi A+? In particular, how much memory will Jasper use in normal operation, given the A+ limit of 256 Mb?

**Comment by glop102** [comment]
I believe that with using the slimmer STT and TTS engines, it would be fine. The base chip is the same, just the stacked RAM is smaller. Also, the images probably would work fine. Try them out first and see.
