### ISSUE TITLE
Manual Installation of Jasper - ALSA Conf Issue

### ISSUE THREAD

**Issue by mike-n-ike** [jasperproject/jasper-client#354]
I decided to manually install jasper on my RPi 2 Model B. Thats only because i had trouble installing the pre-made jasper software on the card because most of the imaging programs were PC related, and i have a Mac. I've had no issue up until I had to begin editing the ALSA configuration for the microphone. I have the exact model microphone that was recommended by the creators. Once i get to the configuration using:

sudo vim /etc/modprobe.d/alsa-base.conf

This brings me to a page that i then have to find the following:

options snd-usb-audio index=-2

and edit it, and change it to:

options snd-usb-audio index=0

and I'm having trouble doing it. I was able to begin inserting characters and delete other characters. But was unable to save my edits. I figured out the way to exit the configuration was to Press the Colon : and then type "quit!" with the exclamation mark. so it would look something like so 

:quit!

But then as i continue in the instructions, it doesn't see the mic, as if its not there. So i go back to the configuration to see if the edit was saved, and it wasn't. 

Any thoughts?

**Comment by DieKatzchen** [comment]
Try using ee instead of vim.  I'm pretty sure it's installed by default in Raspian and it's a lot more user friendly.

**Comment by mike-n-ike** [comment]
I just gave it a shot now, but it isn't already installed on Raspian, its the latest copy and I've don't all the updates needed.

**Comment by Holzhaus** [comment]
Try `nano`.

**Comment by bryanbecker** [comment]
@mike-n-ike 

`:quit!` with the exclamation point means to discard changes
`:wq` (no need for an exclamation) means "write file, then quit"
