### ISSUE TITLE
Suggestion : Manually setting sphinx path to .lm and .dic file

### ISSUE THREAD

**Issue by Hadjimina** [jasperproject/jasper-client#359]
Heyo guys 

I have been playing around with jasper for the last couple of days now and ran into an issue where I did not want that Google could be listening in on me all the time. So i discovered the stt_passive_engine setting in the profile.yml. I installed everything that is need for sphinx to run (the pkgbuil of one of the aur dependencies is broken. You can find a link to the correct pkgbuild file in the most recent comment) but discovered soon that sphinx cant tell the difference from "James" to "Say" .( I renamed Jasper to James. The Documentation on the website wrong, one can change the name simply by changing the JASPER entry in jasper.py to anything you want)

What I then did was I used the sphinx lmtool to create file for my needs i.e. recognizing "JAMES". But I ran into a huge problem when trying to use my new .lm and .dic file with jasper. After a while I found the setting in vocacompiler.py where I have now hardcoded the return value of  "languagemodel_file" and "dictionary_file" to my path to the lm and dic file.

I suggest either writing about it in the documentation or add support for setting the lm and dic file in profile.yml

btw. Jasper is awesome !

EDIT:
P.S. if anyone is interested in a script that automatically updates the Google Api key as soon as the limit of calls per day is reached, simply contact me.

**Comment by Holzhaus** [comment]
Changing the name is now implement inside the `jasper-dev` branch, Closing this.

**Comment by kevinzzz007** [comment]
@Hadjimina could you let us know how you fixed your Jasper after updating the `.lm` and `.dic` files?  Is it the same problem as https://github.com/jasperproject/jasper-client/issues/569?

**Comment by Hadjimina** [comment]
Sorry @kevinzzz007  no idea how I managed it. As you can see the post is from 2015 and I haven't played around with it since. (Currentyl waiting for my Mycroft unit XD)
Good luck
