### ISSUE TITLE
Which microphone works across the room to do Voice Control?

### ISSUE THREAD

**Issue by confile** [jasperproject/jasper-client#360]
I want to place my raspberry running with jasper anywhere in my room and I will be able to control the raspberry from everywhere from this room.

Which microphone do you recommend, that work even across a room?

**Comment by nathanayling** [comment]
I use the Snowball, but both the Snowball & Yeti microphones work well. All i needed to do was to adjust the mic sensitivity in alsamixer and now it works across the room.

**Comment by glop102** [comment]
The noise floor for those mics are low enough to do that? Nice equipment there.....
(damn webcam mic...)

**Comment by confile** [comment]
Could you please post a link?

**Comment by nathanayling** [comment]
They are both quality budget microphones. The Yeti is a bit more pricey then the Snowball.

This is the Yeti one http://amzn.to/1IOzyNH and the one I use is the Snowball http://amzn.to/1UFGhkp

**Comment by confile** [comment]
They are quite expensive. Are there any cheaper once that work well too? What should I take care about when buying a mic?
