### ISSUE TITLE
libportaudio-dev in Jessie

### ISSUE THREAD

**Issue by dennisjanssen** [jasperproject/jasper-client#363]
First of all: I'm not very experienced in Linux.
Now, when installing Jasper on Ubuntu, most of it went flawless, it was working beautifully!

Next step was getting it to work on my Raspberry Pi, which has OSMC on it (which rests on Debian for all I know), but for some reason it's not installing libportaudio-dev. After researching I found out it doesn't seem to be in Debian Jessie. https://packages.debian.org/search?suite=default&section=all&arch=any&searchon=names&keywords=libportaudio-dev

Now I'm a bit clueless. Will another package do as well? Or is there another way to get this installed?
Also: sorry I filed this as an issue, might not be one at all.

**Comment by glop102** [comment]
I am having trouble determining what OSMC is based on. Truthfully this topic should be taken up with the os specific forums as they are going to be the package maintainers that have libportaudio-dev.

What package manager does it use? Does it even have one? You say the rest went well, so i am assuming you have apt-get.

Using a debian based system with apt on it, you can do **apt-cache search libportaudio** and see what comes up. Tell me if you need some more tricks to search

**Comment by dennisjanssen** [comment]
That command returns me these packages: 
libportaudio-ocaml - OCaml bindings for the portaudio library
libportaudio-ocaml-dev - OCaml bindings for the portaudio library
libportaudio2 - Portable audio I/O - shared library
libportaudiocpp0 - Portable audio I/O C++ bindings - shared library

Would any of those work as well? Or do I just install them all and see what happens down the line?

**Comment by glop102** [comment]
I am setting up a VM with jessie. There is ussually a python bindings file.

The OCaml stuff is for a different language. Try the libportaudio2, though i think that is only the binaries, not the python dev stuff.

Ill get back in a few minutes.

**Comment by glop102** [comment]
Sorry for the late reply, but apparently the solution was simple. The **python-pyaudio** is probably the only package you need. I cant find anything else. Try just continuing as if nothing else has changed and see if it bites you later. I am trying to get it to work on the VM now, I over estimated how much free time i have tonight.

**Comment by glop102** [comment]
I have completed the install on a VM and it seems to work fine with not explicitly installing libportaudio and just the **python-pysudio** stuff.

Also, another pitfall i ran across was an outdated PIP version. You should use **easy_install pip** to get the latest version.

**Comment by dennisjanssen** [comment]
You were very right, I could continue perfectly without it. I did get stuck a little further down the line, but I'm pretty sure it's unrelated. Thanks for your help, it's greatly appreciated!
