### ISSUE TITLE
jasper crashes on RPI 2 Model B with sphinxbase-5prealpha

### ISSUE THREAD

**Issue by Shibonja** [jasperproject/jasper-client#364]
Hi guys, you made a nice job developing jasper. 
I tried to install it on my RPI 2 following your steps on the installation page. I am running (trying to run) jasper on Raspbian (Debian Wheezy, Release date:2015-05-05, Kernel version:3.18) and after the first attempt I got jasper running, but barely recognizing any word. I am using a USB Microphone as input, so I checked my microphone with arecord and noticed the a big SNR, so the sound I recorded had a big noise. In order to find out whats wrong with my sound input I burned a clean image on RPi and recorded again my voice. The new recorded sound was clean and with barely noise. So i started my jasper installation for the second time and recorded and checked the sound after every step. I came to the conclusion that after installing sphinxbase my sound gone wrong. So I started again form a new Image but this time i installed sphinxbase-5prealpha and pocketsphinx-5prealpha from this tutorial https://wolfpaulus.com/jounal/embedded/raspberrypi2-sr/ and after this i continued woth the normal installation procedure again checking the spund after ever step. This time the sound doesnt got messed but I could not start jasper with this error:
```shell
pi@raspberrypi ~/jasper $ python jasper.py 
*******************************************************
*             JASPER - THE TALKING COMPUTER           *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
WARNING:root:tts_engine not specified in profile, defaulting to 'espeak-tts'
ERROR:root:Error occured!
Traceback (most recent call last):
  File "jasper.py", line 143, in <module>
    app = Jasper()
  File "jasper.py", line 106, in __init__
    stt_passive_engine_class.get_passive_instance(),
  File "/home/pi/jasper/client/stt.py", line 48, in get_passive_instance
    return cls.get_instance('keyword', phrases)
  File "/home/pi/jasper/client/stt.py", line 34, in get_instance
    config = cls.get_config()
  File "/home/pi/jasper/client/stt.py", line 143, in get_config
    config['hmm_dir'] = profile['pocketsphinx']['hmm_dir']
TypeError: 'NoneType' object has no attribute '__getitem__'
```

I am not a newbie to RPi, so can anyone point me in the right direction to solve this problem???

Best regards, Haris.

**Comment by Holzhaus** [comment]
Looks like your `profile.yml` is missing some values. Have a look at the configuration section in the documentation.

**Comment by Shibonja** [comment]
Here is my profile.yml
pi@raspberrypi ~/.jasper $ cat profile.yml 
carrier: ''
first_name: Haris
gmail_password: ''
last_name: Sibonjic
phone_number: ''
prefers_email: false
stt_engine: sphinx

with the error in the previous comment. When adding manually path to pocketsphinx like this:

pi@raspberrypi ~/.jasper $ cat profile.yml 
carrier: ''
first_name: Haris
gmail_password: ''
last_name: Sibonjic
phone_number: ''
prefers_email: false
stt_engine: sphinx
pocketsphinx:
  fst_model: '../phonetisaurus/g014b2b.fst'                            
  hmm_dir: '/usr/local/share/pocketsphinx/model/hmm/en_US/hub4wsj_sc_8k' 

I am getting again the same error

pi@raspberrypi ~/jasper $  python jasper.py --debug
*******************************************************
*             JASPER - THE TALKING COMPUTER           *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
DEBUG:client.diagnose:Checking network connection to server 'www.google.com'...
DEBUG:client.diagnose:Network connection working
DEBUG:__main__:Trying to read config file: '/home/pi/.jasper/profile.yml'
DEBUG:client.diagnose:Checking python import 'pocketsphinx'...
DEBUG:client.diagnose:Python package 'pocketsphinx' found: '/usr/local/lib/python2.7/dist-packages/pocketsphinx/__init__.py'
WARNING:root:tts_engine not specified in profile, defaulting to 'espeak-tts'
DEBUG:client.diagnose:Checking executable 'aplay'...
DEBUG:client.diagnose:Executable 'aplay' found: '/usr/bin/aplay'
DEBUG:client.diagnose:Checking executable 'espeak'...
DEBUG:client.diagnose:Executable 'espeak' found: '/usr/bin/espeak'
DEBUG:client.vocabcompiler:compiled_revision is 'bb74ae36d130ef20de710e3a77b43424b8fa774f'
ERROR:root:Error occured!
Traceback (most recent call last):
  File "jasper.py", line 143, in <module>
    app = Jasper()
  File "jasper.py", line 106, in __init__
    stt_passive_engine_class.get_passive_instance(),
  File "/home/pi/jasper/client/stt.py", line 48, in get_passive_instance
    return cls.get_instance('keyword', phrases)
  File "/home/pi/jasper/client/stt.py", line 42, in get_instance
    instance = cls(**config)
  File "/home/pi/jasper/client/stt.py", line 126, in __init__
    **vocabulary.decoder_kwargs)
TypeError: __init__() got an unexpected keyword argument 'hmm'

**Comment by Shibonja** [comment]
I finally got jasper running with pocketsphinx-5prealpha with changes form this link:

https://groups.google.com/forum/#!topicsearchin/jasper-support-forum/5prealpha/jasper-support-forum/VTod74fdzSM

but now jasper is not able to recognize any word.

**Comment by G10DRAS** [comment]
The tutorial you mentioned above https://wolfpaulus.com/jounal/embedded/raspberrypi2-sr/  , was it works for you ? 
if aplay ./test.wav works then try changing below jasper code and see if jasper will work for you...

client/tts.py:        # cmd = ['aplay', '-D', 'plughw:1,0', str(filename)]
client/tts.py:        cmd = ['aplay', str(filename)]

else remove pulseraudio and try re-installing pyaudio and try again....
