### ISSUE TITLE
phonetisaurus-g2p: symbol lookup error

### ISSUE THREAD

**Issue by dedenker** [jasperproject/jasper-client#367]
Using Ubuntu 14.04 x386.
Try to follow the installation document, but not all links are working like for phonetisaurus.
But I managed to get the archived tarball.

But now when run jasper.py something goes wrong at this point:
phonetisaurus-g2p --model=/home/{user}/phonetisaurus/g014b2b.fst --input=/tmp/tmpv6cmgH.g2p --words --isfile
with the error message: phonetisaurus-g2p: symbol lookup error: phonetisaurus-g2p: undefined symbol: _ZN3fst22ShortestPathPropertiesEy

Here the full debug:
DEBUG:client.diagnose:Executable 'phonetisaurus-g2p' found: '/usr/bin/phonetisaurus-g2p'
DEBUG:client.g2p:Using FST model: '/home/{user}/phonetisaurus/g014b2b.fst'
DEBUG:client.g2p:Converting 18 words to phonemes
DEBUG:client.g2p:phonetisaurus-g2p: symbol lookup error: phonetisaurus-g2p: undefined symbol: _ZN3fst22ShortestPathPropertiesEy
ERROR:client.g2p:Command 'phonetisaurus-g2p --model=/home/{user}/phonetisaurus/g014b2b.fst --input=/tmp/tmp_xoGmT.g2p --words --isfile' return with exit status 127
ERROR:client.vocabcompiler:Fatal compilation Error occured, cleaning up...
Traceback (most recent call last):
  File "/home/{user}/jasper/client/vocabcompiler.py", line 163, in compile
    self._compile_vocabulary(phrases)
  File "/home/{user}/jasper/client/vocabcompiler.py", line 271, in _compile_vocabulary
    self._compile_dictionary(vocabulary, self.dictionary_file)
  File "/home/{user}/jasper/client/vocabcompiler.py", line 321, in _compile_dictionary
    phonemes = g2pconverter.translate(words)
  File "/home/{user}/jasper/client/g2p.py", line 130, in translate
    output = self._translate_words(words)
  File "/home/{user}/jasper/client/g2p.py", line 119, in _translate_words
    nbest=self.nbest)
  File "/home/{user}/jasper/client/g2p.py", line 56, in execute
    raise OSError("Command execution failed")
OSError: Command execution failed
ERROR:root:Error occured!
Traceback (most recent call last):
  File "jasper.py", line 143, in <module>
    app = Jasper()
  File "jasper.py", line 106, in __init__
    stt_passive_engine_class.get_passive_instance(),
  File "/home/{user}/jasper/client/stt.py", line 48, in get_passive_instance
    return cls.get_instance('keyword', phrases)
  File "/home/{user}/jasper/client/stt.py", line 40, in get_instance
    vocabulary.compile(phrases)
  File "/home/{user}/jasper/client/vocabcompiler.py", line 171, in compile
    raise e
OSError: Command execution failed
{user}@joey:~/jasper$ phonetisaurus-g2p --model=/home/{user}/phonetisaurus/g014b2b.fst --input=/tmp/tmpv6cmgH.g2p --words --isfile
phonetisaurus-g2p: symbol lookup error: phonetisaurus-g2p: undefined symbol: _ZN3fst22ShortestPathPropertiesEy

Is there a python version I have keep in mind? I use python 2 and 3...

**Comment by Holzhaus** [comment]
You should recompile Phonetisaurus and/or the openfst lib. I guess something went wrong during that step.

**Comment by Jearde** [comment]
dedenker, have you figured out, how to solve the error?

**Comment by dedenker** [comment]
I did have it compiled, but not yet a clear answer.
But I did a lot of things (adding lib's and changing environmental
settings) at the same time (I did wrote it all down).
So I wanted to go over it to see what are the steps again/precisely.

I give it some time and post the exact steps.
Sorry for no coming back on this.

2016-01-06 23:02 GMT+01:00 Jearde <notifications@github.com>:

> dedenker, have you figured out, how to solve the error?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jasperproject/jasper-client/issues/367#issuecomment-169476539>
> .
>



-- 
Imagination is more important than knowledge.
Knowledge is limited.
Imagination encircles the world.
-Albert Einstein-

**Comment by Jearde** [comment]
Would be great if you could do that. I did all the steps again on an new os and i also got:
*******************************************************
*             JASPER - THE TALKING COMPUTER           *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
ERROR:client.g2p:Command 'phonetisaurus-g2p --model=/home/ubuntu/phonetisaurus/g014b2b.fst --input=/tmp/tmpW5Cyy4.g2p --words --isfile' return with exit status -11
ERROR:client.vocabcompiler:Fatal compilation Error occured, cleaning up...
Traceback (most recent call last):
  File "/home/ubuntu/jasper/client/vocabcompiler.py", line 163, in compile
    self._compile_vocabulary(phrases)
  File "/home/ubuntu/jasper/client/vocabcompiler.py", line 271, in _compile_vocabulary
    self._compile_dictionary(vocabulary, self.dictionary_file)
  File "/home/ubuntu/jasper/client/vocabcompiler.py", line 321, in _compile_dictionary
    phonemes = g2pconverter.translate(words)
  File "/home/ubuntu/jasper/client/g2p.py", line 130, in translate
    output = self._translate_words(words)
  File "/home/ubuntu/jasper/client/g2p.py", line 119, in _translate_words
    nbest=self.nbest)
  File "/home/ubuntu/jasper/client/g2p.py", line 56, in execute
    raise OSError("Command execution failed")
OSError: Command execution failed
ERROR:root:Error occured!
Traceback (most recent call last):
  File "jasper.py", line 143, in <module>
    app = Jasper()
  File "jasper.py", line 106, in __init__
    stt_passive_engine_class.get_passive_instance(),
  File "/home/ubuntu/jasper/client/stt.py", line 48, in get_passive_instance
    return cls.get_instance('keyword', phrases)
  File "/home/ubuntu/jasper/client/stt.py", line 40, in get_instance
    vocabulary.compile(phrases)
  File "/home/ubuntu/jasper/client/vocabcompiler.py", line 171, in compile
    raise e
OSError: Command execution failed

**Comment by dedenker** [comment]
Hi,

I did not yet had the change to setup a clean machine and go over my steps.
However I did go over the software repositories I used.
Also looking at your error message and trying the command:
*phonetisaurus-g2p --model=/home/ubuntu/phonetisaurus/g014b2b.fst
--input=/tmp/tmpW5Cyy4.g2p --words --isfile*
And also on my machine this does give an error (segmentation fault).
Please take a look at this file
  phonetisaurus-googlecode-archive.tgz
<https://drive.google.com/file/d/0BxOpXUa3dSyoLTFSWTZwTEU4NjA/view?usp=drivesdk>
, I believe it holds the file(s) you need without compiling.

But which ubuntu are you using?
I still try to get working on the steps when I find the time.

Would be great if you could do that. I did all the steps again on an new os
and i also got:
------------------------------

   - JASPER - THE TALKING COMPUTER *
   - (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
   *******************************************************
   ERROR:client.g2p:Command 'phonetisaurus-g2p
   --model=/home/ubuntu/phonetisaurus/g014b2b.fst --input=/tmp/tmpW5Cyy4.g2p
   --words --isfile' return with exit status -11
   ERROR:client.vocabcompiler:Fatal compilation Error occured, cleaning up...
   Traceback (most recent call last): File
   "/home/ubuntu/jasper/client/vocabcompiler.py", line 163, in compile
self.*compile_vocabulary(phrases)
   File "/home/ubuntu/jasper/client/vocabcompiler.py", line 271, in
   compile_vocabulary self._compile_dictionary(vocabulary,
   self.dictionary_file) File "/home/ubuntu/jasper/client/vocabcompiler.py",
   line 321, in _compile_dictionary phonemes = g2pconverter.translate(words)
   File "/home/ubuntu/jasper/client/g2p.py", line 130, in translate output =
   self._translate_words(words) File "/home/ubuntu/jasper/client/g2p.py", line
   119, in _translate_words nbest=self.nbest) File
   "/home/ubuntu/jasper/client/g2p.py", line 56, in execute raise
   OSError("Command execution failed") OSError: Command execution failed
   ERROR:root:Error occured! Traceback (most recent call last): File
   "jasper.py", line 143, in app = Jasper() File "jasper.py", line 106, in
   __init* stt_passive_engine_class.get_passive_instance(), File
   "/home/ubuntu/jasper/client/stt.py", line 48, in get_passive_instance
   return cls.get_instance('keyword', phrases) File
   "/home/ubuntu/jasper/client/stt.py", line 40, in get_instance
   vocabulary.compile(phrases) File
   "/home/ubuntu/jasper/client/vocabcompiler.py", line 171, in compile raise e
   OSError: Command execution failed

—
Reply to this email directly or view it on GitHub
<https://github.com/jasperproject/jasper-client/issues/367#issuecomment-170391976>
.

**Comment by Jearde** [comment]
I use Ubuntu 14.04 LTS with the image installation from here: https://wiki.ubuntu.com/ARM/RaspberryPi
I solved the error. After reinstalling some libs like opengrm-ngram (not sure if necessary), m2m-aligner, mitlm, is2013-conversion(phonetisaurus), i didn't get the error. I think that were the programs. I'm trying to make a own step by step guide. Here are some steps I did. The whole file is not ready and I still have one problem. When I start Jasper, he doesn't make a sound. Mic and VLC are working. I tried with the media player.
I still get some errors like : 
ALSA lib confmisc.c:1286:(snd_func_refer) Unable to find definition 'cards.bcm2835.pcm.front.0:CARD=0'
# Here are some steps which could be helpful with the libs:
...
uncomment if you don't have a swap file with >= 500MB
#sudo su
#echo "CONF_SWAPSIZE=512" > /etc/dphys-swapfile
#dphys-swapfile setup
#dphys-swapfile swapon
#reboot

cd
wget http://www.openfst.org/twiki/pub/FST/FstDownload/openfst-1.5.0.tar.gz
wget https://mitlm.googlecode.com/files/mitlm-0.4.1.tar.gz
wget https://m2m-aligner.googlecode.com/files/m2m-aligner-1.2.tar.gz
http://www.openfst.org/twiki/pub/GRM/NGramDownload/opengrm-ngram-1.2.1.tar.gz
wget https://phonetisaurus.googlecode.com/files/is2013-conversion.tgz
#wget https://www.dropbox.com/s/154q9yt3xenj2gr/phonetisaurus-0.8a.tgz
wget https://www.dropbox.com/s/kfht75czdwucni1/g014b2b.tgz?dl=0
tar -xvf openfst-1.5.0.tar.gz
tar -xvf m2m-aligner-1.2.tar.gz
tar -xvf mitlm-0.4.1.tar.gz
tar -xvzf opengrm-ngram-1.2.1.tar.gz
tar -xvf is2013-conversion.tgz
#tar -xvf phonetisaurus-0.8a.tgz
tar -xvf g014b2b.tgz
cd
cd openfst-1.5.0/
sudo ./configure --enable-compact-fsts --enable-const-fsts --enable-far --enable-lookahead-fsts --enable-pdt
sudo make install
cd
cd opengrm-ngram-1.2.1/
./configure
make
sudo make install
cd
cd m2m-aligner-1.2/
sudo make
cd
cd mitlm-0.4.1/
sudo ./configure
sudo make install
cd
cd is2013-conversion/phonetisaurus/src
#cd ~/phonetisaurus-0.8a/phonetisaurus/src
sudo make CFLAGS+=-std=gnu++11
sudo cp ~/m2m-aligner-1.2/m2m-aligner /usr/local/bin/m2m-aligner
sudo cp ~/is2013-conversion/bin/phonetisaurus-g2p /usr/local/bin/phonetisaurus-g2p
#sudo cp ~/phonetisaurus-0.8a/bin/phonetisaurus-g2p /usr/local/bin/phonetisaurus-g2p
cd
cd g014b2b/
./compile-fst.sh
mv ~/g014b2b ~/phonetisaurus
sudo reboo
....

**Comment by Jearde** [comment]
Jasper works now! The no audio bug  I have was, that jasper wants to have your output card on index 1 not 0. What I did:
aplay -l
lsmod | grep snd
sudo nano /etc/modprobe.d/alsa-base.conf
edit
options snd-usb-audio index=0
add after snd-usb-audio
options snd_bcm2835 index=1
sudo nano /etc/modules
add
#snd-bcm2835
snd-usb-audio
test
speaker-test -c2 -D hw:1,0
