### ISSUE TITLE
In mic.py no play() function is available to play wav file in Jasper Modules.

### ISSUE THREAD

**Issue by G10DRAS** [jasperproject/jasper-client#376]
In mic.py no play() function is available to play wav file in Jasper Modules.
I want to play some wav files from my custom jasper modules but no function available as of now.
mic.say() is there but no mic.play().

**Comment by Holzhaus** [comment]
Check out the [jasper-dev](https://github.com/jasperproject/jasper-client/tree/jasper-dev) branch, which has such a function: https://github.com/jasperproject/jasper-client/blob/jasper-dev/client/mic.py#L152

That branch also reimplements most of the audio io stuff and might be a better choice anyway. Keep in mind that that branch will introduce some big changes, so an update might break your modules.

**Comment by G10DRAS** [comment]
Thanks, got it. Closing the issue.
