### ISSUE TITLE
Can we provide custom wav file for voice recognition in jasper?

### ISSUE THREAD

**Issue by ashubhatt** [jasperproject/jasper-client#386]
Hey Guys, I know that Jasper is always listening for audio commands from mic. But is it possible to write a script such that a custom audio (.wav) file can be provided as input to Jasper for voice recognition?

If yes, can somebody post a method explaining the same.

Thank you.

**Comment by Holzhaus** [comment]
Not possible yet. What's the use case? If you just want to transcribe an audio file, you could use pocketsphinx/sphinx/etc. directly.
