### ISSUE TITLE
Any plan to support latest cmusphinx en_us G2P Model (FST) ?

### ISSUE THREAD

**Issue by G10DRAS** [jasperproject/jasper-client#392]
http://sourceforge.net/projects/cmusphinx/files/G2P%20Models/en_us_nostress.tar.gz/download

Any plan to support the latest cmusphinx en_us G2P Model (cmudict-5prealpha.fst) in Jasper v2.
It works with lower case Words, hence need code changes in g2p.py.

**Comment by Holzhaus** [comment]
Currently, it looks like Phonetisaurus can't handle this model (causes a hang on my PC). I'll look into it.

**Comment by G10DRAS** [comment]
This FST handles lowercase WORDS, hence --input file nees to contain 'lowercase' words only....

pi@RaspBerryPi2 ~/jasper $ cat /tmp/tmpN7TxTy.g2p
automation
barzellette
bazar
birthday
compleanno
convert
currency
data
date

pi@RaspBerryPi2 ~/jasper $ phonetisaurus-g2p --model=/home/pi/g014b2b/cmudict-5prealpha.fst --input=/tmp/tmpN7TxTy.g2p --words --isfile --nbest=1
automation      13.166  AO T AH M EY SH AH N
barzellette     25.2822 B AA R Z IH L EH T
bazar   13.4238 B AH Z AA R
birthday        12.291  B ER TH D EY
cam     11.3662 K AE M
compleanno      22.9033 K AH M P L IY AE N OW
convert 11.9609 K AA N V ER T
currency        11.3604 K ER AH N S IY
data    11.5791 D EY T AH
date    11.0557 D EY T
definition      12.6748 D EH F AH N IH SH AH N
dictionary      15.4062 D IH K SH AH N EH R IY
echo    11.625  EH K OW
email   12.7998 IY M EY L
exchange        11.6836 IH K S CH EY N JH
facebook        19.5127 F EY S B UH K
forecast        11.6172 F AO R K AE S T
fram    11.2393 F R AE M
gmail   20.0029 G M EY L
hacker  11.3125 HH AE K ER
home    10.0234 HH OW M
imdb    25.9795 IH M D B
inbox   15.9727 IH N B AA K S
joke    12.3184 JH OW K
knock   11.1875 N AA K
life    10.2295 L AY F

**Comment by Holzhaus** [comment]
Yes, but `phonetisaurus-g2p` will hang forever if that word is not found:

```
$ phonetisaurus-g2p --model=/home/jan/Downloads/en_us_nostress/model.fst --input=HELLO
Symbol: 'H' not found in input symbols table.
Mapping to null...
Symbol: 'E' not found in input symbols table.
Mapping to null...
Symbol: 'L' not found in input symbols table.
Mapping to null...
Symbol: 'L' not found in input symbols table.
Mapping to null...
Symbol: 'O' not found in input symbols table.
Mapping to null...

```

The  process won't return at that point and run forever, so I'll have to implement a way to detect that and kill it first.

**Comment by Holzhaus** [comment]
I fixed the issue in 0ef2b3393c0bad2077bbc6c62f048b815da7fcc9. Can you test and report back if that worked for you?

**Comment by G10DRAS** [comment]
Ok I will check it on Monday.

Mean time I did changes in my jasper-client master code.(g2p.py), take a look ...
https://github.com/G10DRAS/jasper-client/commit/4d5cdd98becfb727d6c1058da570e5e732eb68bb

I have added one config option "fst_type"  in profile.yml . Where 
fst_type: 'phonetisaurus'  # if you are using cmudict-5prealpha.fst with Jasper
fst_type: 'openfst'             # default or if you are using existing FST with Jasper

Sample Profile.yml

    stt_engine: sphinx
    stt_passive_engine: sphinx
    pocketsphinx:
      # Latest FST model from cmusphinx
      # http://sourceforge.net/projects/cmusphinx/files/G2P%20Models/en_us_nostress.tar.gz/download 
      fst_model: '/home/pi/g014b2b/cmudict-5prealpha.fst'             
      fst_type: 'phonetisaurus'  # specify it if using cmudict-5prealpha.fst
      # fst_model: '/home/pi/g014b2b/g014b2b.fst'     
      # fst_type: 'openfst'    # default or existing g014b2b FST
      hmm_dir: '/usr/local/share/pocketsphinx/model/en-us/en-us'           
      nbest: '1'

I did testing with all possible cases using both FSTs. Both works without any hang issue. 

    WORDS = ["AUTOMATION"]
    WORDS = ["automation"]
    WORDS = ["Automation"]
    WORDS = ["AutoMATION"]

Lets see if this code can be merge with jasper-dev

**Comment by Holzhaus** [comment]
@G10DRAS Commit 0ef2b3393c0bad2077bbc6c62f048b815da7fcc9 should fix the issue without the need to add more config options. It attempts to do g2p conversion with uppercase words first, then checks if any `Symbol: 'X' not found in input symbols table.` are written to `stderr`. If that's the case, it kills the process and retries with lowercase words.

**Comment by Holzhaus** [comment]
Can you confirm this works?

**Comment by G10DRAS** [comment]
1. Ok it works well if current FST model (g014b2b.fst) is used with Jasper. 
2. But with new FST model (cmudict-5prealpha.fst), Jasper kills phonetisaurus-g2p, every time a new dictionary generated. (at least 2 times)
3. My Jasper generating 7 dictionaries and hence phonetisaurus-g2p killed 7 times, not looks good.
4. Take cases below ( I just changed WORDS in one Jasper Module as below, all other Module having WORDS in UPPER case)

    a. WORDS = ["AUTOMATION"] ---- Works well !!!

    b. WORDS = ["automation"] ----- Jasper Crashed...........
    c. WORDS = ["Automation"] ----- Jasper Crashed........... 
    d. WORDS = ["AutoMATION"] ----- Jasper Crashed...........
    Need to change below code in sphinxvocab.py (line 120)

     # phonemes = g2pconverter.translate(words)
     phonemes = g2pconverter.translate([word.upper() for word in words]) 

5. If we consider above cases b, c and d then we need changes for Language Model compilation
    
    def _compile_vocabulary(self, phrases):
          # text = " ".join([("<s> %s </s>" % phrase) for phrase in phrases])
           text = " ".join([("<s> %s </s>" % phrase.upper()) for phrase in phrases])

**Comment by Holzhaus** [comment]
The change in 4 shouldn't be neccessary when we convert all phrases to uppercase like you proposed in number 5.  I'll upload a fix.

**Comment by G10DRAS** [comment]
Change in 5 is for language model.
Change in 4 required for dictionary

Need to change below code in sphinxvocab.py (line 120)
    
     # phonemes = g2pconverter.translate(words)
     phonemes = g2pconverter.translate([word.upper() for word in words])

**Comment by Holzhaus** [comment]
[Relevant code:](https://github.com/jasperproject/jasper-client/blob/d7840e8be20d7aac8239cc4aded42a81590d0966/plugins/stt/pocketsphinx-stt/sphinxvocab.py#L62-L70)

```python
text = " ".join([("<s> %s </s>" % phrase.upper()) for phrase in phrases])
# [...]
vocabulary = compile_languagemodel(text, languagemodel_path)
# [...]
compile_dictionary(g2pconverter, vocabulary, dictionary_path)
```

The phrases (uppercase) are passed into `compile_languagemode()`, This function will split them into individual words and return them, so they should still be uppercase. They are then passed into the `compile_dictionary()` function. So I don't think we need to call `str,upper()` again.

**Comment by G10DRAS** [comment]
my fault, lately I was doing function testing of _compile_dictionary().

Another thought about new FST Model (cmudict-5prealpha.fst). 
It is possible to compile cmudict-5prealpha.dict in to cmudict-5prealpha.fst, in such a way that it will support UPPER case isyms. But in this case we have to maintain compiled FST either on GitHub Jasper repository or somewhere else. That the overhead of maintaining an external file. 
Not a good idea.... Discard.....

**Comment by Holzhaus** [comment]
> It is possible to compile cmudict-5prealpha.dict in to cmudict-5prealpha.fst, in such a way that it will support UPPER case isyms. But in this case we have to maintain compiled FST either on GitHub Jasper repository or somewhere else. That the overhead of maintaining an external file.  Not a good idea.... Discard.....

Since it's possible to specify your own fst model, you can do that. But I don't think that'd fit into the scope of jasper ;-)

Anyhow, I'll close this since that issue seems to be fixed.
