### ISSUE TITLE
Prevent wear on sd-card

### ISSUE THREAD

**Issue by redfast00** [jasperproject/jasper-client#396]
At https://github.com/jasperproject/jasper-client/blob/master/client/mic.py#L170 , Jasper opens a temp file. If you write a lot of temp files, the sd-card will eventually break. Would it be possible to make a RAM-disk for Jasper's recorded files? You can set the location of the temp files in Python. https://docs.python.org/2/library/tempfile.html#tempfile.tempdir 

Thanks!

**Comment by Holzhaus** [comment]
Tempfiles will go into `/tmp`, which is often a `tmpfs`file system.
