### ISSUE TITLE
[bug?] Mic#fetchThreshold poorly designed

### ISSUE THREAD

**Issue by skeggse** [jasperproject/jasper-client#397]
The [`Mic#fetchThreshold`](https://github.com/jasperproject/jasper-client/blob/c38256b4418aab9fa359ce257b1b99497e422c05/client/mic.py#L47) method, as I understand it, is supposed to sample the microphone for a second and determine the loudness threshold for identifying speech. This process uses two lists - `frames` and `lastN`. These lists don't seem to serve any real purpose.

Data is added to `frames`, but frames is just garbage collected.

The `lastN` list (which could be replaced with the more efficient [deque](https://docs.python.org/2/library/collections.html#collections.deque)), is continually mutated and used to calculate the `average` variable, but only the last calculate of `average` is used, making the whole process inefficient and seemingly incorrect, as it only accounts for the last 20 samples.

How is the `average` supposed to be calculated? What is the purpose of `lastN`, and why is `20` significant?

In effect, the entire `fetchThreshold` function can be reduced to:

```py
def fetchThreshold(self):
  RATE = 16000
  CHUNK = 1024
  THRESHOLD_MULTIPLIER = 1.8
  THRESHOLD_RELEVANT = 20
  THRESHOLD_TIME = 1

  stream = self._audio.open(format=pyaudio.paInt16, channels=1, rate=RATE, input=True, frames_per_buffer=CHUNK)

  for i in xrange(THRESHOLD_TIME * RATE / CHUNK - THRESHOLD_RELEVANT):
    stream.read(CHUNK) # why?

  lastN = [self.getScore(stream.read(chunk)) for i in xrange(THRESHOLD_RELEVANT)]

  stream.stop_stream()
  stream.close()

  return THRESHOLD_MULTIPLIER * sum(lastN) / THRESHOLD_RELEVANT
```

(also, shouldn't `stream.start_stream` be called?)

**Comment by Holzhaus** [comment]
Check out the `jasper-dev` branch: https://github.com/jasperproject/jasper-client/blob/jasper-dev/client/mic.py#L39
