### ISSUE TITLE
Crackling audio playback with PyAudio in jasper-dev.

### ISSUE THREAD

**Issue by G10DRAS** [jasperproject/jasper-client#404]
Though it is not a Jasper issue. 
As Jasper is using PyAudio for Audio playback in jasper-dev, I am experiencing crackling audio out from jasper-dev. (on Raspbian Wizzy)
I tried aplay in place of PyAudio and it works without any issue,  just like it worked in previous version of jaspe-client.
I am not sure if some one else is also experiencing similar issue with Audio playback in jasper-dev. 
Its good if a config option is introduce to choose between 'aplay' and 'PyAudio' for audio playback  in jasper-dev.

**Comment by Holzhaus** [comment]
You could try to play with the values for `output_chunksize` and `output_padding` in your `profile.yml`. These are the defaults:

```yml
audio:
    output_chunksize: 1024
    output_padding: no
```

Since b68dc22aac1f45933fb1261ae35d72a2cdadffd9, we also have a new audio engine as an alternative to PyAudio. It relies on [ALSA](https://github.com/larsimmisch/pyalsaaudio) and can be used by putting this in your profile:

```yml
audio_engine: alsa
```

**Comment by G10DRAS** [comment]
I tried alsa audio engine as well with no luck.
My config is as following

    language: 'en-US'
    audio_engine: alsa
    input_device:   'front-card-u0x46d0x825-dev-0' 
    output_device:  'sysdefault-card-alsa' 
    # audio_engine: pyaudio
    # input_device:   'usb-device-0x46d-0x825-usb-audio'
    # output_device:  'bcm2835-alsa-bcm2835-alsa'
    keyword: 'JASPER'
    audio:
       input_samplerate: 16000
       input_samplewidth: 16
       input_channels: 1
       input_chunksize: 1024
       output_chunksize: 1024
       output_padding: 'no'    # true, yes
    

Could you list down what version of PyAlsaAudio, PortAudio  and  PyAudio you tested jasper-dev with ?

Even I got different list-audio-devices with two different config

with pyaudio config

    audio_engine: pyaudio
    input_device:   'usb-device-0x46d-0x825-usb-audio'
    output_device:  'bcm2835-alsa-bcm2835-alsa'

    ./jasper.py  --list-audio-devices

    [Audio device 'usb-device-0x46d-0x825-usb-audio']
      Name: USB Device 0x46d:0x825: USB Audio (hw:0,0)
      Input device: Yes
      Output device: No
    [Audio device 'bcm2835-alsa-bcm2835-alsa']
      Name: bcm2835 ALSA: bcm2835 ALSA (hw:1,0)
      Input device: No
      Output device: Yes
    [Audio device 'bcm2835-alsa-bcm2835-iec958-hdmi']
      Name: bcm2835 ALSA: bcm2835 IEC958/HDMI (hw:1,1)
      Input device: No
      Output device: Yes
    [Audio device 'sysdefault']
      Name: sysdefault
      Input device: Yes
      Output device: No
    [Audio device 'spdif']
      Name: spdif
      Input device: Yes
      Output device: No
    [Audio device 'usb']
      Name: usb
      Input device: Yes
      Output device: No
    [Audio device 'internal']
      Name: internal
      Input device: No
      Output device: Yes
    [Audio device 'default']
      Name: default
      Input device: Yes
      Output device: Yes

With alsa config

    audio_engine: alsa
    input_device:   'front-card-u0x46d0x825-dev-0' 
    output_device:  'sysdefault-card-alsa' 

    ./jasper.py  --list-audio-devices

    [Audio device 'front-card-u0x46d0x825-dev-0']
      Name: front:CARD=U0x46d0x825,DEV=0
      Input device: Yes
      Output device: No
    [Audio device 'iec958-card-u0x46d0x825-dev-0']
      Name: iec958:CARD=U0x46d0x825,DEV=0
      Input device: Yes
      Output device: No
    [Audio device 'null']
      Name: null
      Input device: Yes
      Output device: Yes
    [Audio device 'pulse']
      Name: pulse
      Input device: Yes
      Output device: Yes
    [Audio device 'surround40-card-u0x46d0x825-dev-0']
      Name: surround40:CARD=U0x46d0x825,DEV=0
      Input device: Yes
      Output device: No
    [Audio device 'surround41-card-u0x46d0x825-dev-0']
      Name: surround41:CARD=U0x46d0x825,DEV=0
      Input device: Yes
      Output device: No
    [Audio device 'surround50-card-u0x46d0x825-dev-0']
      Name: surround50:CARD=U0x46d0x825,DEV=0
      Input device: Yes
      Output device: No
    [Audio device 'surround51-card-u0x46d0x825-dev-0']
      Name: surround51:CARD=U0x46d0x825,DEV=0
      Input device: Yes
      Output device: No
    [Audio device 'surround71-card-u0x46d0x825-dev-0']
      Name: surround71:CARD=U0x46d0x825,DEV=0
      Input device: Yes
      Output device: No
    [Audio device 'sysdefault-card-alsa']
      Name: sysdefault:CARD=ALSA
      Input device: No
      Output device: Yes
    [Audio device 'sysdefault-card-u0x46d0x825']
      Name: sysdefault:CARD=U0x46d0x825
      Input device: Yes
      Output device: No

**Comment by G10DRAS** [comment]
With alsa config I got following error ........

    DEBUG:alsa_1_0_0.alsaaudioengine:Found 10 ALSA devices
    DEBUG:alsa_1_0_0.alsaaudioengine:Found 11 ALSA devices
    DEBUG:alsa_1_0_0.alsaaudioengine:Found 3 ALSA devices
    DEBUG:alsa_1_0_0.alsaaudioengine:Found 11 ALSA devices
    WARNING:sphinx_1_0_0.sphinxplugin:This STT plugin doesn't have multilanguage support!
    DEBUG:client.vocabcompiler:compiled_revision is 'a64e1b2cd78dec87d838e811694a508105291a2b'
    DEBUG:sphinx_1_0_0.sphinxplugin:Initializing PocketSphinx Decoder with hmm_dir '/usr/local/share/pocketsphinx/model/en-us/en-us'
    WARNING:sphinx_1_0_0.sphinxplugin:This STT plugin doesn't have multilanguage support!
    DEBUG:client.vocabcompiler:compiled_revision is 'bb74ae36d130ef20de710e3a77b43424b8fa774f'
    DEBUG:sphinx_1_0_0.sphinxplugin:Initializing PocketSphinx Decoder with hmm_dir '/usr/local/share/pocketsphinx/model/en-us/en-us'
    DEBUG:client.mic:Input sample rate: 16000 Hz
    DEBUG:client.mic:Input sample width: 16 bit
    DEBUG:client.mic:Input channels: 1
    DEBUG:client.mic:Input chunksize: 1024 frames
    DEBUG:client.mic:Output chunksize: 1024 frames
    DEBUG:client.mic:Output padding: no
    DEBUG:pico_tts_1_0_0.pico:Executing pico2wave -w /tmp/tmpCInIGF.wav -l en-US 'How can I be of service, JASPER?'
    DEBUG:alsa_1_0_0.alsaaudioengine:output stream opened on device 'sysdefault-card-alsa' (16000 Hz, 1 channel, 16 bit)
    DEBUG:alsa_1_0_0.alsaaudioengine:output stream closed on device 'sysdefault-card-alsa'
    DEBUG:client.conversation:Starting to handle conversation.
    INFO:client.mic:Waiting for keyword 'JASPER'...
    DEBUG:alsa_1_0_0.alsaaudioengine:input stream opened on device 'front-card-u0x46d0x825-dev-0' (16000 Hz, 1 channel, 16 bit)
    DEBUG:client.mic:Started recording on device 'front-card-u0x46d0x825-dev-0'
    DEBUG:client.mic:Triggered on SNR of 25.0395644033dB
    DEBUG:client.mic:Recording's SNR dB: 1.594557
    DEBUG:client.mic:Recorded 21 frames
    DEBUG:sphinx_1_0_0.sphinxplugin:INFO: pocketsphinx.c(145): Parsed model-specific feature parameters from /usr/local/share/pocketsphinx/model/en-us/en-us/feat.params
    DEBUG:sphinx_1_0_0.sphinxplugin:Current configuration:
    DEBUG:sphinx_1_0_0.sphinxplugin:[NAME]                  [DEFLT]         [VALUE]
    DEBUG:sphinx_1_0_0.sphinxplugin:-agc                    none            none
    DEBUG:sphinx_1_0_0.sphinxplugin:-agcthresh              2.0             2.000000e+00
    DEBUG:alsa_1_0_0.alsaaudioengine:input stream closed on device 'front-card-u0x46d0x825-dev-0'
    Traceback (most recent call last):
      File "./jasper.py", line 39, in <module>
        app.run()
      File "/home/pi/NewJasper/jasper-dev/jasper-client/client/application.py", line 239, in run
        self.conversation.handleForever()
      File "/home/pi/NewJasper/jasper-dev/jasper-client/client/conversation.py", line 40, in handleForever
        input = self.mic.listen()
      File "/home/pi/NewJasper/jasper-dev/jasper-client/client/mic.py", line 190, in listen
        self.wait_for_keyword(self._keyword)
      File "/home/pi/NewJasper/jasper-dev/jasper-client/client/mic.py", line 156, in wait_for_keyword
        snr = self._snr([frame])
      File "/home/pi/NewJasper/jasper-dev/jasper-client/client/mic.py", line 94, in _snr
        rms = audioop.rms(b"".join(frames), 2)
    audioop.error: not a whole number of frames

**Comment by Holzhaus** [comment]
$ pacman -Q portaudio python2 python2-pyalsaaudio python2-pyaudio
portaudio 19_20140130-1
python2 2.7.10-2
python2-pyalsaaudio 0.8.2-1
python2-pyaudio 0.2.8-1

**Comment by Holzhaus** [comment]
Different device names are normal by the way. Just try the `pulse` device for both input and output.

**Comment by G10DRAS** [comment]
Seems packages are messed up on my RPi2B. Recording part is working good but Audio Playback is a still a problem.

**Comment by Holzhaus** [comment]
Even with PyAlsaAudio?

Try setting the `output_chunksize` to 256 and `output_padding` to `yes`.

**Comment by gravytrain** [comment]
I am also having an issue with crackling audio when using pyAudio when moving to the jasper-dev build.  The method used for playback in the master branch works fine.  I have tried all of the suggestions in this thread, and running into issues with all of them.

**Comment by codeurfou** [comment]
The same as @G10DRAS & @gravytrain . And often, sound does not output at all :(

**Comment by codeurfou** [comment]
I found the "jack server" solution for the sound that did not output.
But sound is still crackling

**Comment by gkkulik** [comment]
Changing both occurences of the value "1024" to "4096" in audioengine.py basically solves the crackling problem.

**Comment by G10DRAS** [comment]
Thanks @gkkulik, could you also paste your profile.yml configuration.

**Comment by gravytrain** [comment]
Changing those values helps with the crackling audio, but it also cuts off the end of the recording.

**Comment by gravytrain** [comment]
Anyone manage to solve this issue completely?

**Comment by G10DRAS** [comment]
pyAudio --- playback --- No
Try alsa.
