### ISSUE TITLE
Spotify doesn't respond to commands

### ISSUE THREAD

**Issue by smokinpuppy** [jasperproject/jasper-client#405]
Hi,

I'm using spotify and it works great and plays my music, but it doesn't respond to any of the music mode control words. I've tried with "JASPER" and without. Any ideas on how to fix it?

Thanks,

Robert

**Comment by Holzhaus** [comment]
> Any ideas on how to fix it?

No, unless you post a *complete* debug log:

```
$ rm -rf ~/.jasper/vocabularies
$ ./jasper.py --debug
```

**Comment by smokinpuppy** [comment]
Sorry about that, here you go:
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
DEBUG:client.diagnose:Checking network connection to server 'www.google.com'...
DEBUG:client.diagnose:Network connection working
DEBUG:__main__:Trying to read config file: '/home/pi/.jasper/profile.yml'
DEBUG:client.diagnose:Checking python import 'pocketsphinx'...
DEBUG:client.diagnose:Python module 'pocketsphinx' found: '/usr/local/lib/python2.7/dist-packages/pocketsphinx.so'
DEBUG:client.diagnose:Checking executable 'aplay'...
DEBUG:client.diagnose:Executable 'aplay' found: '/usr/bin/aplay'
DEBUG:client.diagnose:Checking executable 'text2wave'...
DEBUG:client.diagnose:Executable 'text2wave' found: '/usr/bin/text2wave'
DEBUG:client.diagnose:Checking executable 'festival'...
DEBUG:client.diagnose:Executable 'festival' found: '/usr/bin/festival'
DEBUG:client.tts:Executing festival --pipe
DEBUG:client.vocabcompiler:compiled_revision is '08c8d4fe2d2d45b7f23ff9f7b6a90ee272a03d10'
DEBUG:client.brain:Looking for modules in: '/home/pi/jasper/client/modules'
DEBUG:client.brain:Found module 'Birthday' with words: ['BIRTHDAY']
DEBUG:client.brain:Found module 'Evernote' with words: ['NOTE']
DEBUG:client.brain:Found module 'Gmail' with words: ['EMAIL', 'INBOX']
DEBUG:client.brain:Found module 'HN' with words: ['HACKER', 'NEWS', 'YES', 'NO', 'FIRST', 'SECOND', 'THIRD']
DEBUG:client.brain:Found module 'Joke' with words: ['JOKE', 'KNOCK KNOCK']
DEBUG:client.brain:Found module 'Life' with words: ['MEANING', 'OF', 'LIFE']
DEBUG:client.brain:Found module 'MPDControl' with words: ['MUSIC', 'SPOTIFY']
DEBUG:client.brain:Found module 'Movies' with words: ['movie', 'movies', 'yes']
DEBUG:client.brain:Found module 'News' with words: ['NEWS', 'YES', 'NO', 'FIRST', 'SECOND', 'THIRD']
DEBUG:client.brain:Found module 'Notifications' with words: ['FACEBOOK', 'NOTIFICATION']
DEBUG:client.brain:Found module 'Status' with words: ['STATUS']
DEBUG:client.brain:Found module 'Time' with words: ['TIME']
DEBUG:client.brain:Found module 'Twitter' with words: ['TWITTER', 'TWITTER NOTIFICATIONS', 'DIRECT MESSAGE', 'FEED', 'TWEET', 'TRENDING', 'NOTIFICATION', 'NOTIFICATIONS']
DEBUG:client.brain:Found module 'Unclear' with words: []
DEBUG:client.brain:Found module 'Weather' with words: ['WEATHER', 'TODAY', 'TOMORROW']
DEBUG:client.brain:Found module 'knowledged' with words: ['WHO', 'WHAT', 'HOW MUCH', 'HOW MANY', 'HOW OLD']
DEBUG:client.vocabcompiler:compiled_revision is '47baa5e0c0db5250852a84d64fe61d2f29b35367'
INFO:client.mic:Initializing PyAudio. ALSA/Jack error messages that pop up during this process are normal and can usually be safely ignored.
ALSA lib pcm_dmix.c:1018:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2217:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm_dmix.c:957:(snd_pcm_dmix_open) The dmix plugin supports only playback stream
ALSA lib pcm_dmix.c:1018:(snd_pcm_dmix_open) unable to open slave
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
INFO:client.mic:Initialization of PyAudio completed.
DEBUG:client.tts:Saying 'How can I be of service, Robert?' with 'festival-tts'
DEBUG:client.tts:Executing text2wave
DEBUG:client.tts:Executing aplay /tmp/tmp2jlqLz.wav
DEBUG:client.tts:Output was: 'Playing WAVE '/tmp/tmp2jlqLz.wav' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
'
DEBUG:client.brain:Looking for modules in: '/home/pi/jasper/client/modules'
DEBUG:client.brain:Found module 'Birthday' with words: ['BIRTHDAY']
DEBUG:client.brain:Found module 'Evernote' with words: ['NOTE']
DEBUG:client.brain:Found module 'Gmail' with words: ['EMAIL', 'INBOX']
DEBUG:client.brain:Found module 'HN' with words: ['HACKER', 'NEWS', 'YES', 'NO', 'FIRST', 'SECOND', 'THIRD']
DEBUG:client.brain:Found module 'Joke' with words: ['JOKE', 'KNOCK KNOCK']
DEBUG:client.brain:Found module 'Life' with words: ['MEANING', 'OF', 'LIFE']
DEBUG:client.brain:Found module 'MPDControl' with words: ['MUSIC', 'SPOTIFY']
DEBUG:client.brain:Found module 'Movies' with words: ['movie', 'movies', 'yes']
DEBUG:client.brain:Found module 'News' with words: ['NEWS', 'YES', 'NO', 'FIRST', 'SECOND', 'THIRD']
DEBUG:client.brain:Found module 'Notifications' with words: ['FACEBOOK', 'NOTIFICATION']
DEBUG:client.brain:Found module 'Status' with words: ['STATUS']
DEBUG:client.brain:Found module 'Time' with words: ['TIME']
DEBUG:client.brain:Found module 'Twitter' with words: ['TWITTER', 'TWITTER NOTIFICATIONS', 'DIRECT MESSAGE', 'FEED', 'TWEET', 'TRENDING', 'NOTIFICATION', 'NOTIFICATIONS']
DEBUG:client.brain:Found module 'Unclear' with words: []
DEBUG:client.brain:Found module 'Weather' with words: ['WEATHER', 'TODAY', 'TOMORROW']
DEBUG:client.brain:Found module 'knowledged' with words: ['WHO', 'WHAT', 'HOW MUCH', 'HOW MANY', 'HOW OLD']
INFO:apscheduler.scheduler:Scheduler started
DEBUG:apscheduler.scheduler:Looking for jobs to run
DEBUG:apscheduler.scheduler:No jobs; waiting until a job is added
INFO:apscheduler.scheduler:Added job "Notifier.gather" to job store "default"
INFO:client.conversation:Starting to handle conversation with keyword 'ALICE'.
DEBUG:client.conversation:Started listening for keyword 'ALICE'
DEBUG:apscheduler.scheduler:Looking for jobs to run
DEBUG:apscheduler.scheduler:Next wakeup is due at 2015-12-20 21:24:35.991012+00:00 (in 29.982266 seconds)
INFO:client.stt:Transcribed: ['']
DEBUG:client.conversation:Stopped listening for keyword 'ALICE'
INFO:client.conversation:Nothing has been said or transcribed.
DEBUG:client.conversation:Started listening for keyword 'ALICE'
INFO:client.stt:Transcribed: ['WHAT A']
DEBUG:client.conversation:Stopped listening for keyword 'ALICE'
INFO:client.conversation:Nothing has been said or transcribed.
DEBUG:client.conversation:Started listening for keyword 'ALICE'
INFO:client.stt:Transcribed: ['ALICE']
DEBUG:client.conversation:Stopped listening for keyword 'ALICE'
INFO:client.conversation:Keyword 'ALICE' has been said!
DEBUG:client.conversation:Started to listen actively with threshold: 3182.4
DEBUG:client.tts:Executing aplay /home/pi/jasper/static/audio/beep_hi.wav
DEBUG:client.tts:Output was: 'Playing WAVE '/home/pi/jasper/static/audio/beep_hi.wav' : Signed 16 bit Little Endian, Rate 44100 Hz, Stereo
'
DEBUG:client.tts:Executing aplay /home/pi/jasper/static/audio/beep_lo.wav
DEBUG:client.tts:Output was: 'Playing WAVE '/home/pi/jasper/static/audio/beep_lo.wav' : Signed 16 bit Little Endian, Rate 44100 Hz, Stereo
'
INFO:client.stt:Transcribed: ['MUSIC']
DEBUG:client.conversation:Stopped to listen actively with threshold: 3182.4
DEBUG:client.brain:'MUSIC' is a valid phrase for module 'MPDControl'
DEBUG:MPDControl:Preparing to start music module
DEBUG:client.tts:Saying 'Please give me a moment, I'm loading your Spotify playlists.' with 'festival-tts'
DEBUG:client.tts:Executing text2wave
DEBUG:client.tts:Executing aplay /tmp/tmpRaYhT_.wav
DEBUG:apscheduler.scheduler:Looking for jobs to run
INFO:apscheduler.executors.default:Running job "Notifier.gather (trigger: interval[0:00:30], next run at: 2015-12-20 21:24:35 UTC)" (scheduled at 2015-12-20 21:24:35.991012+00:00)
DEBUG:apscheduler.scheduler:Next wakeup is due at 2015-12-20 21:25:05.991012+00:00 (in 29.997560 seconds)
DEBUG:client.tts:Output was: 'Playing WAVE '/tmp/tmpRaYhT_.wav' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
'
DEBUG:MPDControl:Starting music mode
DEBUG:client.vocabcompiler:Vocabulary dir '/home/pi/.jasper/vocabularies/pocketsphinx-vocabulary/music' does not exist, creating...
INFO:client.vocabcompiler:Starting compilation...
DEBUG:client.vocabcompiler:Compiling languagemodel...
DEBUG:client.vocabcompiler:Creating vocab file: '/tmp/tmpHxtrIO.vocab'
INFO:apscheduler.executors.default:Job "Notifier.gather (trigger: interval[0:00:30], next run at: 2015-12-20 21:25:05 UTC)" executed successfully
DEBUG:cmuclmtk:text2wfreq : Reading text from standard input...
DEBUG:cmuclmtk:text2wfreq : Done.
DEBUG:cmuclmtk:Command 'text2wfreq -hash 1000000 -verbosity 2' returned with exit code '0'.
DEBUG:cmuclmtk:wfreq2vocab : Will generate a vocabulary containing the most
DEBUG:cmuclmtk:frequent 20000 words. Reading wfreq stream from stdin...
DEBUG:cmuclmtk:wfreq2vocab : Done.
DEBUG:cmuclmtk:Command 'wfreq2vocab -verbosity 2 -records 1000000' returned with exit code '0'.
DEBUG:client.vocabcompiler:Creating languagemodel file: '/home/pi/.jasper/vocabularies/pocketsphinx-vocabulary/music/languagemodel'
DEBUG:cmuclmtk:text2idngram
DEBUG:cmuclmtk:Vocab                  : /tmp/tmpHxtrIO.vocab
DEBUG:cmuclmtk:Output idngram         : /tmp/tmp_Y8hjW.idngram
DEBUG:cmuclmtk:N-gram buffer size     : 100
DEBUG:cmuclmtk:Hash table size        : 2000000
DEBUG:cmuclmtk:Temp directory         : cmuclmtk-1OLZyc
DEBUG:cmuclmtk:Max open files         : 20
DEBUG:cmuclmtk:FOF size               : 10
DEBUG:cmuclmtk:n                      : 3
DEBUG:cmuclmtk:Initialising hash table...
DEBUG:cmuclmtk:Reading vocabulary...
DEBUG:cmuclmtk:Allocating memory for the n-gram buffer...
DEBUG:cmuclmtk:Reading text into the n-gram buffer...
DEBUG:cmuclmtk:20,000 n-grams processed for each ".", 1,000,000 for each line.
DEBUG:cmuclmtk:Sorting n-grams...
DEBUG:cmuclmtk:Writing sorted n-grams to temporary file cmuclmtk-1OLZyc/1
DEBUG:cmuclmtk:Merging 1 temporary files...
DEBUG:cmuclmtk:2-grams occurring:       N times         > N times       Sug. -spec_num value
DEBUG:cmuclmtk:0                                                     25             35
DEBUG:cmuclmtk:1                                     24               1             11
DEBUG:cmuclmtk:2                                      0               1             11
DEBUG:cmuclmtk:3                                      0               1             11
DEBUG:cmuclmtk:4                                      0               1             11
DEBUG:cmuclmtk:5                                      0               1             11
DEBUG:cmuclmtk:6                                      0               1             11
DEBUG:cmuclmtk:7                                      0               1             11
DEBUG:cmuclmtk:8                                      0               1             11
DEBUG:cmuclmtk:9                                      0               1             11
DEBUG:cmuclmtk:10                                     0               1             11
DEBUG:cmuclmtk:3-grams occurring:       N times         > N times       Sug. -spec_num value
DEBUG:cmuclmtk:0                                                     36             46
DEBUG:cmuclmtk:1                                     36               0             10
DEBUG:cmuclmtk:2                                      0               0             10
DEBUG:cmuclmtk:3                                      0               0             10
DEBUG:cmuclmtk:4                                      0               0             10
DEBUG:cmuclmtk:5                                      0               0             10
DEBUG:cmuclmtk:6                                      0               0             10
DEBUG:cmuclmtk:7                                      0               0             10
DEBUG:cmuclmtk:8                                      0               0             10
DEBUG:cmuclmtk:9                                      0               0             10
DEBUG:cmuclmtk:10                                     0               0             10
DEBUG:cmuclmtk:text2idngram : Done.
DEBUG:cmuclmtk:Command 'text2idngram -vocab /tmp/tmpHxtrIO.vocab -idngram /tmp/tmp_Y8hjW.idngram -buffer 100 -hash 2000000 -files 20 -verbosity 2 -n 3 -fof_size 10' returned with exit code '0'.
DEBUG:cmuclmtk:Warning : OOV fraction specified, but will not be used, since vocab type is not 2.
DEBUG:cmuclmtk:n : 3
DEBUG:cmuclmtk:Input file : /tmp/tmp_Y8hjW.idngram     (binary format)
DEBUG:cmuclmtk:Output files :
DEBUG:cmuclmtk:ARPA format   : /home/pi/.jasper/vocabularies/pocketsphinx-vocabulary/music/languagemodel
DEBUG:cmuclmtk:Vocabulary file : /tmp/tmpHxtrIO.vocab
DEBUG:cmuclmtk:Cutoffs :
DEBUG:cmuclmtk:2-gram : 0     3-gram : 0
DEBUG:cmuclmtk:Vocabulary type : Open - type 1
DEBUG:cmuclmtk:Minimum unigram count : 0
DEBUG:cmuclmtk:Zeroton fraction : 1
DEBUG:cmuclmtk:Counts will be stored in two bytes.
DEBUG:cmuclmtk:Count table size : 65535
DEBUG:cmuclmtk:Discounting method : Good-Turing
DEBUG:cmuclmtk:Discounting ranges :
DEBUG:cmuclmtk:1-gram : 1     2-gram : 7     3-gram : 7
DEBUG:cmuclmtk:Memory allocation for tree structure :
DEBUG:cmuclmtk:Allocate 100 MB of memory, shared equally between all n-gram tables.
DEBUG:cmuclmtk:Back-off weight storage :
DEBUG:cmuclmtk:Back-off weights will be stored in four bytes.
DEBUG:cmuclmtk:Reading vocabulary.
DEBUG:cmuclmtk:read_wlist_into_siht: a list of 15 words was read from "/tmp/tmpHxtrIO.vocab".
DEBUG:cmuclmtk:read_wlist_into_array: a list of 15 words was read from "/tmp/tmpHxtrIO.vocab".
DEBUG:cmuclmtk:WARNING: <s> appears as a vocabulary item, but is not labelled as a
DEBUG:cmuclmtk:context cue.
DEBUG:cmuclmtk:Allocated space for 3571428 2-grams.
DEBUG:cmuclmtk:Allocated space for 8333333 3-grams.
DEBUG:cmuclmtk:table_size 16
DEBUG:cmuclmtk:Allocated 57142848 bytes to table for 2-grams.
DEBUG:cmuclmtk:Allocated (2+33333332) bytes to table for 3-grams.
DEBUG:cmuclmtk:Processing id n-gram file.
DEBUG:cmuclmtk:20,000 n-grams processed for each ".", 1,000,000 for each line.
DEBUG:cmuclmtk:Calculating discounted counts.
DEBUG:cmuclmtk:Warning : 1-gram : Discounting range is 1; setting P(zeroton)=P(singleton).
DEBUG:cmuclmtk:Discounted value : 0.86
DEBUG:cmuclmtk:Warning : 2-gram : GT statistics are out of range; lowering cutoff to 6.
DEBUG:cmuclmtk:Warning : 2-gram : GT statistics are out of range; lowering cutoff to 5.
DEBUG:cmuclmtk:Warning : 2-gram : GT statistics are out of range; lowering cutoff to 4.
DEBUG:cmuclmtk:Warning : 2-gram : GT statistics are out of range; lowering cutoff to 3.
DEBUG:cmuclmtk:Warning : 2-gram : GT statistics are out of range; lowering cutoff to 2.
DEBUG:cmuclmtk:Warning : 2-gram : GT statistics are out of range; lowering cutoff to 1.
DEBUG:cmuclmtk:Warning : 2-gram : Discounting range of 1 is equivalent to excluding
DEBUG:cmuclmtk:singletons.
DEBUG:cmuclmtk:Warning : 2-gram : GT statistics are out of range; lowering cutoff to 0.
DEBUG:cmuclmtk:Warning : 2-gram : Discounting is disabled.
DEBUG:cmuclmtk:Warning : 3-gram : GT statistics are out of range; lowering cutoff to 6.
DEBUG:cmuclmtk:Warning : 3-gram : GT statistics are out of range; lowering cutoff to 5.
DEBUG:cmuclmtk:Warning : 3-gram : GT statistics are out of range; lowering cutoff to 4.
DEBUG:cmuclmtk:Warning : 3-gram : GT statistics are out of range; lowering cutoff to 3.
DEBUG:cmuclmtk:Warning : 3-gram : GT statistics are out of range; lowering cutoff to 2.
DEBUG:cmuclmtk:Warning : 3-gram : GT statistics are out of range; lowering cutoff to 1.
DEBUG:cmuclmtk:Warning : 3-gram : Discounting range of 1 is equivalent to excluding
DEBUG:cmuclmtk:singletons.
DEBUG:cmuclmtk:Warning : 3-gram : GT statistics are out of range; lowering cutoff to 0.
DEBUG:cmuclmtk:Warning : 3-gram : Discounting is disabled.
DEBUG:cmuclmtk:Unigrams's discount mass is 0.047619 (n1/N = 0.333333)
DEBUG:cmuclmtk:2 zerotons, P(zeroton) = 0.0238095 P(singleton) = 0.0238095
DEBUG:cmuclmtk:prob[UNK] = 0.0238095
DEBUG:cmuclmtk:Incrementing contexts...
DEBUG:cmuclmtk:Calculating back-off weights...
DEBUG:cmuclmtk:Writing out language model...
DEBUG:cmuclmtk:ARPA-style 3-gram will be written to /home/pi/.jasper/vocabularies/pocketsphinx-vocabulary/music/languagemodel
DEBUG:cmuclmtk:idngram2lm : Done.
DEBUG:cmuclmtk:Command 'idngram2lm -idngram /tmp/tmp_Y8hjW.idngram -vocab /tmp/tmpHxtrIO.vocab -vocab_type 1 -oov_fraction 0.5 -min_unicount 0 -verbosity 2 -n 3 -arpa /home/pi/.jasper/vocabularies/pocketsphinx-vocabulary/music/languagemodel -bin_input' returned with exit code '0'.
DEBUG:client.vocabcompiler:Getting words from vocab file and removing it afterwards...
DEBUG:client.vocabcompiler:Starting dictionary...
DEBUG:client.vocabcompiler:Getting phonemes for 13 words...
DEBUG:client.diagnose:Checking executable 'phonetisaurus-g2p'...
DEBUG:client.diagnose:Executable 'phonetisaurus-g2p' found: '/usr/local/bin/phonetisaurus-g2p'
DEBUG:client.g2p:Using FST model: '/home/pi/phonetisaurus/g014b2b.fst'
DEBUG:client.g2p:Converting 13 words to phonemes
DEBUG:client.g2p:G2P conversion returned phonemes for 13 words
DEBUG:client.vocabcompiler:Creating dict file: '/home/pi/.jasper/vocabularies/pocketsphinx-vocabulary/music/dictionary'
INFO:client.vocabcompiler:Compilation done.
INFO:client.mic:Initializing PyAudio. ALSA/Jack error messages that pop up during this process are normal and can usually be safely ignored.
INFO:client.mic:Initialization of PyAudio completed.
DEBUG:client.tts:Saying 'Playing Wicked Games by The Weeknd' with 'festival-tts'
DEBUG:client.tts:Executing text2wave
DEBUG:client.tts:Executing aplay /tmp/tmpGtdvDm.wav
DEBUG:client.tts:Output was: 'Playing WAVE '/tmp/tmpGtdvDm.wav' : Signed 16 bit Little Endian, Rate 16000 Hz, Mono
'
INFO:client.stt:Transcribed: ['']
INFO:MPDControl:Nothing has been said or transcribed.
INFO:client.stt:Transcribed: ['ON']
INFO:MPDControl:Nothing has been said or transcribed.
DEBUG:apscheduler.scheduler:Looking for jobs to run
INFO:apscheduler.executors.default:Running job "Notifier.gather (trigger: interval[0:00:30], next run at: 2015-12-20 21:25:05 UTC)" (scheduled at 2015-12-20 21:25:05.991012+00:00)
DEBUG:apscheduler.scheduler:Next wakeup is due at 2015-12-20 21:25:35.991012+00:00 (in 29.994017 seconds)
INFO:client.stt:Transcribed: ['CLOSE']
INFO:MPDControl:Nothing has been said or transcribed.
INFO:apscheduler.executors.default:Job "Notifier.gather (trigger: interval[0:00:30], next run at: 2015-12-20 21:25:35 UTC)" executed successfully
INFO:client.stt:Transcribed: ['NEWS']
INFO:MPDControl:Nothing has been said or transcribed.
INFO:client.stt:Transcribed: ['DO']
INFO:MPDControl:Nothing has been said or transcribed.
INFO:client.stt:Transcribed: ['STOP']
INFO:MPDControl:Nothing has been said or transcribed.
INFO:client.stt:Transcribed: ['CLOSE']
INFO:MPDControl:Nothing has been said or transcribed.
INFO:client.stt:Transcribed: ['']
INFO:MPDControl:Nothing has been said or transcribed.
^CERROR:client.brain:Failed to execute module
Traceback (most recent call last):
  File "/home/pi/jasper/client/brain.py", line 72, in query
    module.handle(text, self.mic, self.profile)
  File "/home/pi/jasper/client/modules/MPDControl.py", line 47, in handle
    music_mode.handleForever()
  File "/home/pi/jasper/client/modules/MPDControl.py", line 164, in handleForever
    threshold, transcribed = self.mic.passiveListen(self.persona)
  File "/home/pi/jasper/client/mic.py", line 163, in passiveListen
    data = stream.read(CHUNK)
  File "/usr/lib/pymodules/python2.7/pyaudio.py", line 564, in read
    return pa.read_stream(self._stream, num_frames)
KeyboardInterrupt
DEBUG:client.tts:Saying 'I'm sorry. I had some trouble with that operation. Please try again later.' with 'festival-tts'
DEBUG:client.tts:Executing text2wave
^CException RuntimeError: 'Set changed size during iteration' in <bound method Mic.__del__ of <client.mic.Mic instance at 0x2d908c8>> ignored
INFO:client.conversation:Received notification: 'New email from Gmail Team.'
INFO:client.conversation:Received notification: 'New email from Gmail Team.'
INFO:client.conversation:Received notification: 'New email from Gmail Team.'
INFO:client.conversation:Received notification: 'New email from Jasper.'
INFO:client.conversation:Received notification: 'New email from Jasper.'
DEBUG:client.conversation:Started listening for keyword 'ALICE'
DEBUG:apscheduler.scheduler:Looking for jobs to run
INFO:apscheduler.executors.default:Running job "Notifier.gather (trigger: interval[0:00:30], next run at: 2015-12-20 21:25:35 UTC)" (scheduled at 2015-12-20 21:25:35.991012+00:00)
DEBUG:apscheduler.scheduler:Next wakeup is due at 2015-12-20 21:26:05.991012+00:00 (in 29.992495 seconds)
INFO:client.stt:Transcribed: ['']
DEBUG:client.conversation:Stopped listening for keyword 'ALICE'
INFO:client.conversation:Nothing has been said or transcribed.
DEBUG:client.conversation:Started listening for keyword 'ALICE'
^CTraceback (most recent call last):
  File "jasper/jasper.py", line 148, in <module>
    app.run()
  File "jasper/jasper.py", line 118, in run
    conversation.handleForever()
  File "/home/pi/jasper/client/conversation.py", line 31, in handleForever
    threshold, transcribed = self.mic.passiveListen(self.persona)
  File "/home/pi/jasper/client/mic.py", line 163, in passiveListen
    data = stream.read(CHUNK)
  File "/usr/lib/pymodules/python2.7/pyaudio.py", line 564, in read
    return pa.read_stream(self._stream, num_frames)
KeyboardInterrupt
INFO:apscheduler.scheduler:Scheduler has been shut down
^CINFO:apscheduler.executors.default:Job "Notifier.gather (trigger: interval[0:00:30], next run at: 2015-12-20 21:26:05 UTC)" executed successfully
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/thread.py", line 39, in _python_exit
    t.join()
  File "/usr/lib/python2.7/threading.py", line 668, in join
    self.__block.wait()
  File "/usr/lib/python2.7/threading.py", line 244, in wait
    waiter.acquire()
KeyboardInterrupt
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/local/lib/python2.7/dist-packages/concurrent/futures/thread.py", line 39, in _python_exit
    t.join()
  File "/usr/lib/python2.7/threading.py", line 668, in join
    self.__block.wait()
  File "/usr/lib/python2.7/threading.py", line 244, in wait
    waiter.acquire()
KeyboardInterrupt
Exception RuntimeError: 'Set changed size during iteration' in <bound method Mic.__del__ of <client.mic.Mic instance at 0x3266d50>> ignored
*******************************************************************************************
Thank you in advance

Robert

**Comment by Holzhaus** [comment]
Did you somehow patch jasper to listen to the `ALICE` keyword instead of `JASPER`? Anyhow, the Spotify module doesn't support that:
https://github.com/jasperproject/jasper-client/blob/master/client/modules/MPDControl.py#L42-L43

**Comment by smokinpuppy** [comment]
Thanks for Holzhaus for your reply. Yes, I followed the instructions in the FAQ section to change the name although I think I might change it back as there are too many words that are similar to "ALICE" so it isn't recognizing it too much. I updated the MPDControl file to use "ALICE" and it responds now. Another is that came up though is with the actual commands. I'm testing with google stt and it returns an array with all the words it thinks work, so it seems that the first word is the one that is being recognized. I looked through MDPControl and I should be checking if any of the returned words match, but it doesn't seem to be working. Do you think I should program in a for loop to check all the words and return true if it is there?

Thank you so much :)

Robert

**Comment by Holzhaus** [comment]
@smokinpuppy You can, but I'd rather check out the `jasper-dev` branch, which has a rewritten version of the module.

**Comment by smokinpuppy** [comment]
right on, I'll do that. Thank you :) :+1:
