### ISSUE TITLE
STT option enhancement

### ISSUE THREAD

**Issue by smokinpuppy** [jasperproject/jasper-client#411]
Hi,

I think it would great if we could use one STT for passive listening and another for Active listening, as in passive it's possible that jasper would be waiting for his name to come up for hours and all the while he's checking the sounds he hears. This isn't very efficient for people using a service with a quota. So if it was only using (for example) google for active listening and sphinx for passive then you wouldn't use as much of the quota.

Thank you for all your work, its a really nice project,

Robert

**Comment by smokinpuppy** [comment]
Apparently already available :)

**Comment by DarthToker** [comment]
How do you implement that

**Comment by DarthToker** [comment]
Never mind I found it 

stt_engine: witai
stt_passive_engine: sphinx

Or what ever u want
