### ISSUE TITLE
phonetisaurus-0.7.8.tgz not exists?

### ISSUE THREAD

**Issue by Alam90210** [jasperproject/jasper-client#412]
First I found the openfst-1.3.3.tar.gz no longer exists on the host, after googling its said already change to openfst-1.3.4.tar.gz. Next I'm stuck in downloading the phonetisaurus-0.7.8.tgz file which also no longer exists on the host, and I still have no idea where to find it. Any idea are truly appreciated. Thanks

**Comment by Holzhaus** [comment]
https://www.dropbox.com/s/kfht75czdwucni1/g014b2b.tgz?dl=0
