### ISSUE TITLE
Jasper v2 (jasper-dev) config path is overlapping with Jasper v1 config path.

### ISSUE THREAD

**Issue by G10DRAS** [jasperproject/jasper-client#419]
Jasper v2 (jasper-dev) config path is overlapping with Jasper v1 config path, if both are install on same m/c.

A simple change in paths.py  of jasper-dev will solve the problem.

     CONFIG_PATH = os.path.expanduser(os.getenv('JASPER_CONFIG', '~/.jasper'))
     change to
     CONFIG_PATH = os.path.expanduser(os.getenv('JASPER_CONFIG', '~/.jasperV2'))

**Comment by Holzhaus** [comment]
You can easily work around by running the two jasper installations as different users.

**Comment by G10DRAS** [comment]
I am running 4 Jasper, and creating 4 users is realy a bad idea for me.
But it is not a big issue for end user though. 
closing this issue .
