### ISSUE TITLE
Wikipedia module

### ISSUE THREAD

**Issue by amar-laksh** [jasperproject/jasper-client#423]
I would like to suggest an addition to the existing modules under the project with that being of a Wikipedia module to perform Wikipedia quick searches on different topics. Currently, I do have some code that might provide an idea for this. 

https://github.com/amar-laksh/wikapy

P.S - The jasper project is seriously amazing, thank you :)

**Comment by edouardpoitras** [comment]
It's also worth looking into this v1.0 module: https://github.com/Naoto-Ida/Jasper-Wikipedia
