### ISSUE TITLE
Problem with a command 

### ISSUE THREAD

**Issue by MarkusLowa** [jasperproject/jasper-client#425]
Hello Thomas,

When I want to run this command  "sudo dpkg --install pico2wave.deb", I get an ERROR like this:

dpkg: error processing archive pico2wave.deb (--install):
 cannot access archive: No such file or directory
Errors were encountered while processing:
 pico2wave.deb

Maybe you have a solution for me...

nice regards from Austria

Markus

**Comment by Holzhaus** [comment]
> cannot access archive: No such file or directory

You don't have that file (pico2wave.deb).
