### ISSUE TITLE
SystemExit being caught by client/brain.py

### ISSUE THREAD

**Issue by ensingm2** [jasperproject/jasper-client#432]
Hey all, I'm making a simple module to either exit Jasper or shut the device down via voice commands("Quit"/"Exit" exit jasper, "Shut down"/"shutdown" powers off the device), but it seems like sys.exit(), which raises SystemExit, is being caught and ignored by brain.py. 

I can workaround this by using os._exit() instead, but this stops any cleanup from happening. Wouldn't it be useful to allow modules to exit Jasper? Not all uses for Jasper use it as the only program running, so having a way to cleanly exit via voice command would be nice, unless I'm missing something that already exists.

Thanks!

**Comment by G10DRAS** [comment]
In conversion.py try below code

            self._logger.debug(" Start to listen actively with threshold: %r .",
                               threshold)				
            input = self.mic.activeListenToAllOptions(threshold)
                               
            if "SHUTDOWN" in input.split(): 
                self.mic.say('OK SHUTING DOWN.')
                break
                            
            if input:
                self.brain.query(input)
            else:
                self.mic.say(" Pardon?")

**Comment by ensingm2** [comment]
Yeah, I'm aware that I can edit the files to work around this, and that seems like it'd work (haven't been able to test because I've had to format and start from scratch since then).

I was more opening the issue as an example of why it may be worth only catching specific exceptions from modules rather than a [general "the module failed" catch-all](https://github.com/jasperproject/jasper-client/blob/f9750d85b7bf6d52d2aabe222782a6e25c2341ad/client/brain.py#L72-L78), or at least allowing/handling potentially useful ones like SystemExit through.

If that's not the case though, feel free to close.

**Comment by Holzhaus** [comment]
You're right, catching `SystemExit` is probably a bit excessive. By the way, it should work in the `jasper-dev` branch. I'll backport this to current master.

**Comment by ucy74** [comment]
This kills jasper:
```
import subprocess
proc = subprocess.Popen(["pkill", "-f", "jasper.py"], stdout=subprocess.PIPE)
proc.wait()
```
I was creating module named _Shutdown.py_ based on _Life.py_
I was adding words _**down, shut**_ and _**shutdown**_ to _keyword_phrases_ file and running _boot.sh_ script at end.
File location: ~/jasper/client/modules/Shutdown.py                   

```
# -*- coding: utf-8-*-
import random
import sys
import re
import subprocess

WORDS = ["SHUTDOWN", "SHUT", "DOWN"]

def handle(text, mic, profile):
    """
        Responds to user-input, typically speech text, by shuting down jasper

        Arguments:
        text -- user-input, typically transcribed speech
        mic -- used to interact with the user (for both input and output)
        profile -- contains information related to the user (e.g., phone
                   number)
    """
    messages = ["I'm going down.",
                "Shuting down now.",
                "Bye Bye."]

    message = random.choice(messages)
    mic.say(message)

    proc = subprocess.Popen(["pkill", "-f", "jasper.py"], stdout=subprocess.PIPE)
    proc.wait()

def isValid(text):
    """
        Returns True if the input is related to the jasper's quit.

        Arguments:
        text -- user-input, typically transcribed speech
    """
    return bool(re.search(r'\bshut down\b', text, re.IGNORECASE))
```
