### ISSUE TITLE
Servo module with RPi.GPIO problem 

### ISSUE THREAD

**Issue by DarkoStoicic** [jasperproject/jasper-client#437]
I have module whit GPIO pins involved which controles servo.

My code:
```ruby
# -*- coding: utf-8-*-
import random
import re
import RPi.GPIO as GPIO
import time
WORDS = ["TURN", "ON", "SERVO"]
GPIO.setmode(GPIO.BOARD)
GPIO.setup(7,GPIO.OUT)

p = GPIO.PWM(7,50)
p.start(7.5)
try:
        while True:
            p.ChangeDutyCycle(7.5)  
            time.sleep(1)
            p.ChangeDutyCycle(12.5)  
            time.sleep(1)
            p.ChangeDutyCycle(2.5) 
            time.sleep(1)
except KeyboardInterrupt:
    GPIO.cleanup()
def handle(text, mic, profile):
    """
        Responds to user-input, typically speech text, by relaying the
        meaning of life.
        Arguments:
        text -- user-input, typically transcribed speech
        mic -- used to interact with the user (for both input and output)
        profile -- contains information related to the user (e.g., phone
                   number)
    """
    messages = ["It's on.",
                "It's on. Servo is on?"]

    message = random.choice(messages)

    mic.say(message)
    
def isValid(text):
    """
        Returns True if the input is related to the meaning of life.
        Arguments:
        text -- user-input, typically transcribed speech
    """
    return bool(re.search(r'\bmeaning of life\b', text, re.IGNORECASE))
```

Error on Jasper console:

File "/home/pi/jasper/client/modules/servo.py", line 8, in <module>
     GPIO.setup(7,GPIO,OUT)
RuntimeError: No access to /dev/mem. Try running as root!

So I can simply run my program by typing: sudo idle3 python servo.py or sudo python servo.py and works fine.
But how to make it work in jasper. How to make servo.py run as super user from jasper?
Thanks in advance.

**Comment by G10DRAS** [comment]
Dump your GPIO code in a python script and call that script using subprocess

      cmd = ['sudo','python', <path to servo.py>]
      .......
      proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
      ......

**Comment by Holzhaus** [comment]
And don't forget to edit your `/etc/sudoers` so that you can execute that particular command without being asked for a password (if that's not already the case).

**Comment by DarkoStoicic** [comment]
Thanks for advice. I solved problem by calling script:

    import os
    os.system('sudo python servo.py')

Note: servoscript.py and servo.py are in the same folder.
