### ISSUE TITLE
ALSA error Invalid sample rate -9997

### ISSUE THREAD

**Issue by Beyond-Birthday** [jasperproject/jasper-client#450]
Hello, 
Since 2 weeks, i've try to install Jasper on my brand new Raspberry Pi 2 model 2 running on Jessie.
But I've got the same error every time : 

*******************************************************
*             JASPER - THE TALKING COMPUTER           *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
WARNING:root:tts_engine not specified in profile, defaulting to 'espeak-tts'
ALSA lib pcm_dmix.c:1022:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm_dmix.c:1022:(snd_pcm_dmix_open) unable to open slave
Expression 'paInvalidSampleRate' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2048
Expression 'PaAlsaStreamComponent_InitialConfigure( &self->capture, inParams, self->primeBuffers, hwParamsCapture, &realSr )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2719
Expression 'PaAlsaStream_Configure( stream, inputParameters, outputParameters, sampleRate, framesPerBuffer, &inputLatency, &outputLatency, &hostBufferSizeMode )' failed in 'src/hostapi/alsa/pa_linux_alsa.c', line: 2843
Traceback (most recent call last):
  File "jasper.py", line 148, in <module>
    app.run()
  File "jasper.py", line 118, in run
    conversation.handleForever()
  File "/home/pi/jasper/client/conversation.py", line 31, in handleForever
    threshold, transcribed = self.mic.passiveListen(self.persona)
  File "/home/pi/jasper/client/mic.py", line 110, in passiveListen
    frames_per_buffer=CHUNK)
  File "/usr/lib/python2.7/dist-packages/pyaudio.py", line 747, in open
    stream = Stream(self, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pyaudio.py", line 442, in __init__
    self._stream = pa.open(**arguments)
IOError: [Errno Invalid sample rate] -9997

I've got a USB mic and a speaker on jack. Thanks for helping ^^

**Comment by ThomasDelteil** [comment]
I had a similar issue, fortunately the jasper-dev branch has some changes in that allow you to configure the input and output devices, the sample rate, number of channels and chunk size directly in `.jasper/profile.yaml`
Try to checkout the dev branch and configure your input device.

You can use `pulseaudio` `sudo apt-get install pulseaudio` to determine the frame rate and number of channels of your USB mic by running.
`pactl list short sinks`
(http://www.voxforge.org/home/docs/faq/faq/linux-how-to-determine-your-audio-cards-or-usb-mics-maximum-sampling-rate)

Note that installing `pulseaudio` seems to mess with the default input and output device on your raspberry pi. After installing pulseaudio my output would not work by default I had to set it manually in the `profile.yaml` file, but my input device started working :open_mouth:. 

The relevant part of my `profile.yaml`

```
output_device: bcm2835-alsa-hw10
audio:
  input_chunksize: 1024
  input_samplerate: 41800
  input_channels: 1
```

**Comment by GeoBeBee** [comment]
Thought it might be useful to cross reference back to the Support Forum where people are also reporting the 'Invalid sample rate':
[https://groups.google.com/forum/#!topic/jasper-support-forum/DzsFdAKYbEo](https://groups.google.com/forum/#!topic/jasper-support-forum/DzsFdAKYbEo)

**Comment by mattcurrycom** [comment]
This is a config issue, please use the [forum](https://groups.google.com/forum/#!forum/jasper-support-forum).
