### ISSUE TITLE
ValueError: TTS engine 'google-tts' is not available (due to missing dependencies, etc.)

### ISSUE THREAD

**Issue by wscheper** [jasperproject/jasper-client#455]
When I try to start Jasper I get the following message:

ValueError: TTS engine 'google-tts' is not available (due to missing dependencies, etc.)

It doesn't matter which TTS engine I choose, it never works.

Jasper seems like a cool product, but to be honest I'm a bit done with it by now. For three evenings in a row I have been busy trying to install Jasper on Raspbian/Raspberry Pi B+. After I had to find out a dozen of missing wget links and compile errors I gave it up. I thought trying it on ArchLinux would be a solution, but I was wrong. Again a pain in the ass getting PocketSphinx to work, so I skipped it and tried other engines. It didn't go smooth and I though I finally had it all working, until again an error comes up.

I strongly advice the authors of the project to update their installation instructions, inform their users, or just deprecate this project. But at least don't let users spend hours on something that doesn't want to work.

**Comment by Holzhaus** [comment]
Please use this issue tracker to report code bugs only. If you have usage questions, please use the forum: https://groups.google.com/forum/#!forum/jasper-support-forum
