### ISSUE TITLE
Pocketsphinx failes to install because sphinxbase has no armv6h architecture

### ISSUE THREAD

**Issue by phynix719** [jasperproject/jasper-client#460]
The title pretty much says it all. The exact error I get is this while trying to install jasper-stt-pocketsphinx from the AUR
`==> ERROR: sphinxbase is not available for the 'armv6h' architecture.
The build failed.
warning: armv6h missing from arch array`

Thanks for your help.

**Comment by Holzhaus** [comment]
You need to use `yaourt`'s `-A` flag.

**Comment by phynix719** [comment]
Thank you. Solves my problem.
