### ISSUE TITLE
Unable to install module Jasper-Twitter, any help would be very appreciated

### ISSUE THREAD

**Issue by ncoletto** [jasperproject/jasper-client#461]
Hi! I am running Raspbian Jessie Linux raspberrypi 4.1.18-v7+ #845 SMP.
Jasper works ok, but I encounter many different errors while trying to install and run a module that is in Jasper's website "Twitter module", following their install instructions.

http://jasperproject.github.io/documentation/modules/

Any help would be very appreciated!
Thanks in advance, 
Nicolas

pi@raspberrypi ~/jasper $ sudo pip install tweepy
Downloading/unpacking tweepy
Cannot fetch index base URL http://pypi.python.org/simple/
Could not find any downloads that satisfy the requirement tweepy
No distributions at all found for tweepy
Storing complete log in /root/.pip/pip.log

pi@raspberrypi ~/jasper $ git clone https://github.com/marclave/Jasper-Twitter.git
Cloning into 'Jasper-Twitter'...
error: Couldn't resolve host 'github.com' while accessing https://github.com/marclave/Jasper-Twitter.git/info/refs
fatal: HTTP request failed

pi@raspberrypi ~/jasper $ ./jasper.py

JASPER - THE TALKING COMPUTER *
(c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis * ******************************************************* WARNING:root:Network not connected. This may prevent Jasper from running properly. WARNING:client.brain:Skipped module 'Twitter' due to an error. Traceback (most recent call last): File "/home/pi/jasper/client/brain.py", line 43, in get_modules mod = loader.load_module(name) File "/usr/lib/python2.7/pkgutil.py", line 246, in load_module mod = imp.load_module(fullname, self.file, self.filename, self.etc) File "/home/pi/jasper/client/modules/Twitter.py", line 1, in import tweepy ImportError: No module named tweepy

**Comment by Holzhaus** [comment]
Please use this issue tracker to report code bugs only. If you have usage questions, please use the forum: https://groups.google.com/forum/#!forum/jasper-support-forum

**Comment by ncoletto** [comment]
Thanks for your response! sorry I did not know that. I´ll post there.
