### ISSUE TITLE
Error while trying to start

### ISSUE THREAD

**Issue by RubidiumBlade** [jasperproject/jasper-client#462]
Hello! I've been trying to get this running, but when I try to start it it throws a bunch of errors. I was having a very similar issue to [https://github.com/jasperproject/jasper-client/issues/433](this guy), but his solution didn't provide the same result for me (couldn't get the "jasper - the talking computer" in a box to ever show up). This is the errors it is throwing when I do `python jasper.py`:

` Traceback (most recent call last):`
`  File "jasper.py", line 13, in <module>`
`    from client.conversation import Conversation`
`  File "/home/pi/jasper/client/conversation.py", line 3, in <module>`
`    from notifier import Notifier`
`  File "/home/pi/jasper/client/notifier.py", line 4, in <module>`
`    from modules import Gmail`
`  File "/home/pi/jasper/client/modules/Gmail.py", line 5, in <module>`
`    from dateutil import parser`
`  File "/usr/local/lib/python2.7/dist-packages/dateutil/parser.py", line 14, in <module>`
`    from six import text_type, binary_type, integer_types`
`ImportError: No module named six`
Any help? 

P.S. How do you put the error in the nice box like the guy I mentioned did?

**Comment by Holzhaus** [comment]
Try to install `six`, either via package manager or `pip`.

> P.S. How do you put the error in the nice box like the guy I mentioned did?
https://help.github.com/articles/creating-and-highlighting-code-blocks/
