### ISSUE TITLE
Module time / change word : don't work

### ISSUE THREAD

**Issue by zola2** [jasperproject/jasper-client#465]
Hi,

With module "Time" with : 
WORDS = ["TIME"]

It's ok !
When I say "Time", the script is launched and it tells me the time

But if i change it to : 
WORDS = ["HOURS"]

Debug :
INFO:client.stt:Transcribed: [u'HOURS']
The STT function works well but, It's the "Unclear" script is launched

I do not understand why

Can you help me ?

Thanks

**Comment by Holzhaus** [comment]
Fid you also change the is_valid function?
