### ISSUE TITLE
pocketsphinx can't find g014b2b.fst?

### ISSUE THREAD

**Issue by RubidiumBlade** [jasperproject/jasper-client#466]
When I start up Jasper, it's throwing this error:

*******************************************************
*             JASPER - THE TALKING COMPUTER           *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
ERROR:client.vocabcompiler:Fatal compilation Error occured, cleaning up...
Traceback (most recent call last):
  File "/home/pi/jasper/client/vocabcompiler.py", line 163, in compile
    self._compile_vocabulary(phrases)
  File "/home/pi/jasper/client/vocabcompiler.py", line 271, in _compile_vocabulary
    self._compile_dictionary(vocabulary, self.dictionary_file)
  File "/home/pi/jasper/client/vocabcompiler.py", line 320, in _compile_dictionary
    g2pconverter = PhonetisaurusG2P(**PhonetisaurusG2P.get_config())
  File "/home/pi/jasper/client/g2p.py", line 93, in __new__
    "instance.") % fst_model)
OSError: FST model ''../phonetisaurus/g014b2b.fst'' does not exist! Can't create instance.
ERROR:root:Error occured!
Traceback (most recent call last):
  File "jasper.py", line 143, in <module>
    app = Jasper()
  File "jasper.py", line 106, in __init__
    stt_passive_engine_class.get_passive_instance(),
  File "/home/pi/jasper/client/stt.py", line 48, in get_passive_instance
    return cls.get_instance('keyword', phrases)
  File "/home/pi/jasper/client/stt.py", line 40, in get_instance
    vocabulary.compile(phrases)
  File "/home/pi/jasper/client/vocabcompiler.py", line 171, in compile
    raise e
OSError: FST model ''../phonetisaurus/g014b2b.fst'' does not exist! Can't create instance.

It seems like it just can't find the g014b2b.fst file, but I've confirmed it is there and its in the default path. I've tried putting the path in profile.yml, but that didn't help. Any help?

**Comment by andweber** [comment]
its not expected in the default path, its expected in "../phonetisaurus/g014b2b.fst" - set a sym link or copy it to this location.
In your case: "/home/pi/phonetisaurus/g014b2b.fst"

**Comment by RubidiumBlade** [comment]
Hmm, I'm really not sure what I'm doing wrong... I tried messing with it a bit more, but am not having any luck. Here is me finding the file in the terminal:
![image](https://cloud.githubusercontent.com/assets/13438477/13766400/c4db3f1c-ea1e-11e5-8797-a3cdf3ff5d11.png)
and here is the relevant part of my profile.yml:
![image](https://cloud.githubusercontent.com/assets/13438477/13766437/0676e23c-ea1f-11e5-9489-5c23794870ee.png)
and here is the error it throws:
![image](https://cloud.githubusercontent.com/assets/13438477/13766455/3b9e09ae-ea1f-11e5-8e85-2577f7621dda.png)
It seems to me that the profile.yml is pointing to the right spot, but it just isn't working. Am I missing something? I'm not all that great with linux so there could easily be something I totally missed that should be obvious.

**Comment by Holzhaus** [comment]
Try `/home/username` instead of `~`.
