### ISSUE TITLE
Getting Jasper to read TXT files

### ISSUE THREAD

**Issue by nifhail** [jasperproject/jasper-client#497]
i've tried so many ways with my knowledge in python but i can't seem to get it.. anyone can help me with this? :(

**Comment by GeoBeBee** [comment]
What have you tried?

**Comment by mkotzjan** [comment]
To read a file with python you have to open it first:
`file = open('yourfile.txt', 'r')`
The option 'r' let you open the file in "Read" mode.
Now use 'read()' to get the text:
`text = file.read()`
I assume you want Jasper to read the file on your command, which means you have to write your own module. Just follow the documentation: [https://jasperproject.github.io/documentation/api/standard/](url)

Your 'handle' method will look something like this:
```python
def handle(text, mic, profile):
    file = open('<PATH TO YOUR FILE>', 'r')
    message = file.read()

    mic.say(message)
```

**Comment by redfast00** [comment]
@mkotzjan don't forget to close the file afterwards with `file.close()` (although I recommend using a `with` statement and another variable name than  `file`).

**Comment by mkotzjan** [comment]
@redfast00 Thank you! I've missed that!
```python
def handle(text, mic, profile):
    with open("newtext.txt") as text:
        message = text.read()

    mic.say(message)

```

**Comment by Holzhaus** [comment]
This is not really jasper related. Closing.
