### ISSUE TITLE
SST and TTS do not work on the Raspberry Pi 3

### ISSUE THREAD

**Issue by cable2T17** [jasperproject/jasper-client#499]
I love the idea of Jasper, but I have been encountering problems installing the STT and TTS modules

I am running Arch Linux, I have a Raspberry Pi 3 and I get this response:

==> Building and installing package
==> ERROR: flite is not available for the 'armv7h' architecture.
==> ERROR: Makepkg was unable to build flite.

for pocketsphinx:
==> ERROR: cmuclmtk is not available for the 'armv7h' architecture.
==> ERROR: Makepkg was unable to build cmuclmtk.
==> Restart building cmuclmtk ? [y/N]

**Comment by iamtheib** [comment]
At the step when it asks you to `Edit PKGBUILD ? [Y/n] ("A" to abort)`, enter `y` for yes. On the line that has `arch=('i686' 'x86_64')`, add `'armv7h'` to make it `arch=('i686' 'x86_64' 'armv7h')`.

That should get the package download and installation started.

You might have to edit `PKGBUILD` further, to tweak the flags used with `gcc` to make it compile on your architecture.

Also, `pocketsphinx` is very large and can take a long time to compile. Make sure you increase the size of tmp folder/tmpfs, or set the build directory to a location with enough space by exporting `BUILDDIR=/home/tmp` or some other directory.

**Comment by Holzhaus** [comment]
You can use `makepkg`'s `-A, --ignorearch` flag ("Ignore a missing or incomplete arch field in the build script. This is for rebuilding packages from source when the PKGBUILD may be slightly outdated and not updated with an arch=('yourarch') field.").

**Comment by dmbuchta** [comment]
@cable2T17 as a note, I successfully installed it on my raspberry PI 3 this weekend using the provided Raspian Jessie image.
