### ISSUE TITLE
Error at Compiling and Installing Phonetisaurus:

### ISSUE THREAD

**Issue by theja0473** [jasperproject/jasper-client#500]
root@raspberrypi:~/Phonetisaurus/src# ./configure
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking whether g++ supports C++11 features by default... no
checking whether g++ supports C++11 features with -std=gnu++11... no
checking whether g++ supports C++11 features with -std=gnu++0x... no
checking whether g++ supports C++11 features with -std=c++11... no
checking whether g++ supports C++11 features with -std=c++0x... no
configure: error: *** A compiler with support for C++11 language features is required.

![screenshot from 2016-04-29 17-50-03](https://cloud.githubusercontent.com/assets/15976291/14947471/bd509040-1051-11e6-8974-3a72689f4374.png)
![screenshot from 2016-04-29 17-50-03](https://cloud.githubusercontent.com/assets/15976291/14947483/e45c389c-1051-11e6-8cb3-5c859fb522e5.png)

**Comment by Holzhaus** [comment]
It looks like you're using a really outdated compiler version. You can check that with `g++ -v`.

**Comment by theja0473** [comment]
I am using latest g++ version only shown bellow.
![g version](https://cloud.githubusercontent.com/assets/15976291/14982338/46964866-1153-11e6-897f-3d1ed6a3a586.JPG)

**Comment by Holzhaus** [comment]
No, gcc 4.6.3 is not the latest version. It's [more than 4 years old](https://gcc.gnu.org/gcc-4.6/) (released March 1, 2012). The current version is [gcc 6.1](https://gcc.gnu.org/gcc-6/).

**Comment by nmstoker** [comment]
I know this is closed, but for anyone who stumbles on it, the steps below works in Jessie (which has 4.9, so isn't as old as 4.6.3 but still falls behind @Holzhaus! :wink: ) on a Raspberry Pi 3.

Am assuming you downloaded and prepared Phonetisaurus something akin to:

- `wget https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/phonetisaurus/is2013-conversion.tgz`
(ie from https://code.google.com/archive/p/phonetisaurus/downloads )
- `tar -zxvf is2013-conversion.tgz` (to unpack)
- `cd /is2013-conversion/phonetisaurus/src`(as folder structures slightly changed)

If you follow the instructions (**sudo make**) you'll get an error compiling, as it needs a flag set for C++11. I'm rusty on C++ but it was as simple as editing **Makefile** and adding this line at the top (after the comments):
  `CXXFLAGS=-std=c++11` 
and then re-trying sudo make.  Be prepared for a bit of a wait! Initially it did nothing, so I wondered if it got stuck but then you see it slowly go through the stages and complete.

**Comment by paulgreg** [comment]
Tried to add `CXXFLAGS=-std=c++11` to Makefile but it fail the same way...
```
pi@raspberrypi:~/is2013-conversion/phonetisaurus/src $ sudo make
g++ -O2 -I3rdparty/sparsehash -I3rdparty/utfcpp -std=c++11   -c Phonetisaurus.cpp -o Phonetisaurus.o
In file included from /usr/local/include/fst/rational.h:31,
                 from /usr/local/include/fst/closure.h:29,
                 from /usr/local/include/fst/fstlib.h:62,
                 from Phonetisaurus.cpp:34:
/usr/local/include/fst/replace.h: In constructor ‘fst::ArcIterator<fst::ReplaceFst<A, T> >::ArcIterator(const fst::ReplaceFst<A, T>&, fst::ArcIterator<fst::ReplaceFst<A, T> >::StateId)’:
/usr/local/include/fst/replace.h:1069:46: error: expected ‘;’ before ‘::’ token
       (fst_.GetImpl())->template CacheImpl<A>::InitArcIterator(state_,
                                              ^~
                                              ;
make: *** [Makefile:54: Phonetisaurus.o] Error 1
```

Here’s my g++ version :
```
$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-gnueabihf/8/lto-wrapper
Target: arm-linux-gnueabihf
Configured with: ../src/configure -v --with-pkgversion='Raspbian 8.3.0-6+rpi1' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=arm-linux-gnueabihf- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libitm --disable-libquadmath --disable-libquadmath-support --enable-plugin --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-sjlj-exceptions --with-arch=armv6 --with-fpu=vfp --with-float=hard --disable-werror --enable-checking=release --build=arm-linux-gnueabihf --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf
Thread model: posix
gcc version 8.3.0 (Raspbian 8.3.0-6+rpi1) 
```

**Comment by ysharoiko** [comment]
Same trouble i got
gcc version 8.3.0 (Debian 8.3.0-6)

**Comment by nmstoker** [comment]
Given the project was last touched by the developers four years ago and most of the code seems unchanged since six years ago, you might want to consider whether this is going to be worth it.

Another sign to suggest caution are all the unanswered issues (the closed ones seems closed by the openers from what I see)
