### ISSUE TITLE
Proposal: Allow jasper to execute commands while passive listening?

### ISSUE THREAD

**Issue by dmbuchta** [jasperproject/jasper-client#502]
Has there been any thought about allowing Jasper to execute a command at the same time as hearing his name. Instead of:

**Me:** Jasper
_High Beep_
**Me:** What time is it?
_Low Beep_

It could be:
**Me:** Jasper what time is it?
_Low Beep (if valid)_
_High Beep (if not valid)_

**Comment by G10DRAS** [comment]
This is possible but its not straight forward, need changes in Jasper code. And with such implementation, there is a possibility of spamming STT (if you are using online services) with garbage requests.

**Comment by dmbuchta** [comment]
Well STT gets spammed regardless since Jasper is always listening for the keyword "Jasper", is it not?

**Comment by dmbuchta** [comment]
If that's incorrect than please let me know because that's another issue I'm trying to  deal with.

**Comment by G10DRAS** [comment]
You can configure Jasper with 2 STT.

1. stt_passive_engine ---> usually offline STT Pocketsphinx, for Keyword (ex: 'JASPER') detection
2. stt_engine ----> An Offline or Online STT, for handling phrases/commands

A sample configuration in profile.yml 

stt_engine: google   
stt_passive_engine: sphinx
pocketsphinx:
  fst_model: '<path_to_fst_model>'  
  hmm_dir: '<path_to_hmm_dir>'  

So your example above will looks like 

Me: Jasper -----> ( This part will handle by stt_passive_engine)
High Beep
Me: What time is it? ------> (This part will handle by stt_engine)
Low Beep

See stt_passive_engine implementation part in jasper.py

        try:
            slug = self.config['stt_passive_engine']
            stt_passive_engine_class = stt.get_engine_by_slug(slug)
        except KeyError:
            stt_passive_engine_class = stt_engine_class

**Comment by dmbuchta** [comment]
ahhhh, I never noticed this. Thanks! This will definitely help.

**Comment by andweber** [comment]
just as reference, there is a pull request for this topic: #434
