### ISSUE TITLE
Phonetisaurus (Pocketsphinx dependency) not configuring

### ISSUE THREAD

**Issue by dmbuchta** [jasperproject/jasper-client#505]
This isn't an issue with Jasper necessarily but I was wondering if anyone else has experienced this issue. I cannot get Phonetisaurus (dependency for PocketSphinx) to configure properly due to an issue with openfst. There's a couple issues that have come up for me trying to get this to work.

1. First, the link provided on jasper doc is dead `http://distfiles.macports.org/openfst/openfst-1.3.3.tar.gz` and `https://phonetisaurus.googlecode.com/files/phonetisaurus-0.7.8.tgz` no longer exist. So I used http://distfiles.macports.org/openfst/openfst-1.5.2.tar.gz and pulled the latest code off of phonetisaurus's available github repo.

2. The command for configuring openfst does not match what Phonetisaurus  docs says to do
**JASPER'S DOCS:** `sudo ./configure --enable-compact-fsts --enable-const-fsts --enable-far --enable-lookahead-fsts --enable-pdt`
**Phonetisaurus DOCS:** `./configure --enable-static --enable-shared --enable-far \ --enable-lookahead-fsts --enable-const-fsts --enable-pdt \ --enable-ngram-fsts --enable-linear-fsts CC=gcc-4.9`
So I'm not sure which one to use? I did try both and neither options seemed to allow Phonetisaurus to be configured. I got an error (I'm not at my machine right now) somewhere along the lines of: `openfst is missing a module. Please make sure it is configured --enable-static --enable-shared --enable-far \ --enable-lookahead-fsts --enable-const-fsts --enable-pdt \ --enable-ngram-fsts --enable-linear-fsts CC=gcc-4.9`

Has anybody experienced this or a similar issue? It does sound like it's a bug with Phonetisaurus (which I already opened with them). Should I try using a different version instead? Or are there any other suggestions for getting pocketsphinx running?

**Comment by dmbuchta** [comment]
The exact error I get from Phonetisaurus is `configure: error: Can't find one or more extensions. OpenFst should have been configured with the following flags: --enable-static --enable-shared --enable-far --enable-lookahead-fsts --enable-const-fsts --enable-pdt --enable-ngram-fsts --enable-linear-fsts`

**Comment by G10DRAS** [comment]
try....

https://phonetisaurus.googlecode.com/files/is2013-conversion.tgz

http://www.openfst.org/twiki/pub/FST/FstDownload/openfst-1.3.4.tar.gz
sudo ./configure --enable-compact-fsts --enable-const-fsts --enable-far --enable-lookahead-fsts --enable-pdt

**Comment by dmbuchta** [comment]
Thanks for your help. For reference I finally got this working by reading over #436.
