### ISSUE TITLE
Inconsistent Threshold when active listening

### ISSUE THREAD

**Issue by dmbuchta** [jasperproject/jasper-client#512]
Has anybody had issues with the activeListen() threshold? I am constantly either being cut off before I'm done speaking or it will continue to run long after I'm done. This gets extremely annoying, especially when I'm trying to debug something.

**Comment by G10DRAS** [comment]
For debuging you can run Jasper in Text mode.
./jasper.py --local --debug

**Comment by dmbuchta** [comment]
After changing to jasper-dev branch the issue seems to be resolved.
