### ISSUE TITLE
alsa audio engine default device

### ISSUE THREAD

**Issue by FreshMK** [jasperproject/jasper-client#529]
Got a problem in alsaaudioengine.py. In my case alsaaudio.pcms(PCM_PLAYBACK) returns no device name 'default'. Consequently I get a "No such file or directory" error. For now I fixed this by hardcoding my devices as device parameters for the PCM object in l.109 : 
pcm_type = alsaaudio.PCM_PLAYBACK if output else alsaaudio.PCM_CAPTURE
        stream = alsaaudio.PCM(type=pcm_type,
                               mode=alsaaudio.PCM_NORMAL,
                               device=u'front:CARD=Device,DEV=0' if not output else u'sysdefault:CARD=ALSA')

Here my output for alsaaudio.pcms(PCM_PLAYBACK):
>>> alsaaudio.pcms(alsaaudio.PCM_PLAYBACK)
[u'null', u'pulse', u'sysdefault:CARD=ALSA']

do i get no 'default' device because my alsa.conf or .asoundrc is configured wrong or is this normal?

**Comment by mattcurrycom** [comment]
probably .asoundrc.  I posted some tools you can use to check it.  They are pinned at the top of the forum.

**Comment by FreshMK** [comment]
Thank you for the help, but I solved this with 'device=self._name'. After that I found a new issue:
Although jasper opens up the streams for recording and playing correctly shortly after recording some frames i get the following error:
sysdefault:CARD=ALSA
opening stream on sysdefault:CARD=ALSA
DEBUG:alsa_1_0_0.alsaaudioengine:output stream opened on device 'sysdefault-card-alsa' (22050 Hz, 1 channel, 16 bit)
DEBUG:alsa_1_0_0.alsaaudioengine:output stream closed on device 'sysdefault-card-alsa'
DEBUG:jasper.conversation:Starting to handle conversation.
INFO:jasper.mic:Waiting for keyword 'JASPER'...
front:CARD=Device,DEV=0
opening stream on front:CARD=Device,DEV=0
DEBUG:alsa_1_0_0.alsaaudioengine:input stream opened on device 'front-card-device-dev-0' (44100 Hz, 1 channel, 16 bit)
DEBUG:jasper.mic:Started recording on device 'front-card-device-dev-0'
DEBUG:jasper.mic:Triggered on SNR of 13.2143341761dB
DEBUG:jasper.mic:Recording's SNR dB: 23.712732
DEBUG:jasper.mic:Recording's SNR dB: 23.144749
DEBUG:jasper.mic:Recording's SNR dB: 22.861521
DEBUG:jasper.mic:Recording's SNR dB: 22.707019
DEBUG:jasper.mic:Recording's SNR dB: 23.280055
DEBUG:jasper.mic:Recording's SNR dB: 23.413286
DEBUG:jasper.mic:Recording's SNR dB: 23.768091
DEBUG:jasper.mic:Recording's SNR dB: 23.899532
DEBUG:jasper.mic:Recording's SNR dB: 23.910396
DEBUG:jasper.mic:Recording's SNR dB: 23.915823
DEBUG:jasper.mic:Recording's SNR dB: 23.904966
DEBUG:jasper.mic:Recording's SNR dB: 23.690489
DEBUG:jasper.mic:Recording's SNR dB: 22.885988
DEBUG:jasper.mic:Recording's SNR dB: 21.675391
DEBUG:jasper.mic:Recording's SNR dB: 19.113189
DEBUG:jasper.mic:Recording's SNR dB: 17.046729
DEBUG:jasper.mic:Recording's SNR dB: 12.637625
DEBUG:jasper.mic:Recording's SNR dB: 7.540122
DEBUG:jasper.mic:Recording's SNR dB: 4.385731
DEBUG:jasper.mic:Recording's SNR dB: 1.835407
DEBUG:jasper.mic:Recorded 40 frames
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): www.google.com
DEBUG:alsa_1_0_0.alsaaudioengine:input stream closed on device 'front-card-device-dev-0'
Traceback (most recent call last):
  File "jasper-dev/Jasper.py", line 5, in <module>
    jasper.main()
  File "/home/pi/jasper-dev/jasper/__main__.py", line 55, in main
    app.run()
  File "/home/pi/jasper-dev/jasper/application.py", line 251, in run
    self.conversation.handleForever()
  File "/home/pi/jasper-dev/jasper/conversation.py", line 40, in handleForever
    input = self.mic.listen()
  File "/home/pi/jasper-dev/jasper/mic.py", line 197, in listen
    self.wait_for_keyword(self._keyword)
  File "/home/pi/jasper-dev/jasper/mic.py", line 161, in wait_for_keyword
    snr = self._snr([frame])
  File "/home/pi/jasper-dev/jasper/mic.py", line 96, in _snr
    rms = audioop.rms(b''.join(frames), int(self._input_bits/8))
audioop.error: not a whole number of frames

after some time I also found the reason for this issue: After the recording stops, the recording stream from the audio engine closes while the for loop in wait_for_keyword() in mic.py is still running. Consequently in the next run of the loop the call snr=self._snr([frame]) gets an invalid frame.
First i tried to solve this with a little delay, but this only works as long as the transcription equals the keyword: in l.156 it is checked whether the keyword is uttered. Because the STT (google STT in my case) has not finished at that moment the loop continues with a closed stream like explained before. With waiting for the transcription i solved this, but only as long as the keyword equals the transcription. Because else the keyword_uttered is not set and the loop continues.

**Comment by FreshMK** [comment]
Ok I got it working. I just changed that in the bus not very elegant... 
http://pastebin.com/bYyviuka
However I wanted to use the alsaengine because with pyaudio i get the 'Input overflowed' error after some time. Now everything finally works perfect! Going to develop a lot of modules now.

**Comment by mattcurrycom** [comment]
yeah, this is an image issue I am fixing.  Not a jasper issue.

**Comment by Electric-9** [comment]
Hello,
I have the same problem, but I cant solve the problem.

> DEBUG:jasper.mic:Recording's SNR dB: 3.925893
DEBUG:jasper.mic:Recording's SNR dB: 3.098039
DEBUG:jasper.mic:Recording's SNR dB: 3.098039
DEBUG:jasper.mic:Recording's SNR dB: 2.182889
DEBUG:jasper.mic:Recorded 47 frames
INFO: cmn.c(175): CMN: 15.97 -5.51 -0.25 -0.67 -0.73 -0.36 -0.44 -0.26  0.09  0.30  0.18  0.19 -0.07
INFO: ngram_search.c(474): Resized backpointer table to 10000 entries
INFO: ngram_search_fwdtree.c(1549):     6289 words recognized (21/fr)
INFO: ngram_search_fwdtree.c(1551):   226619 senones evaluated (753/fr)
INFO: ngram_search_fwdtree.c(1553):   205156 channels searched (681/fr), 12474 1st, 180472 last
INFO: ngram_search_fwdtree.c(1557):    10196 words for which last channels evaluated (33/fr)
INFO: ngram_search_fwdtree.c(1560):    12203 candidate words for entering last phone (40/fr)
INFO: ngram_search_fwdtree.c(1562): fwdtree 0.24 CPU 0.080 xRT
INFO: ngram_search_fwdtree.c(1565): fwdtree 0.24 wall 0.079 xRT
INFO: ngram_search_fwdflat.c(302): Utterance vocabulary contains 47 words
INFO: ngram_search_fwdflat.c(937):     3580 words recognized (12/fr)
INFO: ngram_search_fwdflat.c(939):   201760 senones evaluated (670/fr)
INFO: ngram_search_fwdflat.c(941):   225618 channels searched (749/fr)
INFO: ngram_search_fwdflat.c(943):     9782 words searched (32/fr)
INFO: ngram_search_fwdflat.c(945):     7291 word transitions (24/fr)
INFO: ngram_search_fwdflat.c(948): fwdflat 0.14 CPU 0.047 xRT
INFO: ngram_search_fwdflat.c(951): fwdflat 0.15 wall 0.049 xRT
INFO: ngram_search.c(1214): &lt;/s&gt; not found in last frame, using &lt;sil&gt;.299 instead
INFO: ngram_search.c(1266): lattice start node &lt;s&gt;.0 end node &lt;sil&gt;.132
INFO: ngram_search.c(1294): Eliminated 209 nodes before end node
INFO: ngram_search.c(1399): Lattice has 472 nodes, 1186 links
INFO: ps_lattice.c(1365): Normalizer P(O) = alpha(&lt;sil&gt;:132:299) = -1754463
INFO: ps_lattice.c(1403): Joint P(O,S) = -1786212 P(S|O) = -31749
INFO: ngram_search.c(888): bestpath 0.02 CPU 0.007 xRT
INFO: ngram_search.c(891): bestpath 0.02 wall 0.006 xRT
DEBUG:sphinx_1_0_0.sphinxplugin:INFO: cmd_ln.c(691): Parsing command line:
DEBUG:sphinx_1_0_0.sphinxplugin:\
DEBUG:sphinx_1_0_0.sphinxplugin:-hmm /usr/share/pocketsphinx/model/hmm/en_US/hub4wsj_sc_8k \
DEBUG:sphinx_1_0_0.sphinxplugin:-lm /home/pi/.jasper/vocabularies/en-US/sphinx/keyword/languagemodel \
DEBUG:sphinx_1_0_0.sphinxplugin:-dict /home/pi/.jasper/vocabularies/en-US/sphinx/keyword/dictionary \
DEBUG:sphinx_1_0_0.sphinxplugin:-logfn /tmp/psdecoder_l3or1S.log
DEBUG:sphinx_1_0_0.sphinxplugin:
DEBUG:sphinx_1_0_0.sphinxplugin:Current configuration:
DEBUG:sphinx_1_0_0.sphinxplugin:[NAME]          [DEFLT]         [VALUE]
DEBUG:sphinx_1_0_0.sphinxplugin:-agc            none            none
DEBUG:sphinx_1_0_0.sphinxplugin:-agcthresh      2.0             2.000000e+00
DEBUG:sphinx_1_0_0.sphinxplugin:-alpha          0.97            9.700000e-01
DEBUG:sphinx_1_0_0.sphinxplugin:-ascale         20.0            2.000000e+01
DEBUG:sphinx_1_0_0.sphinxplugin:-aw             1               1
DEBUG:alsa_1_0_0.alsaaudioengine:input stream closed on device 'plughwcardub1dev0'
Traceback (most recent call last):
DEBUG:sphinx_1_0_0.sphinxplugin:-backtrace      no              no
  File "./Jasper.py", line 5, in &lt;module&gt;
    DEBUG:sphinx_1_0_0.sphinxplugin:-beam               1e-48           1.000000e-48
jasper.main()
  File "/home/pi/jasper-client/jasper/__main__.py", line 55, in main
    app.run()
DEBUG:sphinx_1_0_0.sphinxplugin:-bestpath       yes             yes
  File "/home/pi/jasper-client/jasper/application.py", line 255, in run
    self.conversation.handleForever()
DEBUG:sphinx_1_0_0.sphinxplugin:-bestpathlw     9.5             9.500000e+00
  File "/home/pi/jasper-client/jasper/conversation.py", line 40, in handleForever
DEBUG:sphinx_1_0_0.sphinxplugin:-bghist         no              no
    input = self.mic.listen()
DEBUG:sphinx_1_0_0.sphinxplugin:-ceplen         13              13
  File "/home/pi/jasper-client/jasper/mic.py", line 212, in listen
    DEBUG:sphinx_1_0_0.sphinxplugin:-cmn                current         current
self.wait_for_keyword(self._keyword)
  File "/home/pi/jasper-client/jasper/mic.py", line 178, in wait_for_keyword
DEBUG:sphinx_1_0_0.sphinxplugin:-cmninit        8.0             8.0
    DEBUG:sphinx_1_0_0.sphinxplugin:-compallsen no              no
snr = self._snr([frame])
  File "/home/pi/jasper-client/jasper/mic.py", line 102, in _snr
DEBUG:sphinx_1_0_0.sphinxplugin:-debug                          0
    DEBUG:sphinx_1_0_0.sphinxplugin:-dict                               /home/pi/.jasper/vocabularies/en-US/sphinx/keyword/dictionary
rms = audioop.rms(b''.join(frames), int(self._input_bits/8))
audioopDEBUG:sphinx_1_0_0.sphinxplugin:-dictcase        no              no
.error: not a whole number of frames

With pyaudio I got the same error as @FreshMK (Input overflowed). So I switched to alsa. With alsa I also have a better output sound quality.
But Jasper crashes after a random amount of keyword checks. Some time by the first noise, sometimes it take up to 10 "keyword searches".
I also noticed the "stream closed" but I dont know what to do.
