### ISSUE TITLE
Up-to-date Installation Guide

### ISSUE THREAD

**Issue by TheTyrius** [jasperproject/jasper-client#530]
Is there any up to date information on how to get jasper-dev set up and running?
I'd really like to start experimenting, but the overhead is quite big, I've tried following the documentation, but it is outdated, it is unclear to me what requirements are to be met, and I found that the master doesn't work with latest sphinx etc. If anyone could explain to me ort point me to information, I'd be thankful :)

**Comment by andweber** [comment]
there is a google group for support: https://groups.google.com/forum/#!forum/jasper-support-forum. 

If you get master running, dev should run too, or post specific problems. Lots of info are already here in the issues.

**Comment by LordTyrius** [comment]
Thank you, I guess I'll try the Raspi 2 image Curry posted over there, thanks to the afford in this place.
I'll keep experimenting though, I'd prefer installing it myself ;)

**Comment by mattcurrycom** [comment]
I am updating the RPI2 and RPI3 images.  Once they are to a stable place I will document everything for everyone and post it.  My apologies for the delay; but I have a log going on.

Thanks.

**Comment by ajithkotian** [comment]
Thank you. Eagerly waiting for the new images. I can test and provide feedback. Appreciated.

**Comment by mattcurrycom** [comment]
Thank you, I found a couple other small issues; so i am fixing those before I re-release.
