### ISSUE TITLE
WATCH FOR @mattcurrycom. I wll not be silenced.

### ISSUE THREAD

**Issue by chrobione** [jasperproject/jasper-client#554]
To all those thinking of helping  @mattcurrycom  be careful if you challenge him in anyway he will ban you from everything..  Just thought everyone should know that I am not going away and more information will be posted here:
https://github.com/chrobione/Jasper2fork

Discord: https://discord.gg/kSnVC9C

Peace out!!

**Comment by TuxSeb** [comment]
Hello, 

Now i don't know if i stay in Jasper community with Matt or join you .. too bad that you leave the project of Mattcurry

**Comment by TuxSeb** [comment]
I create a programm in python with Randint module that choose my side .. 

```
while (c != 5):
	chooseyourside()
	c = c +1

	
Jasper with Chris
Jasper with Matthew
Jasper with Chris
Jasper with Chris
Jasper with Matthew

```

and the program choose your project

**Comment by chrobione** [comment]
My hope is that Jasper2 will merge back to Jasper, only time will show on this.

**Comment by chrobione** [comment]
LOL! the ban hammer has spoken. Wow its amazing two people that helped to revieve the dev branch and he bans both.

P.S. We are playing on discord  and open to everyone even the guys that dont agree.

**Comment by chrobione** [comment]
Its funny my post to the main support channel have been deleted.  Such a shame poor, poor, Matt.

**Comment by chrobione** [comment]
You will not silence me Matt.

**Comment by chrobione** [comment]
Wonder why this one is still here.  Maybe cause he doesn't have control of it.

**Comment by mattcurry** [comment]
You have the wrong guy.

**Comment by chrobione** [comment]
I am sorry @mattcurry .  updated with correct information

**Comment by Holzhaus** [comment]
@chrobione Could you email me some details? I'll ask Matt for his side of the story. I hope we can sort this out ASAP.

**Comment by chrobione** [comment]
Sent to your googlemail account.

**Comment by mattcurrycom** [comment]
Pursuing personal opinions and vendettas on Git hub is very unprofessional. @chrobione 

I have unsubscribed; and I will not take part in such immature conversation.  If you have a problem with me; deal like it like a man. Otherwise keep commenting here... Git hub has the space, and honestly it doesn't affect me either way.

**Comment by chrobione** [comment]
Nice job on the corporate caned response.

**Comment by mattcurrycom** [comment]
Please stop impersonating me, that is  illegal, and I have full IP history. I have removed your posts as me "mattucarry123@gmail.com"

**Comment by Holzhaus** [comment]
I feel like this is a personal fight between you two and this conversation is not getting us anywhere. I'll close this and talk to the other project members about what to do next.

**Comment by OdysLam** [comment]
Hey, I don't know what happened but as I have been monitoring the jasper project for like a month or so, I can definitely say that Matt is quite some time in further enriching and upgrade the project, on top of that he is quite the FAQ man in the slack group, assisting virtually everyone.

Although I don't know what happened, I think I should underline how helpful and committed he is,at least from my point of view.

**Comment by chrobione** [comment]
It seems that I am not the only one that will speak out about the issue with the project.
