### ISSUE TITLE
unexpected keyword argument 'hmm'

### ISSUE THREAD

**Issue by simon1tan** [jasperproject/jasper-client#597]
Was getting this error: TypeError: __init__() got an unexpected keyword argument 'hmm'
Someone suggested using jasper-dev but same error. After googling around, I modified stt,py to this:

config = Decoder.default_config()
config.set_string('-hmm', os.path.join(modeldir, 'en-us/en-us'))
config.set_string('-dict', os.path.join(modeldir, 'en-us/cmudict-en-us.dict'))
decoder = Decoder(config)

Now the error is: RuntimeError: Decoder_start_utt returned -1

Anybody know how to get past this? 

BTW, compiling this on Ubuntu 16.

**Comment by G10DRAS** [comment]
could you post pocketsphinx configuration from your profile.yml

**Comment by simon1tan** [comment]
profile.yml looks like this:
pocketsphinx:
   fst_model: '/home/stan/projects/phonetisaurus/g014b2b.fst'
   hmm_dir: '/usr/share/pocketsphinx/model/hmm/en_US/hub4wsj_sc_8k'

Ok, I think I got past that by modifying the code to this(I did not specify LM):
`       config = ps.Decoder.default_config()
        config.set_string('-hmm', hmm_dir)        
        modeldir= "/usr/share/pocketsphinx/model/"
        config.set_string('-lm', '/usr/share/pocketsphinx/model/lm/en_US/en-70k-0.1.lm')
        config.set_string('-dict', os.path.join(modeldir, 'en-us/cmudict-en-us.dict'))
        self._decoder = ps.Decoder(config)
`

Downloaded some LM files (en-70k-0.1.lm), I think this is going to work. 

Thanks for helping me work through this.  Going to close this.

**Comment by G10DRAS** [comment]
No, It will not going to work. 
In Jasper, no need to download LM.
Jasper generates one for itself.
