### ISSUE TITLE
Add new words to vocabulary (PocketSphinx)

### ISSUE THREAD

**Issue by jeroenpeeters** [jasperproject/jasper-client#609]
I'm relatively new to STT and TTS engines. So far I have found Jasper quite simple to install. I want to do offline STT and TTS so I use PocketSphinx and espeak.

What is unclear to me is how I extend the vocabulary of PocketSphinx. I understand it comes with a default vocabulary that plays nice with the default Jasper modules. However, when I develop my own module I need to extend the vocabulary as well. At least, that is how I understand it, correct?

I've tried adding words to the vocabulary, but Jasper doesn't recognize them.

My question: How to I extend the vocabulary of PocketSphinx so that Jasper recognizes the words.

**Comment by G10DRAS** [comment]
No need to add new WORDS in vocabulary, Jasper will do it for you. Add your module and restart Jasper.
