### ISSUE TITLE
Talking to Jasper through Siri

### ISSUE THREAD

**Issue by thesanjeetc** [jasperproject/jasper-client#614]
Hi there!

This is not an issue but I just wanted to make this hack known to more people. 

I have recently found a hack and wrote some python code to enable you to talk to Jasper through Siri, on your iOS device. You do this by creating a Note with Siri which syncs with our gmail account and is fetched by the python script and inputted into the 'brain' of Jasper.

The way this works means that you can send a command through Siri, to Jasper which will be executes as if you were speaking to it, can be sent from anywhere in the world, opening up many possibilities.

Of course, you can also talk to Jasper directly as well.

It is very cool once you get it working. The setup is quite simple - here is my post to explain in more detail and a link to the scripts you need to replace: https://thereallycoolstuff.wordpress.com/2017/03/04/talking-to-jasper-using-siri/

I hope you guys enjoy it. Thanks.

**Comment by Mvpchris** [comment]
Link does not work to view your steps

**Comment by thesanjeetc** [comment]
Sorry - the link tries to find the page in GitHub. I have updated it without the link tags. Thanks.

**Comment by Mvpchris** [comment]
Ok Im trying to run the script. I get an error saying username is not defined
