### ISSUE TITLE
Weather "Cant access that information"

### ISSUE THREAD

**Issue by Mvpchris** [jasperproject/jasper-client#616]
[Weather.txt](https://github.com/jasperproject/jasper-client/files/931199/Weather.txt)
 
When I ask Jasper what is the weather. It responds with "Im sorry I can't seem to access that information...."
I have my location and wmoid entered in my profile but I still can't get the correct response.

wmo_id: 72372
location: Nashville

**Comment by G10DRAS** [comment]
You can try relatively new weather module based on Open Weather Map.
https://github.com/G10DRAS/JasperModules/blob/master/README.md#openweathermap-module

**Comment by Mvpchris** [comment]
Open Weather worked for me. thanks!
