### ISSUE TITLE
cmuclmtk is not defined

### ISSUE THREAD

**Issue by Yberamos** [jasperproject/jasper-client#627]
I've been trying to install jasper all day, and when finally I'm supposed to launch it I have this issue. Any idea for a fix? (I've reinstalled cmuclmtk several times, still not working).

```
pi@raspberrypi:~ $ /home/pi/jasper/jasper.py
No handlers could be found for logger "client.vocabcompiler"
*******************************************************
*             JASPER - THE TALKING COMPUTER           *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
ERROR:client.vocabcompiler:Fatal compilation Error occured, cleaning up...
Traceback (most recent call last):
  File "/home/pi/jasper/client/vocabcompiler.py", line 163, in compile
    self._compile_vocabulary(phrases)
  File "/home/pi/jasper/client/vocabcompiler.py", line 269, in _compile_vocabulary
    vocabulary = self._compile_languagemodel(text, self.languagemodel_file)
  File "/home/pi/jasper/client/vocabcompiler.py", line 290, in _compile_languagemodel
    cmuclmtk.text2vocab(text, vocab_file)
NameError: global name 'cmuclmtk' is not defined
ERROR:root:Error occured!
Traceback (most recent call last):
  File "/home/pi/jasper/jasper.py", line 146, in <module>
    app = Jasper()
  File "/home/pi/jasper/jasper.py", line 109, in __init__
    stt_passive_engine_class.get_passive_instance(),
  File "/home/pi/jasper/client/stt.py", line 48, in get_passive_instance
    return cls.get_instance('keyword', phrases)
  File "/home/pi/jasper/client/stt.py", line 40, in get_instance
    vocabulary.compile(phrases)
  File "/home/pi/jasper/client/vocabcompiler.py", line 171, in compile
    raise e
NameError: global name 'cmuclmtk' is not defined

```

PS: I'm on raspian lite

**Comment by G10DRAS** [comment]
How did you install cmuclmtk?

Try below procedure:
1. Run
`sudo pip install --upgrade cmuclmtk`
2. Download pkg:
[cmuclmtk](https://github.com/G10DRAS/Raspbian-Jessie-Pkgs/blob/master/cmuclmtk_3alpha-1_armhf.deb)
3. Install it:
`sudo dpkg -i cmuclmtk_3alpha-1_armhf.deb`
4. Restart Jasper

**Comment by Yberamos** [comment]
I installed it using:
`svn co https://svn.code.sf.net/p/cmusphinx/code/trunk/cmuclmtk/`

1. I got this:
`Requirement already up-to-date: cmuclmtk in /usr/local/lib/python3.4/dist-packages`

Tried the procedure you proposed but got the same result.
I do not know python so what I'm about to say might be stupid but, I had to modify the populate script because it was using old function no longer avaible in python3 (i.e. raw_input). And I had severl problems where it didn't find some modules. I solver that issue by using
`sudo apt-get install python-X`
So my theory is that maybe it's looking for cmuclmtk in the wrong directory? Like pyhton instead of python3.4. But maybe what I'm saying is completly stupid.

PS: I looked on the net to see how to know wich modules ar installed and when I do `pip freeze` I see `cmuclmtk==0.1.5`.

**Comment by asuthoshcr** [comment]
how did you solve this issue YBERAMOS.
i have the same issue an the command "sudo apt-get install python-X" doesn't works.

pi@raspberrypi:~ $ sudo apt-get install python-X
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package python-X
what to do?
i need to solve this issue.

**Comment by Yberamos** [comment]
I didn't solved it. I had other problems and simply ditch my project. Sorry that I can't help you.

**Comment by SteveQuinn1** [comment]
I've got the same issues
