### ISSUE TITLE
Can someone please tell me how they got this working?

### ISSUE THREAD

**Issue by bhodgs01** [jasperproject/jasper-client#66]
Hello,

I have been trying for days to get this working without success.  I have tried loading the pre-built image 3 times and it doesn't work.  

When I run main.py from the directory, I get this:

INFO: acmod.c(246): Parsed model-specific feature parameters from
/usr/local/share/pocketsphinx/model/hmm/en_US/hub4wsj_sc_8k/feat.params
INFO: feat.c(713): Initializing feature stream to type: '1s_c_d_dd',
ceplen=13, CMN='current', VARNORM='no', AGC='none'
INFO: cmn.c(142): mean[0]= 12.00, mean[1..12]= 0.0
INFO: acmod.c(167): Using subvector specification 0-12/13-25/26-38
INFO: mdef.c(517): Reading model definition:
/usr/local/share/pocketsphinx/model/hmm/en_US/hub4wsj_sc_8k/mdef
INFO: mdef.c(528): Found byte-order mark BMDF, assuming this is a
binary mdef file
INFO: bin_mdef.c(336): Reading binary model definition:
/usr/local/share/pocketsphinx/model/hmm/en_US/hub4wsj_sc_8k/mdef
INFO: bin_mdef.c(513): 50 CI-phone, 143047 CD-phone, 3
emitstate/phone, 150 CI-sen, 5150 Sen, 27135 Sen-Seq
INFO: tmat.c(205): Reading HMM transition probability matrices:
/usr/local/share/pocketsphinx/model/hmm/en_US/hub4wsj_sc_8k/transition_matrices
INFO: acmod.c(121): Attempting to use SCHMM computation module
INFO: ms_gauden.c(198): Reading mixture gaussian parameter:
/usr/local/share/pocketsphinx/model/hmm/en_US/hub4wsj_sc_8k/means
INFO: ms_gauden.c(292): 1 codebook, 3 feature, size:
INFO: ms_gauden.c(294):  256x13
INFO: ms_gauden.c(294):  256x13
INFO: ms_gauden.c(294):  256x13
INFO: ms_gauden.c(198): Reading mixture gaussian parameter:
/usr/local/share/pocketsphinx/model/hmm/en_US/hub4wsj_sc_8k/variances
INFO: ms_gauden.c(292): 1 codebook, 3 feature, size:
INFO: ms_gauden.c(294):  256x13
INFO: ms_gauden.c(294):  256x13
INFO: ms_gauden.c(294):  256x13
INFO: ms_gauden.c(354): 0 variance values floored
INFO: s2_semi_mgau.c(903): Loading senones from dump file
/usr/local/share/pocketsphinx/model/hmm/en_US/hub4wsj_sc_8k/sendump
INFO: s2_semi_mgau.c(927): BEGIN FILE FORMAT DESCRIPTION
INFO: s2_semi_mgau.c(1022): Using memory-mapped I/O for senones
INFO: s2_semi_mgau.c(1296): Maximum top-N: 4 Top-N beams: 0 0 0
INFO: dict.c(317): Allocating 4130 \* 20 bytes (80 KiB) for word entries
INFO: dict.c(332): Reading main dictionary: dictionary.dic
ERROR: "dict.c", line 193: Line 13: Phone 'KNOCK' is mising in the
acoustic model; word 'KNOCK' ignored
INFO: dict.c(211): Allocated 0 KiB for strings, 0 KiB for phones
INFO: dict.c(335): 22 words read
INFO: dict.c(341): Reading filler dictionary:
/usr/local/share/pocketsphinx/model/hmm/en_US/hub4wsj_sc_8k/noisedict
INFO: dict.c(211): Allocated 0 KiB for strings, 0 KiB for phones
INFO: dict.c(344): 11 words read
INFO: dict2pid.c(396): Building PID tables for dictionary
INFO: dict2pid.c(404): Allocating 50^3 \* 2 bytes (244 KiB) for
word-initial triphones
INFO: dict2pid.c(131): Allocated 30200 bytes (29 KiB) for word-final triphones
INFO: dict2pid.c(195): Allocated 30200 bytes (29 KiB) for single-phone
word triphones
ERROR: "ngram_model_arpa.c", line 466: File
/usr/local/share/pocketsphinx/model/lm/languagemodel.lm not found
ERROR: "ngram_model_dmp.c", line 106: Dump file
/usr/local/share/pocketsphinx/model/lm/languagemodel.lm not found
ERROR: "ngram_search.c", line 208: Failed to read language model file:
/usr/local/share/pocketsphinx/model/lm/languagemodel.lm

and when I run python /home/pi/jasper/client/main.py I am getting this:
# 

 JASPER The Talking Computer
#  Copyright 2013 Shubhro Saha & Charlie Marsh

Traceback (most recent call last):
  File "/home/pi/jasper/client/main.py", line 21, in <module>
    profile = yaml.safe_load(open("profile.yml", "r"))
IOError: [Errno 2] No such file or directory: 'profile.yml'

Since the compiled image doesn't work, I have been going through the manual installation.  I get to the last step of running ./compile-fst.sh and it says 

fstcompile --ssymbols=g014b2b.ssyms --isymbols=g014b2b.isyms --keep_isymbols --osymbols=g014b2b.osyms --keep_osymbols g014b2b.fst.txt > g014b2b.fst
./compile-fst.sh: line 8: fstcompile: command not found

I can understand making a mistake doing the manual process but why isn't the image working?

Please help!  thanks,

Blake

**Comment by shajmaan** [comment]
IOError: [Errno 2] No such file or directory: '/root/.jasper/profile.yml'

i have the same issue
i have manually compiled image
the image does exist in ~/.jasper/profile.yml
am new to this so can u please help me out :)

**Comment by Holzhaus** [comment]
> IOError: [Errno 2] No such file or directory: '/root/.jasper/profile.yml'
> [...]
> the image does exist in ~/.jasper/profile.yml

Jasper always loads the config from`~/.jasper/profile.yml` where `~` is the home directory of your current user. You probably used `sudo ./jasper` instead of just `./jasper.py, so that Jasper is running as root - thus, your home folder isn't `/home/pi/` anymore, but `/root`.

Just don't run jasper as root.

**Comment by shajmaan** [comment]
hey thanks aloy
am getting an 'error 403 api might be invalid' when using google api eventhough my api is correct :/

it is transcribing when i used wit though
