### ISSUE TITLE
RuntimeError:hmm_dir

### ISSUE THREAD

**Issue by Shifat7788** [jasperproject/jasper-client#679]
pi@raspberrypi:~ $ /home/pi/jasper/jasper.py
*******************************************************
*             JASPER - THE TALKING COMPUTER           *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
ERROR:client.stt:hmm_dir '/usr/local/share/pocketsphinx/model/hmm/en_US/hub4wsj_sc_8k' does not exist! Please make sure that you have set the correct hmm_dir in your profile.
ERROR:root:Error occured!
Traceback (most recent call last):
  File "/home/pi/jasper/jasper.py", line 146, in <module>
    app = Jasper()
  File "/home/pi/jasper/jasper.py", line 109, in __init__
    stt_passive_engine_class.get_passive_instance(),
  File "/home/pi/jasper/client/stt.py", line 48, in get_passive_instance
    return cls.get_instance('keyword', phrases)
  File "/home/pi/jasper/client/stt.py", line 42, in get_instance
    instance = cls(**config)
  File "/home/pi/jasper/client/stt.py", line 105, in __init__
    raise RuntimeError(msg)
RuntimeError: hmm_dir '/usr/local/share/pocketsphinx/model/hmm/en_US/hub4wsj_sc_8k' does not exist! Please make sure that you have set the correct hmm_dir in your profile.
------
------
My Profile:
carrier: ''
first_name: Shifat
gmail_address: shifatbaig@gmail.com
gmail_password: ''
last_name: Baig
location: Munich
phone_number: ''
prefers_email: true
stt_engine: sphinx
pocketsphinx-0.8:
  fst_model: '../phonetisaurus/g014b2b.fst'
  mm_dir: '/home/pi/pocketsphinx-0.8/model/hmm/en_US/hub4wsj_sc_8k'
tts_engine: google-tts
timezone: Europe/Berlin

In my profile i have specified another path but still its getting the previous path. I don't have the root access so how can i move file to usr/local/share or what can be the best solution. Please help...

**Comment by G10DRAS** [comment]
`mm_dir: '/home/pi/pocketsphinx-0.8/model/hmm/en_US/hub4wsj_sc_8k'`
should be
`hmm_dir: '/home/pi/pocketsphinx-0.8/model/hmm/en_US/hub4wsj_sc_8k'`

**Comment by Shifat7788** [comment]
carrier: ''
first_name: Shifat
gmail_address: shifatbaig@gmail.com
gmail_password: ''
last_name: Baig
location: Munich
phone_number: ''
prefers_email: true
stt_engine: sphinx
pocketsphinx-0.8:
  fst_model: '../phonetisaurus/g014b2b.fst'
  hmm_dir: '/home/pi/pocketsphinx-0.8/model/hmm/en_US/hub4wsj_sc_8k'
tts_engine: google-tts
timezone: Europe/Berlin
............
pi@raspberrypi:~ $ sudo nano ~/.jasper/profile.yml
pi@raspberrypi:~ $ /home/pi/jasper/jasper.py
*******************************************************
*             JASPER - THE TALKING COMPUTER           *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
ERROR:client.stt:hmm_dir '/usr/local/share/pocketsphinx/model/hmm/en_US/hub4wsj_sc_8k' does not exist! Please make sure that you have set the correct hmm_dir                             in your profile.
ERROR:root:Error occured!
Traceback (most recent call last):
  File "/home/pi/jasper/jasper.py", line 146, in <module>
    app = Jasper()
  File "/home/pi/jasper/jasper.py", line 109, in __init__
    stt_passive_engine_class.get_passive_instance(),
  File "/home/pi/jasper/client/stt.py", line 48, in get_passive_instance
    return cls.get_instance('keyword', phrases)
  File "/home/pi/jasper/client/stt.py", line 42, in get_instance
    instance = cls(**config)
  File "/home/pi/jasper/client/stt.py", line 105, in __init__
    raise RuntimeError(msg)
RuntimeError: hmm_dir '/usr/local/share/pocketsphinx/model/hmm/en_US/hub4wsj_sc_8k' does not exist! Please make sure that you have set the correct hmm_dir in                             your profile.

**It was a typing mistake before. It shows the same error. Is there any way i can move the folder ?**

**Comment by G10DRAS** [comment]
Make sure you have downloaded the correct acoustic model and set the correct path.
Else download the latest acoustic model from cmusphinx source forge site into your home dir and set the path to it in profile.yml
