### ISSUE TITLE
Jabra Mic Working, but Speakers not

### ISSUE THREAD

**Issue by DanielSDiggs** [jasperproject/jasper-client#693]
Currently Jabra mic can accept sound
Jabra speakers can output sound
Jasper can pick up Jabra mic
Jasper cannot output sound through Jabra speakers

I'm using a Jabra 510- connected through bluetooth

**Comment by G10DRAS** [comment]
It is not clear, 
-- what you had done so for, 
-- how did you tested Jabra BT Mic with Jasper, 
-- what configuration and libs you used for it ??

**Comment by DanielSDiggs** [comment]
Thanks @G10DRAS , I'm not really sure how but I was able to fix it by changing the sound files from mp3 to wavs.
