### ISSUE TITLE
i cant get jasper to work on my raspberry 3 b+

### ISSUE THREAD

**Issue by rubeng0182** [jasperproject/jasper-client#703]
i did everything acording to the jasper website
and i get this

pi@raspberrypi:~ $ /home/pi/jasper/jasper.py

No handlers could be found for logger "cmuclmtk"
*******************************************************
*             JASPER - THE TALKING COMPUTER           *
* (c) 2015 Shubhro Saha, Charlie Marsh & Jan Holthuis *
*******************************************************
ALSA lib pcm_dmix.c:1052:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bl                                                                                                                                                             uealsa.device'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned err                                                                                                                                                             or: No such file or directory
ALSA lib conf.c:4996:(snd_config_expand) Args evaluate error: No such file or di                                                                                                                                                             rectory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM bluealsa
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bl                                                                                                                                                             uealsa.device'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned err                                                                                                                                                             or: No such file or directory
ALSA lib conf.c:4996:(snd_config_expand) Args evaluate error: No such file or di                                                                                                                                                             rectory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM bluealsa
ALSA lib pcm_dmix.c:1052:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1052:(snd_pcm_dmix_open) unable to open slave
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unloc                                                                                                                                                             k
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unloc                                                                                                                                                             k
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.                                                                                                                                                             py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding c                                                                                                                                                             ertificate verification is strongly advised. See: https://urllib3.readthedocs.or                                                                                                                                                             g/en/latest/security.html
  InsecureRequestWarning)
WARNING:client.stt:Empty response: Nothing has been transcribed.
WARNING:client.stt:Empty response: Nothing has been transcribed.
WARNING:client.stt:Empty response: Nothing has been transcribed.
WARNING:client.stt:Empty response: Nothing has been transcribed.
WARNING:client.stt:Empty response: Nothing has been transcribed.
WARNING:client.stt:Empty response: Nothing has been transcribed.
WARNING:client.stt:Empty response: Nothing has been transcribed.
WARNING:client.stt:Empty response: Nothing has been transcribed.
WARNING:client.stt:Empty response: Nothing has been transcribed.
WARNING:client.stt:Empty response: Nothing has been transcribed.
WARNING:client.stt:Empty response: Nothing has been transcribed.
WARNING:client.stt:Empty response: Nothing has been transcribed.
WARNING:client.stt:Empty response: Nothing has been transcribed.
Traceback (most recent call last):
  File "/home/pi/jasper/jasper.py", line 151, in <module>
    app.run()
  File "/home/pi/jasper/jasper.py", line 121, in run
    conversation.handleForever()
  File "/home/pi/jasper/client/conversation.py", line 31, in handleForever
    threshold, transcribed = self.mic.passiveListen(self.persona)
  File "/home/pi/jasper/client/mic.py", line 163, in passiveListen
    data = stream.read(CHUNK)
  File "/usr/lib/python2.7/dist-packages/pyaudio.py", line 608, in read
    return pa.read_stream(self._stream, num_frames, exception_on_overflow)
IOError: [Errno -9981] Input overflowed

Can anyone help me?

**Comment by G10DRAS** [comment]
Try increasing CHUNK size to 2048 or 4096

**Comment by rubeng0182** [comment]
@G10DRAS how do i do that excactly?

**Comment by G10DRAS** [comment]
In code, mic.py
