### ISSUE TITLE
fstcompile: command not found

### ISSUE THREAD

**Issue by vpuna** [jasperproject/jasper-client#76]
Hi I was executing all the commands for the manual installation. At the final stage
cd g014b2b/
./compile-fst.sh
i get the error 
fstcompile --ssymbols=g014b2b.ssyms --isymbols=g014b2b.isyms --keep_isymbols --osymbols=g014b2b.osyms --keep_osymbols g014b2b.fst.txt > g014b2b.fst
./compile-fst.sh: line 8: fstcompile: command not found

Please help!

**Comment by sunny1986** [comment]
I tried with the OpenFST 1.3.3 version with the swap space and it shows a swap space of more than 512MB but it still doesn't work.

I am trying to install it on a Raspberry Pi B+ which has a 512 MB RAM. Having Googled about installing the OpenFST on a Linux platform I came across a point where it said I should have my swap space twice that of my RAM which is 512 MB. 

Do you guys think this could be as issue? Or should I try installing version 1.3.4 ?

**Comment by AndyMiao** [comment]
I got the same error, anyone have solved this?

fstcompile --ssymbols=g014b2b.ssyms --isymbols=g014b2b.isyms --keep_isymbols --osymbols=g014b2b.osyms --keep_osymbols g014b2b.fst.txt > g014b2b.fst
./compile-fst.sh: line 8: fstcompile: command not found

**Comment by alexjfno1** [comment]
I ran `sudo apt-get -t experimental install libfst-tools` which fixed the command not found error but now I get:

```bash
pi@raspberrypi:~/jasper/g014b2b $ ./compile-fst.sh
fstcompile --ssymbols=g014b2b.ssyms --isymbols=g014b2b.isyms --keep_isymbols --osymbols=g014b2b.osyms --keep_osymbols g014b2b.fst.txt > g014b2b.fst
./compile-fst.sh: line 8:  1135 Illegal instruction     fstcompile --ssymbols=g014b2b.ssyms --isymbols=g014b2b.isyms --keep_isymbols --osymbols=g014b2b.osyms --keep_osymbols g014b2b.fst.txt > g014b2b.fst
```

**Comment by Holzhaus** [comment]
That libfst-tools build seems to be broken. Maybe try to update the package? Also don't forget to file a bug report to the debian package maintainer.

**Comment by Taconut** [comment]
I'm having this issue as well. Both the compilefst and phonetisaurus-g2p commands output "Illegal Instruction." This is on a Method 1 install where I added phonetisaurus through the apt-get method.

**Comment by gertjaap** [comment]
For people having the Illegal Instruction error, what model of RPi are you running on? I had this issue, but it was on a RPi zero. The packages in jesse-experimental are built for armv7 while my board (Pi Zero) has an armv6. After coming across https://groups.google.com/forum/#!topic/jasper-support-forum/_i1PDuW-fSQ on the support forum, i added that repo and the fstcompile command started working properly.

**Comment by alexjfno1** [comment]
@gertjaap I am running RPI B+

**Comment by gertjaap** [comment]
The RPI B+ has an Armv6 too. Using the debian packages from experimental on Raspbian Jesse will therefore not work, they are Armv7. Try adding the repo specified in the link i included, uninstall the previous packages, and then retry. I managed to compile the FST with that on my Pi Zero.

**Comment by LuisCDias** [comment]
I am running RPI B+ with debian and this line
sudo apt-get -t experimental install libfst-tools
fixed it.

**Comment by jgoldmann** [comment]
@gertjaap 's link helped me to proceed, thanks! (also RPI B+ debian jessie )

**Comment by drunkgunner** [comment]
I got the same error: ./compile-fst.sh: line 8: fstcompile: command not found

I installed the libfst-tools package from the standard repos and it worked!
sudo apt-get install libfst-tools

Raspberry Pi 2 Model B+ v1.1
Raspbian Jesse, version March 2016, release date 2016-03-18

**Comment by ibariens** [comment]
thanks @drunkgunner seems to work perfectly!
