### ISSUE TITLE
Give "Jasper" a different name

### ISSUE THREAD

**Issue by ivdma** [jasperproject/jasper-client#8]
Is it possible to set Jasper's name in configuration? This is useful in the following scenarios:

1) Lots of Dutch people are called Jasper. 
2) Some people can't pronounce some letters.

Last example is personal: I stutter, and have difficulties with some letters from time to time. Sounds "dje" (English way to pronounce Jasper) and "ya" (Dutch way to pronounce Jasper) are difficult for me to pronounce.

**Comment by svanlan1** [comment]
Is this still valid?  And if so, where are dictionary_persona.dic and sentences_persona.txt?

**Comment by professorDODO** [comment]
I replaced "JASPER", which now could be found in jasper.py line 117, with my choosen name. I addes it to dictionary_persona.dic compiled it and replaced the .dic and .lm files in ~/jasper/static/. My problem is, that he still recognizes the words from the old .dic file (tested by deleting JASPER, but he still recognizes it). Are the .dic .lm files, save somewhere else or in some kind of cache?

**Comment by amitch56** [comment]
@profoessorDODO
Was there anything else besides updating the keyword_phrases file with your new chosen name?  I'm replaced that file, along with the .dic and .lm files and the new name isn't being recognized (though the old one is and its been removed from the above mentioned files).  I've rebooted a few times too.

**Comment by FreakErn** [comment]
You'll have to update the listening word in the [jasper.py](https://github.com/jasperproject/jasper-client/blob/master/jasper.py#L117) in line 117
